Repository wandb/wandb, pull requests merged in 2022-12, with the labels that each got.

#4545 style(sdk): turn on linting for internal_api.py
  .flake8-base
  mypy.ini
  wandb/sdk/internal/internal_api.py
Labels: cc-style

#4539 test(sdk): add many tests for InternalApi.upload_file
  tests/unit_tests/conftest.py
  tests/unit_tests/test_internal_api.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/progress.py
Labels: cc-test

#4565 chore(artifacts): Artifact Sequence Fallbacks
  wandb/apis/public.py
Labels: cc-chore

#4499 feat(sdk): Improvements to Report API in preparation for GA
  tests/unit_tests/test_kfp.py
  tests/unit_tests/test_report_api.py
  tests/unit_tests/test_require_helpers.py
  tests/unit_tests_old/test_report_api.py
  wandb/apis/public.py
  wandb/apis/reports/__init__.py
  wandb/apis/reports/_blocks.py
  wandb/apis/reports/_helpers.py
  wandb/apis/reports/_panels.py
  wandb/apis/reports/_templates.py
  wandb/apis/reports/block_gallery.py
  wandb/apis/reports/blocks.py
  wandb/apis/reports/helpers.py
  wandb/apis/reports/mutations.py
  wandb/apis/reports/panels.py
  wandb/apis/reports/report.py
  wandb/apis/reports/reports.py
  wandb/apis/reports/runset.py
  wandb/apis/reports/templates.py
  wandb/apis/reports/util.py
  wandb/apis/reports/validators.py
  wandb/sdk/wandb_require.py
  wandb/sdk/wandb_require_helpers.py
Labels: cc-feat

#4479 test(sdk): make protobuf version requirements more granular
  .circleci/config.yml
  requirements.txt
  tools/check-protobuf-version-compatibility.py
Labels: cc-test

#4571 fix(integrations): update gym integration to match last version
  wandb/integration/gym/__init__.py
Labels: cc-fix

#4439 fix(sdk): harden internal thread management in SystemMetrics
  wandb/sdk/internal/system/assets/interfaces.py
  wandb/sdk/internal/system/system_monitor.py
  wandb/sdk/lib/git.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#4573 test(sdk): update t2_fix_error_cond_feature_importances to install scikit-learn
  tests/functional_tests/t0_main/sklearn/t2_fix_error_cond_feature_importances.py
Labels: cc-test

#4566 chore(sdk): update base Docker images for nightly testing
  .circleci/config.yml
  tests/standalone_tests/mixed_keras.yea
  tests/standalone_tests/shards/gke_cpu/Dockerfile
  tests/standalone_tests/shards/gke_gpu/Dockerfile
Labels: cc-chore

#4581 chore(sdk): bump version to 0.13.7.dev1; update changelog
  CHANGELOG.md
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#4559 style(sdk): Use the same syntax whenever raising exceptions
  tests/unit_tests/test_wandb_summary.py
  wandb/apis/public.py
  wandb/docker/__init__.py
  wandb/sdk/data_types/saved_model.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/lib/preinit.py
  wandb/sdk/lib/sock_client.py
  wandb/sdk/wandb_artifacts.py
  wandb/vendor/pygments/filter.py
  wandb/vendor/watchdog_0_9_0/wandb_watchdog/observers/winapi.py
  wandb/vendor/watchdog_0_9_0/wandb_watchdog/utils/win32stat.py
Labels: cc-style

#4513 chore(launch): added error check for `--build` when resource=local-process
  tests/unit_tests/tests_launch/test_launch_cli.py
  wandb/sdk/launch/launch_add.py
Labels: cc-chore

#4572 fix(sdk): resume collecting system metrics on object restart
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/system/system_monitor.py
Labels: cc-fix

#4555 fix(launch): Fix env handling and node_selector handling
  tests/unit_tests_old/tests_launch/test_launch_kubernetes.py
  wandb/sdk/launch/runner/kubernetes.py
Labels: cc-fix

#4505 feat(artifacts): keep uncommitted uploads in separate staging area
  pyproject.toml
  requirements.txt
  tests/unit_tests/test_wandb_artifacts.py
  tests/unit_tests/test_wandb_artifacts_cache.py
  tests/unit_tests/test_wandb_artifacts_full.py
  wandb/env.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/internal/artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-feat

#4612 chore(launch): remove requirement to make target project match queue
  tests/unit_tests_old/tests_launch/test_launch.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#4602 chore(sdk): enhance nightly cloud testing process
  .circleci/config.yml
  tools/cloud-tool.py
Labels: cc-chore

#4632 build(sdk): temporarily pin jax in tests because of breaking changes
  requirements_dev.txt
Labels: cc-build

#4629 revert(artifacts): revert fix circular reference detected error when updating metadata with numpy len > 32
  tests/unit_tests/test_util.py
  tests/unit_tests/test_wandb_artifacts_full.py
  wandb/apis/public.py
  wandb/sdk/interface/interface.py
  wandb/sdk/wandb_artifacts.py
  wandb/util.py
Labels: cc-revert

#4633 chore(sdk): update pull request template
  .github/pull_request_template.md
Labels: cc-chore

#4516 chore(launch): Return updated runSpec after pushToRunQueue query
  tests/unit_tests/tests_launch/test_launch_add.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/launch_add.py
Labels: cc-chore

#4634 chore(sdk): bump sdk version to 0.13.8.dev1
  CHANGELOG.md
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#4636 chore(launch): fix for run spec handling in sdk
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/launch_add.py
Labels: cc-chore

#4627 chore(sweeps): typo in docs
  wandb/cli/cli.py
Labels: cc-chore

#4625 fix(public-api): Job uses queue_name keyword arg (instead of queue) when calling launch_add
  tests/unit_tests/tests_launch/test_job.py
  wandb/apis/public.py
Labels: cc-fix

#4640 fix(sweeps): sweeps schedulers handles multi word parameters
  wandb/cli/cli.py
Labels: cc-fix

#4656 chore(sdk): remove test dependency on old fastparquet package
  tox.ini
Labels: cc-chore

#4659 chore(sdk): Correct 'exclude'->'ignore-paths' in .pylintrc
  .pylintrc
Labels: cc-chore

#4647 fix(launch): Allow spaces in requirements file, remove duplicate wandb bootstrap file
  wandb/sdk/launch/builder/templates/_wandb_bootstrap.py
  wandb/sdk/launch/templates/_wandb_bootstrap.py
Labels: cc-fix

#4664 chore(sdk): use pytest tmp_path so we can inspect failures
  tests/unit_tests/conftest.py
Labels: cc-chore

#4626 chore(launch): reset build command after building, fixes: WB-11817
  tests/unit_tests/tests_launch/test_launch_sweep.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/wandb_run.py
Labels: cc-chore

#4430 ci(sdk): rerun flaking tests in CI with pytest-rerunfailures
  tox.ini
Labels: cc-ci

#4617 chore(sdk): improve file descriptor management
  tests/unit_tests_old/test_summary.py
  wandb/__init__.py
  wandb/apis/public.py
  wandb/data_types.py
  wandb/sdk/internal/internal.py
  wandb/util.py
Labels: cc-chore

#4638 chore(sdk): remove dead code from filesync logic
  wandb/filesync/step_upload.py
Labels: cc-chore

#4662 chore(sdk): remove unused fields from a filesync message
  wandb/filesync/step_checksum.py
  wandb/sdk/internal/file_pusher.py
Labels: cc-chore

#4588 chore(sdk): refactor retry logic to use globals instead of dependency-injecting them
  tests/unit_tests/test_retry.py
  wandb/sdk/lib/retry.py
Labels: cc-chore

#4650 refactor(sdk): combine _safe_mkdirs with mkdir_exist_ok
  tests/functional_tests/t0_main/login/t2_login_init.py
  tests/unit_tests/conftest.py
  tests/unit_tests/lib/test_filesystem.py
  tests/unit_tests/test_sender.py
  tests/unit_tests/test_wandb.py
  tests/unit_tests_old/conftest.py
  tests/unit_tests_old/test_public_api.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/data_types.py
  wandb/filesync/step_checksum.py
  wandb/jupyter.py
  wandb/old/core.py
  wandb/old/settings.py
  wandb/sdk/data_types/base_types/media.py
  wandb/sdk/data_types/html.py
  wandb/sdk/data_types/video.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/internal/system/system_info.py
  wandb/sdk/internal/tb_watcher.py
  wandb/sdk/lib/config_util.py
  wandb/sdk/lib/filesystem.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
  wandb/sync/sync.py
  wandb/util.py
Labels: cc-refactor

#4648 refactor(artifacts): use a pytest fixture for the artifact cache
  tests/unit_tests/artifacts/conftest.py
  tests/unit_tests/artifacts/test_wandb_artifacts.py
  tests/unit_tests/artifacts/test_wandb_artifacts_cache.py
  tests/unit_tests/artifacts/test_wandb_artifacts_full.py
Labels: cc-refactor

#4665 fix(artifacts): correctly handle url-encoded local file references.
  tests/unit_tests/artifacts/test_wandb_artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-fix

#4652 test(sdk): add unit tests for filesync.StepUpload
  tests/unit_tests/test_step_upload.py
Labels: cc-test

#4649 refactor(artifacts): use ArtifactEntry directly instead of subclassing
  tests/unit_tests/artifacts/test_wandb_artifacts.py
  tests/unit_tests/test_saved_model.py
  wandb/apis/public.py
  wandb/beta/workflows.py
  wandb/data_types.py
  wandb/filesync/step_checksum.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/internal/artifacts.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_run.py
Labels: cc-refactor

#4639 test(sdk): add tests for Api.upload_file_retry
  tests/unit_tests/test_internal_api.py
Labels: cc-test

#4637 chore(launch): remove fallback resource when not specified for a queue
  tests/unit_tests_old/tests_launch/test_launch.py
  tests/unit_tests_old/tests_launch/test_launch_cli.py
  tests/unit_tests_old/tests_launch/test_launch_jobs.py
  wandb/cli/cli.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/launch/runner/loader.py
Labels: cc-chore

#4613 feat(launch): Default to using model-registry project for agent and launch_add
  tests/unit_tests/test_sweep_scheduler.py
  tests/unit_tests/tests_launch/test_job.py
  tests/unit_tests/tests_launch/test_launch_add.py
  tests/unit_tests/tests_launch/test_launch_cli.py
  tests/unit_tests_old/tests_launch/test_launch.py
  tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/deploys/aws-ec2/launch-config.yaml
  wandb/sdk/launch/deploys/aws-eks/launch-config.yaml
  wandb/sdk/launch/deploys/kubernetes/launch-config.yaml
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/launch/runner/local_process.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#4681 fix(artifacts): get digest directly instead of from the manifests' manifest
  wandb/data_types.py
Labels: cc-fix

#4674 test(artifacts): improve storage handler test coverage
  tests/unit_tests/artifacts/test_wandb_artifacts.py
  tests/unit_tests/artifacts/test_wandb_artifacts_cache.py
Labels: cc-test

#4525 refactor(artifacts): consolidate hash utilities into lib.hashutil
  .gitignore
  requirements_dev.txt
  tests/unit_tests/artifacts/test_wandb_artifacts.py
  tests/unit_tests/test_lib_hashutil.py
  tests/unit_tests_old/test_wandb_artifacts.py
  wandb/apis/public.py
  wandb/filesync/step_checksum.py
  wandb/sdk/data_types/saved_model.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/internal/artifacts.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/lib/hashutil.py
  wandb/sdk/wandb_artifacts.py
  wandb/util.py
Labels: cc-refactor

#4690 test(integrations): fix import tests
  tests/functional_tests/t0_main/imports/03-batch3-requirements.txt
  tests/functional_tests/t0_main/imports/03-batch3.py
  tests/functional_tests/t0_main/imports/04-batch4-requirements.txt
  tests/functional_tests/t0_main/imports/04-batch4.py
Labels: cc-test

#4543 docs(sdk): Fixed typo in docstring for data_types.Objects3D
  wandb/sdk/data_types/object_3d.py
Labels: cc-docs

#4687 docs(sdk): Removed less than, greater than characters from dosctrings…
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/sdk/interface/artifacts.py
Labels: cc-docs

#4486 fix(artifacts): artifact.version should be the version index from the associated collection
  tests/unit_tests/test_public_api.py
  wandb/apis/public.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-fix

#4564 feat(sdk): add `exist_ok=False` to `file.download()`
  wandb/apis/public.py
Labels: contrib, cc-feat

#4697 style(public-api): format public file with proper formating
  wandb/apis/public.py
Labels: cc-style
