Repository wandb/wandb, pull requests merged in 2022-10, with the labels that each got.

#4356 chore(sdk): use the gear emoji to denote Dev changes in the changelog/release notes
  .github/release.yml
Labels: changelog-ignore, cc-chore

#4357 chore(sdk): add changelog for 0.13.4 release
  CHANGELOG.md
Labels: changelog-ignore, cc-chore

#4303 feat(artifacts): Add option to upload image references
  tests/unit_tests/test_data_types.py
  wandb/data_types.py
  wandb/sdk/data_types/base_types/media.py
  wandb/sdk/data_types/image.py
Labels: cc-feat

#4361 ci(sdk): make sure we dont shutdown test cluster before grabbing results
  .circleci/config.yml
Labels: cc-ci

#4360 test(artifacts): add standalone artifact test to nightly cpu suite
  tests/standalone_tests/artifact_tests.yea
Labels: cc-test

#4354 style(sdk): ignore new proto generated file directories
  .gitattributes
Labels: cc-style

#4374 chore(sdk): rename default branch to `main`
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  package_readme.md
  wandb/integration/prodigy/prodigy.py
Labels: cc-chore

#4379 fix(launch): generate more readable image names
  tests/unit_tests/test_util.py
  tests/unit_tests_old/tests_launch/test_launch_docker.py
  wandb/util.py
Labels: cc-fix

#4371 fix(artifacts): in artifacts cache, use hash(etag+url) as key, not just etag
  tests/unit_tests/test_wandb_artifacts.py
  tests/unit_tests/test_wandb_artifacts_cache.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-fix

#4381 fix(artifacts): in `wandb artifact put`, wait for artifact to commit before telling the user it's ready
  tests/unit_tests_old/test_cli.py
  wandb/cli/cli.py
Labels: cc-fix

#4221 fix(artifacts): Circular reference detected error when updating metadata with numpy array longer than 32 elements
  tests/unit_tests/test_util.py
  tests/unit_tests/test_wandb_artifacts_full.py
  wandb/apis/public.py
  wandb/proto/v4/wandb_base_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_server_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/sdk/interface/interface.py
  wandb/sdk/wandb_artifacts.py
  wandb/util.py
Labels: cc-fix

#4392 build(sdk): update mypy extension for protobuf type checking
  tox.ini
Labels: cc-build

#4370 feat(sweeps): Sweep now has an expected_run_count property
  tests/unit_tests/test_public_api.py
  tests/unit_tests/test_wandb_sweep.py
  wandb/apis/public.py
Labels: cc-feat

#4213 refactor(sdk): System Metrics probing/monitoring architecture refactor
  src/apple_gpu_stats/README.md
  tests/unit_tests/conftest.py
  tests/unit_tests/test_system_info.py
  tests/unit_tests/test_system_metrics_gpu.py
  tests/unit_tests/test_system_metrics_gpu_apple.py
  tests/unit_tests/test_system_metrics_ipu.py
  tests/unit_tests/test_system_metrics_tpu.py
  tests/unit_tests/test_system_monitor.py
  tests/unit_tests/test_tpu.py
  tests/unit_tests/test_util.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/ipu.py
  wandb/sdk/internal/meta.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/internal/stats.py
  wandb/sdk/internal/system/__init__.py
  wandb/sdk/internal/system/assets/__init__.py
  wandb/sdk/internal/system/assets/aggregators.py
  wandb/sdk/internal/system/assets/asset_registry.py
  wandb/sdk/internal/system/assets/cpu.py
  wandb/sdk/internal/system/assets/disk.py
  wandb/sdk/internal/system/assets/gpu.py
  wandb/sdk/internal/system/assets/gpu_apple.py
  wandb/sdk/internal/system/assets/interfaces.py
  wandb/sdk/internal/system/assets/ipu.py
  wandb/sdk/internal/system/assets/memory.py
  wandb/sdk/internal/system/assets/network.py
  wandb/sdk/internal/system/assets/tpu.py
  wandb/sdk/internal/system/system_info.py
  wandb/sdk/internal/system/system_monitor.py
  wandb/sdk/internal/tpu.py
  wandb/sdk/wandb_settings.py
  wandb/util.py
Labels: cc-refactor

#4395 ci(sdk): move functional import tests to nightly and expand python version coverage
  .circleci/config.yml
  tools/circleci-tool.py
Labels: cc-ci

#4400 style(sdk): fix gitattribute for protobuf generated files
  .gitattributes
Labels: cc-style

#4403 ci(sdk): add Slack notification for failed nightly import tests
  .circleci/config.yml
Labels: cc-ci
