Repository wandb/wandb, pull requests merged in 2022-07, with the labels that each got.

#3901 Add blame ignore
  .git-blame-ignore-revs
Labels: changelog-ignore

#3939 bumps master version to 0.13.0rc6dev1
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: changelog-ignore

#3938 fix up the `bumpversion` config
  setup.cfg
Labels: changelog-ignore

#3951 Pin pyupgrade version
  .circleci/config.yml
  tox.ini
Labels: changelog-ignore

#4015 Update yea-wandb 0.8.2
  tests/utils/mock_server.py
  tox.ini
Labels: changelog-ignore

#3793 Renames `wandb local` to `wandb server`
  tests/unit_tests/wandb_run_test.py
  wandb/cli/cli.py
  wandb/sdk/internal/sender.py
  wandb/sdk/lib/_wburls_generated.py
  wandb/sdk/lib/wburls.py
  wandb/sdk/wandb_run.py
Labels: changelog-cleanup

#4018 Fix flaky tests (notebook, keras, perf oh my)
  tests/assets/notebooks/magic.ipynb
  tests/assets/notebooks/one_cell.ipynb
  tests/functional_tests/t0_main/keras/test_keras_subclassed_model.py
  tests/functional_tests/t0_main/perf/t1_basic.py
  tests/functional_tests/t0_main/perf/t1_basic.yea
  tests/unit_tests/tests_s_nb/test_notebooks.py
Labels: changelog-ignore

#4019 Fix flake in keras subclass test (workaround)
  tests/functional_tests/t0_main/keras/keras_subclassed_test_tf_2_6.yea
Labels: changelog-ignore

#3988 Adds import hook for run telemetry
  tests/functional_tests/t0_main/mp/01-2-simple-no-finish.yea
  tests/unit_tests/test_telemetry_full.py
  wandb/proto/wandb_telemetry.proto
  wandb/proto/wandb_telemetry_pb2.py
  wandb/proto/wandb_telemetry_pb2.pyi
  wandb/sdk/internal/sender.py
  wandb/sdk/lib/import_hooks.py
  wandb/sdk/lib/telemetry.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_manager.py
  wandb/sdk/wandb_run.py
Labels: changelog-enhancement

#4020 Fix mockserver workers to have unique port numbers
  tests/conftest.py
  tests/utils/mock_server.py
  tox.ini
Labels: changelog-ignore
