Repository wandb/wandb, pull requests merged in 2022-06, with the labels that each got.

#3750 add new mutations and query to internal api
  wandb/sdk/internal/internal_api.py
Labels: t:branch, b:summerhack

#3769 summerhack launch: Fix agent code to properly handle received queue configs
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/launch.py
Labels: b:summerhack

#3778 resource aware agents working
  wandb/sdk/launch/agent/agent.py
Labels: b:summerhack

#3781 fix agent project and stuff
  wandb/sdk/launch/agent/agent.py
Labels: b:summerhack

#3771 chore(local): Updating /client README for with new wandb server start…
  README.md
Labels: changelog-ignore

#3870 revert service on by default and update version
  setup.cfg
  setup.py
  tests/conftest.py
  wandb/__init__.py
Labels: changelog-ignore
