Repository wandb/wandb, pull requests merged in 2022-11, with the labels that each got.

#4426 test(cli): fix broken CLI tests that attempt uploading non-existent artifacts
  tests/unit_tests/assets/wandb/offline-run-20210216_154407-g9dvvkua/files/code/standalone_tests/code-toad.py
  tests/unit_tests/assets/wandb/offline-run-20210216_154407-g9dvvkua/files/config.yaml
  tests/unit_tests/assets/wandb/offline-run-20210216_154407-g9dvvkua/files/diff.patch
  tests/unit_tests/assets/wandb/offline-run-20210216_154407-g9dvvkua/files/output.log
  tests/unit_tests/assets/wandb/offline-run-20210216_154407-g9dvvkua/files/requirements.txt
  tests/unit_tests/assets/wandb/offline-run-20210216_154407-g9dvvkua/files/upstream_diff_78c43d0cc7146adb88cef2fcca4ec244a2d6a162.patch
  tests/unit_tests/assets/wandb/offline-run-20210216_154407-g9dvvkua/files/wandb-metadata.json
  tests/unit_tests/assets/wandb/offline-run-20210216_154407-g9dvvkua/files/wandb-summary.json
  tests/unit_tests/test_cli_full.py
Labels: cc-test

#4276 fix(integrations): add a random string to run_id on SageMaker not to break DDP mode
  tests/unit_tests/conftest.py
  tests/unit_tests/test_wandb.py
  tests/unit_tests_old/test_wandb.py
  wandb/integration/sagemaker/resources.py
Labels: cc-fix

#4433 revert(sweeps): add `expected_run_count` property to Sweep's public api
  tests/unit_tests/test_public_api.py
  tests/unit_tests/test_wandb_sweep.py
  wandb/apis/public.py
Labels: cc-revert

#4436 build(sdk): bump SDK version to latest dev version
  CHANGELOG.md
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-build

#4401 fix(artifacts): have default artifactVersions only retrieve committed artifacts
  wandb/apis/public.py
Labels: cc-fix

#4438 fix(cli): Deflake wandb verify
  wandb/sdk/verify/verify.py
Labels: cc-fix

#4416 fix(launch): Fix LaunchProject override_arg format when setb from Job
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.py
  wandb/apis/public.py
Labels: cc-fix

#4459 chore(launch): improved git fetch time by specifying a `refspec` and `depth=1`
  wandb/sdk/launch/utils.py
Labels: cc-chore

#4470 chore(sdk): fix linguist rule to ignore grpc generated files
  .gitattributes
Labels: cc-chore

#4450 fix(launch): remove extra colon from log prefix
  wandb/sdk/launch/utils.py
Labels: cc-fix

#4429 refactor(artifacts): Re-add programmatic alias addition/removal from SDK on artifacts
  tests/unit_tests/test_public_api.py
  wandb/apis/public.py
Labels: cc-refactor

#4440 fix(sdk): add support for service running in a pex based environment
  .circleci/config.yml
  wandb/sdk/internal/settings_static.py
  wandb/sdk/service/service.py
  wandb/sdk/wandb_manager.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#4434 feat(sweeps): Adds Sweep.expected_run_count to public Api
  tests/unit_tests/test_public_api.py
  tests/unit_tests/test_wandb_artifacts_full.py
  tests/unit_tests/test_wandb_sweep.py
  wandb/apis/public.py
Labels: cc-feat

#4427 chore(launch): new shard for launch tests
  .circleci/config.yml
  .codecov.yml
  pytest.ini
  tox.ini
Labels: cc-chore

#4475 feat(launch): Support volume mounts and security contexts in kubernetes runner
  tests/unit_tests_old/tests_launch/test_launch_kubernetes.py
  wandb/sdk/launch/runner/kubernetes.py
Labels: cc-feat

#4497 refactor(launch): remove unused attribute
  wandb/sdk/launch/_project_spec.py
Labels: cc-refactor

#4495 docs(sdk): Remove non-existent argument table_key from plot_table() doc string
  wandb/sdk/wandb_run.py
  wandb/viz.py
Labels: cc-docs

#4508 fix(sdk): pin tensorflow<2.11.0 to prevent errors caused by API changes
  requirements_dev.txt
Labels: cc-fix

#4506 chore(public-api): Upgrade Node 12 based GitHub Actions
  .github/workflows/check-mocks-synced-with-yea-wandb.yml
  .github/workflows/pr.yml
Labels: cc-chore

#4463 test(artifacts): skip flaky test :(
  tests/unit_tests/test_wandb_artifacts_full.py
Labels: cc-test

#4523 test(artifacts): flush writes instead of sleeping to wait on file writes
  tests/unit_tests/test_wandb_artifacts_cache.py
Labels: cc-test

#4521 test(artifacts): Use `tmp_path` fixture instead of writing local files during tests
  tests/unit_tests/test_wandb_artifacts_cache.py
Labels: cc-test

#4528 docs(artifacts): correct parameter name in docstring example
  wandb/sdk/interface/artifacts.py
Labels: cc-docs

#4548 chore(launch): Fix broken queue test
  tests/unit_tests/tests_launch/test_launch_add.py
Labels: cc-chore

#4531 fix(public-api): Changed `artifactSequence` to `artifactCollection` in public GQL requests
  tests/functional_tests/t0_main/artifacts/public_collections.py
  tests/unit_tests_old/utils/mock_server.py
  tox.ini
  wandb/apis/public.py
Labels: cc-fix

#4498 refactor(launch): Add more robust uri parsing
  tests/unit_tests/tests_launch/test_github_reference.py
  tests/unit_tests/tests_launch/test_wandb_reference.py
  wandb/sdk/launch/github_reference.py
  wandb/sdk/launch/utils.py
  wandb/sdk/launch/wandb_reference.py
Labels: cc-refactor

#4550 test(artifacts): skip mysteriously flaky test
  tests/unit_tests/test_wandb_artifacts_full.py
Labels: cc-test

#4391 feat(integrations): add ability to log learning rate using WandbMetricsLogger
  tests/functional_tests/t0_main/keras/keras_metrics_logger_epochwise_tf_2_6.yea
  tests/functional_tests/t0_main/keras/keras_metrics_logger_tf_2.6.yea
  tests/functional_tests/t0_main/keras/test_keras_metrics_logger_epochwise.py
  wandb/integration/keras/callbacks/metrics_logger.py
Labels: cc-feat

#4432 fix(integrations): TF compatibility issues with WandbModelCheckpoint
  .circleci/config.yml
  .codecov.yml
  .coveragerc
  tests/functional_tests/t0_main/keras/keras_model_checkpoint_tf_2_4.yea
  tests/functional_tests/t0_main/keras/test_keras_model_checkpoint.py
  tox.ini
  wandb/integration/keras/callbacks/model_checkpoint.py
Labels: cc-fix

#4533 fix(integrations): make Keras WandbCallback compatible with TF version >= 2.11.0
  requirements_dev.txt
  wandb/integration/keras/keras.py
Labels: cc-fix
