Repository wandb/wandb, pull requests merged in 2022-05, with the labels that each got.

#3602 Add cleanup section to GH changelog
  .github/pull_request_template.md
  .github/release.yml
Labels: changelog-ignore

#3604 Bump version: 0.12.16.dev1 → 0.12.16
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: changelog-ignore

#3605 Bump version: 0.12.16 → 0.12.17.dev1
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: changelog-ignore

#3607 Rename wandb/sdk to wandb/sdk-team
  .github/CODEOWNERS
Labels: changelog-ignore

#3615 Adds verbosity to the tox.ini pytest
  tox.ini
Labels: changelog-ignore

#3619 Modify test to work by default with service
  tests/test_library_public.py
  tests/test_mode_disabled.py
Labels: changelog-ignore

#3623 [WB-9385] Adds support for magic with service
  wandb/sdk/wandb_manager.py
  wandb/trigger.py
Labels: changelog-enhancement

#3614 [WB-9396] Adds timing settings for live policy upload
  tests/wandb_integration_test.py
  wandb/filesync/dir_watcher.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/wandb_settings.py
Labels: changelog-ignore

#3648 skip if service is on
  tests/test_mp_full.py
  tests/wandb_run_test.py
  tests/wandb_test.py
Labels: changelog-ignore

#3621 [WB-7112] un-flake the runtime test
  tests/test_runtime.py
Labels: changelog-ignore

#3650 [WB-9214] Add support in artifacts for files with unicode on windows
  functional_tests/artifacts/log-unicode-artifact.py
  functional_tests/artifacts/log-unicode-artifact.yea
  tests/wandb_artifacts_test.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/wandb_artifacts.py
  wandb/util.py
Labels: changelog-enhancement

#3668 add prekind part and pre counter <- allow skip kindversions from cmdline
  setup.cfg
  tools/bumpversion-tool.py
  tox.ini
Labels: changelog-ignore

#3653 [WB-9113] Revert change to the warning message of outdated local version
  wandb/cli/cli.py
Labels: changelog-cleanup
