Repository wandb/wandb, pull requests merged in 2023-06, with the labels that each got.

#5647 chore(sweeps): set sweep state on scheduler exit
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#5296 fix(sdk): unify offline and online mode during init and fix multiprocess attach
  tests/functional_tests/t0_main/offline/t2_multiprocess.py
  tests/pytest_tests/system_tests/test_core/test_system_info.py
  wandb/sdk/interface/interface.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/sender.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#5535 refactor(integrations): adjust autolog monkey patch code for better generalization and for more loggable media and metrics from integrations
  tests/pytest_tests/unit_tests/test_autolog_patch_integration.py
  wandb/integration/cohere/cohere.py
  wandb/integration/cohere/resolver.py
  wandb/integration/openai/openai.py
  wandb/integration/openai/resolver.py
  wandb/sdk/integration_utils/auto_logging.py
Labels: cc-refactor

#5649 fix(integrations): prevent errors by checking for `wandb.run` in Gym integration
  wandb/integration/gym/__init__.py
Labels: cc-fix

#5261 fix(sdk): fix wandb tfevent sync issue
  wandb/sdk/internal/tb_watcher.py
Labels: contrib, cc-fix

#5579 feat(integrations): Add autologging for calls to supported HuggingFace Pipelines
  .circleci/config.yml
  tests/functional_tests/t0_main/hf_pipelines/t1_text_classification.py
  tests/functional_tests/t0_main/hf_pipelines/t1_text_classification.yea
  tests/functional_tests/t0_main/hf_pipelines/t2_question_answering.py
  tests/functional_tests/t0_main/hf_pipelines/t2_question_answering.yea
  tests/functional_tests/t0_main/hf_pipelines/t3_summarization.py
  tests/functional_tests/t0_main/hf_pipelines/t3_summarization.yea
  tests/functional_tests/t0_main/hf_pipelines/t4_translation.py
  tests/functional_tests/t0_main/hf_pipelines/t4_translation.yea
  tests/functional_tests/t0_main/hf_pipelines/t5_text2text_generation.py
  tests/functional_tests/t0_main/hf_pipelines/t5_text2text_generation.yea
  tests/functional_tests/t0_main/hf_pipelines/t6_text_generation.py
  tests/functional_tests/t0_main/hf_pipelines/t6_text_generation.yea
  tests/functional_tests/t0_main/hf_pipelines/t7_conversational.py
  tests/functional_tests/t0_main/hf_pipelines/t7_conversational.yea
  tests/functional_tests/t0_main/hf_pipelines/t8_custom_table_name_and_latest_id.py
  tests/functional_tests/t0_main/hf_pipelines/t8_custom_table_name_and_latest_id.yea
  tox.ini
  wandb/integration/huggingface/__init__.py
  wandb/integration/huggingface/huggingface.py
  wandb/integration/huggingface/resolver.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
Labels: cc-feat

#5521 feat(integrations): add usage metrics and table logging to OpenAI autologger
  tests/functional_tests/t0_main/llm/t1_llm_jerome_battle.py
  tests/functional_tests/t0_main/llm/t1_llm_jerome_battle.yea
  tests/functional_tests/t0_main/openai/t1_openai_edit.py
  tests/functional_tests/t0_main/openai/t1_openai_edit.yea
  tests/functional_tests/t0_main/openai/t2_openai_completion.py
  tests/functional_tests/t0_main/openai/t2_openai_completion.yea
  tests/functional_tests/t0_main/openai/t2_openai_edit.yea
  tests/functional_tests/t0_main/openai/t3_openai_chat_completion.py
  tests/functional_tests/t0_main/openai/t3_openai_chat_completion.yea
  tests/functional_tests/t0_main/openai/t3_openai_completion.yea
  tests/functional_tests/t0_main/openai/t4_openai_chat_completion.yea
  tests/functional_tests/t0_main/openai/t4_openai_edit_weird_autolog_api_usage.py
  tests/functional_tests/t0_main/openai/t4_openai_edit_weird_autolog_api_usage.yea
  tests/functional_tests/t0_main/openai/t5_openai_edit_weird_autolog_api_usage_2.py
  tests/functional_tests/t0_main/openai/t5_openai_edit_weird_autolog_api_usage_2.yea
  tools/pr-title-bot.py
  tox.ini
  wandb/integration/cohere/resolver.py
  wandb/integration/openai/resolver.py
Labels: cc-feat

#5449 feat(sdk): add support for monitoring AMD GPU system metrics
  tests/pytest_tests/unit_tests/test_system_metrics/test_gpu_amd.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_system_monitor.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/internal/system/assets/__init__.py
  wandb/sdk/internal/system/assets/gpu_amd.py
Labels: cc-feat

#5643 feat(sdk): capture absolute GPU memory allocation
  setup.py
  wandb/sdk/data_types/utils.py
  wandb/sdk/internal/system/assets/gpu.py
  wandb/sdk/lib/sock_client.py
  wandb/sdk/service/server_sock.py
Labels: cc-feat

#5655 chore(sdk): update retry message format
  .github/pull_request_template.md
  wandb/sdk/internal/file_stream.py
Labels: cc-chore

#5656 ci(sdk): use exponential backoff for OpenAI API calls in pr-title-bot.py
  .github/workflows/fix-pr-title.yml
  tools/pr-title-bot.py
Labels: cc-ci

#5660 ci(sdk): fix the OpenAI API call used in pr-title-bot.py
  tools/pr-title-bot.py
Labels: cc-ci

#5664 chore(sdk): Bump version: 0.15.4.dev1 → 0.15.5.dev1
  pyproject.toml
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5667 fix(sdk): address numpy-related mypy errors
  wandb/integration/tensorboard/log.py
  wandb/sdk/data_types/base_types/media.py
  wandb/sdk/data_types/histogram.py
  wandb/sdk/data_types/image.py
  wandb/sdk/data_types/object_3d.py
  wandb/sdk/data_types/video.py
Labels: cc-test

#5666 chore(sweeps): correct typo in method assignment
  wandb/cli/cli.py
Labels: cc-chore

#5669 build(sdk): fix editable mode
  pyproject.toml
Labels: cc-build

#5670 fix(sdk): handle uri schemes in LogicalPath
  tests/pytest_tests/unit_tests/test_lib/test_paths.py
  wandb/sdk/lib/paths.py
Labels: cc-fix

#5672 test(integrations): remove import tests
  .circleci/config.yml
  tests/functional_tests/t0_main/imports/01-batch1-requirements.txt
  tests/functional_tests/t0_main/imports/01-batch1.py
  tests/functional_tests/t0_main/imports/02-batch2-requirements.txt
  tests/functional_tests/t0_main/imports/02-batch2.py
  tests/functional_tests/t0_main/imports/03-batch3-requirements.txt
  tests/functional_tests/t0_main/imports/03-batch3.py
  tests/functional_tests/t0_main/imports/04-batch4-requirements.txt
  tests/functional_tests/t0_main/imports/04-batch4.py
  tests/functional_tests/t0_main/imports/05-batch5-requirements.txt
  tests/functional_tests/t0_main/imports/05-batch5.py
  tests/functional_tests/t0_main/imports/06-batch6-requirements.txt
  tests/functional_tests/t0_main/imports/06-batch6.py
  tests/functional_tests/t0_main/imports/07-batch7-requirements.txt
  tests/functional_tests/t0_main/imports/07-batch7.py
  tests/functional_tests/t0_main/imports/08-batch8-requirements.txt
  tests/functional_tests/t0_main/imports/08-batch8.py
  tests/functional_tests/t0_main/imports/09-batch9-requirements.txt
  tests/functional_tests/t0_main/imports/09-batch9.py
  tests/functional_tests/t0_main/imports/10-batch10-requirements.txt
  tests/functional_tests/t0_main/imports/10-batch10.py
  tests/functional_tests/t0_main/imports/11-batch11-requirements.txt
  tests/functional_tests/t0_main/imports/11-batch11.py
  tests/functional_tests/t0_main/imports/12-batch12-requirements.txt
  tests/functional_tests/t0_main/imports/12-batch12.py
  tools/circleci-tool.py
Labels: cc-test

#5673 fix(sdk): update logical path handling in tb watcher for s3
  wandb/sdk/internal/tb_watcher.py
Labels: cc-chore

#5675 revert(sdk): handle uri schemes in LogicalPath
  tests/pytest_tests/unit_tests/test_lib/test_paths.py
  wandb/sdk/lib/paths.py
Labels: cc-revert

#5676 build(sdk): fix typos in Makefile and update orbs in .circleci/config.yml
  .circleci/config.yml
  Makefile
Labels: cc-build

#5677 chore(sdk): Pin KFPv1 dependencies in yea
  tests/functional_tests/t0_main/kfp/kfp-pipeline-helper.yea
  tests/functional_tests/t0_main/kfp/kfp-pipeline-pytorch.yea
  tests/functional_tests/t0_main/kfp/kfp-pipeline-simple.yea
  tests/functional_tests/t0_main/kfp/kfp-pipeline-sklearn.yea
Labels: cc-chore

#5685 ci(sdk): enforce compliance with conventional commit recommendations for PR titles
  .github/workflows/fix-pr-title.yml
  .github/workflows/pr.yml
  tools/pr-title-bot.py
Labels: cc-ci

#5693 feat(sdk): add nexus experiment
  wandb/analytics/sentry.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/service/service.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_require.py
  wandb/sdk/wandb_settings.py
Labels: changelog-ignore, cc-feat

#5715 test(sdk): improve relay server robustness wrt missing features in service implementation
  tests/pytest_tests/system_tests/conftest.py
  wandb/testing/relay.py
Labels: cc-test

#5722 fix(artifacts): store a reference when storing memory address
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#5707 refactor(integrations): deprecate and proxy the langchain integration
  tests/functional_tests/t0_main/langchain/t1_v1.yea
  tests/functional_tests/t0_main/langchain/t2_v1.yea
  wandb/integration/langchain/util.py
  wandb/integration/langchain/wandb_tracer.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_deprecated.py
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/wandb_settings.py
Labels: cc-refactor

#5738 feat(sweeps): new version of click enables nicer cli printing
  requirements.txt
Labels: cc-feat

#5739 chore(sdk): Mark SSL tests skip for python37
  tests/pytest_tests/unit_tests/test_ssl.py
Labels: cc-chore

#5718 feat(launch): better docker image job name handling, tag -> alias
  tests/functional_tests/t0_main/jobs/job_container_creation.yea
  tests/pytest_tests/unit_tests_old/test_wandb_run.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
Labels: cc-feat

#5706 feat(launch): support kaniko builds on AKS
  requirements_dev.txt
  setup.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_kaniko.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_azure.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_acr.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/environment/azure_environment.py
  wandb/sdk/launch/loader.py
  wandb/sdk/launch/registry/azure_container_registry.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-feat

#5719 chore(launch): allow customization of kaniko image from config
  wandb/sdk/launch/builder/kaniko_builder.py
Labels: cc-chore

#5644 fix(launch): only set WANDB_RUN_ID in master of volcano jobs
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#5637 feat(launch): allow kaniko builds to run in other namespaces
  wandb/sdk/launch/builder/kaniko_builder.py
Labels: cc-feat

#5691 chore(sdk): improve JSONification of dataclasses
  tests/pytest_tests/unit_tests/test_util.py
  wandb/util.py
Labels: cc-chore

#5727 fix(sdk): improve lazy import to be thread-safe
  wandb/util.py
Labels: cc-fix

#5758 test(sdk): fix broken tests
  .circleci/config.yml
  .codecov.yml
  .coveragerc
  tests/functional_tests/t0_main/artifacts/link-artifact.yea
  tests/functional_tests/t0_main/artifacts/link-model-outside-run.yea
  tests/functional_tests/t0_main/artifacts/link-model.yea
  tests/functional_tests/t0_main/artifacts/log-artifact.yea
  tests/functional_tests/t0_main/artifacts/log-image-artifact-path.yea
  tests/functional_tests/t0_main/artifacts/log-model.yea
  tests/functional_tests/t0_main/artifacts/log-unicode-artifact.yea
  tests/functional_tests/t0_main/artifacts/public-link-model.yea
  tests/functional_tests/t0_main/artifacts/use-and-link-model.yea
  tests/functional_tests/t0_main/artifacts/use-model-error.yea
  tests/functional_tests/t0_main/artifacts/use-model-outside-run-error.yea
  tests/functional_tests/t0_main/artifacts/use-model.yea
  tests/functional_tests/t0_main/raytune/t5_colab.yea
  tests/functional_tests/t0_main/tensorflow/t1_tensorflow_log.yea
  tox.ini
Labels: cc-test

#5743 fix(launch): change typo in kaniko image name
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  wandb/sdk/launch/builder/kaniko_builder.py
Labels: cc-fix

#5759 fix(integrations): date was parsed as int/float in SageMaker config
  tests/pytest_tests/unit_tests/test_sagemaker_config_parse.py
  wandb/integration/sagemaker/config.py
Labels: cc-fix

#5736 fix(launch): Make docker build non interactive to prevent region based questions
  wandb/sdk/launch/builder/build.py
Labels: cc-fix

#5737 fix(launch): Update "cuda" base image path to "accelerator" base image path
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_docker.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/build.py
Labels: cc-fix

#5732 chore(sweeps): crashed runs with no metrics dont count against run_cap
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#5701 docs(artifacts): update docs
  wandb/sdk/artifacts/artifact.py
Labels: cc-docs

#5724 fix(artifacts): don't validate name of existing artifacts
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#5757 docs(sdk): remove pydoc-markdown config
  pydoc-markdown.yml
Labels: cc-docs

#5729 feat(artifacts): support access key for Azure references
  wandb/sdk/artifacts/storage_handlers/azure_handler.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#5612 feat(launch): Add information to failed run queue items, support warnings for run queue items
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_run_queue_item_saver.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_aws.py
  wandb/apis/internal.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/agent/job_status_tracker.py
  wandb/sdk/launch/agent/run_queue_item_file_saver.py
  wandb/sdk/launch/builder/abstract.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/builder/noop.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/runner/abstract.py
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/runner/sagemaker_runner.py
  wandb/sdk/launch/runner/vertex_runner.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#5751 docs(artifacts): fix comment about total retry time
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
Labels: cc-docs

#5760 feat(launch): allow direct configuration of registry uri for all registries
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_ecr.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_gcp_artifact_registry.py
  wandb/sdk/launch/environment/aws_environment.py
  wandb/sdk/launch/registry/elastic_container_registry.py
  wandb/sdk/launch/registry/google_artifact_registry.py
Labels: cc-feat

#5761 chore(sweeps): better launch sweeps scheduler stopping (from ui)
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#5771 chore(sweeps): typo name --> id (test suite these are the same)
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#5692 perf(artifacts): get download URLs in batches
  tests/pytest_tests/unit_tests_old/utils/mock_server.py
  tox.ini
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
Labels: cc-perf

#5772 chore(sdk): update nexus experiment to use wandb-core package
  wandb/sdk/service/service.py
Labels: changelog-ignore, cc-chore

#5773 chore(sweeps): tests move name -> id
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
Labels: cc-chore

#5689 refactor(launch): Better support git URIs
  tests/pytest_tests/system_tests/test_launch/test_github_reference.py
  wandb/sdk/launch/github_reference.py
Labels: cc-refactor

#5774 fix(launch): Fix jobs with lots of output from hanging on local-container
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/runner/abstract.py
  wandb/sdk/launch/runner/local_container.py
Labels: cc-fix

#5776 chore(sdk): unpin setuptools
  CONTRIBUTING.md
  pyproject.toml
Labels: cc-chore

#5775 feat(sweeps): sweep scheduler handle program macro
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-feat

#5768 chore(sweeps): pass through previous scheduler args
  wandb/cli/cli.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-chore

#5788 docs(sdk): expose WBTraceTree as data_types.WBTraceTree
  wandb/data_types.py
  wandb/sdk/data_types/trace_tree.py
Labels: cc-docs

#5790 refactor(artifacts): change artifact methods and attributes to private
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  tests/pytest_tests/unit_tests/test_saved_model.py
  tests/pytest_tests/unit_tests/tests_launch/test_job.py
  wandb/apis/public.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
  wandb/sdk/artifacts/storage_handlers/wb_artifact_handler.py
  wandb/sdk/wandb_run.py
Labels: cc-docs

#5798 ci(sdk): fix pr title compliance with conventional commit style
  tools/pr-title-bot.py
Labels: cc-ci

#5778 feat(artifacts): add flag to skip missing S3 references in `Artifact.download`
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
Labels: cc-feat

#5770 feat(launch): Requeue job when pod goes down
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/agent/job_status_tracker.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/runner/abstract.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-feat

#5805 feat(sdk): add setting to disable setproctitle
  wandb/sdk/internal/settings_static.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/service/server.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#5807 fix(launch): Ensure resume does not push sensitive info
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/utils.py
Labels: cc-fix

#5808 fix(artifacts): fix handling of references when downloading
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#5806 fix(sweeps): correct launch sweep author to personal username
  wandb/cli/cli.py
  wandb/sdk/internal/internal_api.py
Labels: cc-fix

#5804 test(integrations): langchain - add required bs4 import and fix depre…
  tests/functional_tests/t0_main/langchain/t1_v1.yea
  tests/functional_tests/t0_main/langchain/t2_v1.yea
  wandb/integration/langchain/wandb_tracer.py
Labels: cc-test

#5815 chore(sdk): post release update
  CHANGELOG.md
  pyproject.toml
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5802 chore(launch): respect project kwarg if no project given by user
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/utils.py
  wandb/sdk/wandb_settings.py
Labels: cc-chore

#5814 fix(sdk): only creating new project if it doesn't already exist
  wandb/apis/reports/report.py
Labels: cc-fix

#5787 chore(launch): launch agent doesnt run jobs from stopped sweep
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#5823 chore(sweeps): paused is not a terminal state
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore
