Repository wandb/wandb, pull requests merged in 2023-05, with the labels that each got.

#5430 chore(launch): sweep scheduler uses better arg passing
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_sweep_cli.py
  wandb/cli/cli.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-chore

#5457 test(sdk): fix mixed_keras test on nightly/gpu
  tests/standalone_tests/mixed_keras.py
  tests/standalone_tests/shards/gke_cpu/Dockerfile
  tests/standalone_tests/shards/gke_gpu/Dockerfile
Labels: cc-test

#5442 feat(sdk): set job source in settings
  tests/functional_tests/t0_main/jobs/job_artifact_creation.py
  tests/functional_tests/t0_main/jobs/job_artifact_creation_disabled.py
  tests/functional_tests/t0_main/jobs/job_container_creation.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#5441 chore(launch): Remove batching from installation script
  wandb/sdk/launch/builder/templates/_wandb_bootstrap.py
Labels: cc-chore

#5083 fix(integrations): ensure wandb can be used in AWS lambda
  tests/functional_tests/t0_main/debug/t8_sentry_session_no_finish.py
  wandb/old/settings.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/internal/system/env_probe_helpers.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#5463 chore(sdk): bump version to 0.15.2.dev1 and update CHANGELOG.md
  CHANGELOG.md
  pyproject.toml
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5455 ci(sdk): clean up and organize our tox
  .circleci/config.yml
  .coveragerc
  Makefile
  requirements_test.txt
  setup.py
  tests/functional_tests/t0_main/artifacts/link-model-outside-run.yea
  tests/functional_tests/t0_main/artifacts/link-model.yea
  tests/functional_tests/t0_main/artifacts/log-image-artifact-path.yea
  tests/functional_tests/t0_main/artifacts/public-link-model.yea
  tests/functional_tests/t0_main/artifacts/use-and-link-model.yea
  tests/functional_tests/t0_main/console/t1_tqdm_wrap.yea
  tests/functional_tests/t0_main/console/t2_tqdm_nested_wrap.yea
  tests/functional_tests/t0_main/console/t5_tqdm_post_finish.yea
  tests/functional_tests/t0_main/core/t5_log_media.py
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.yea
  tests/functional_tests/t0_main/metaflow/wandb-example-flow-decoboth.yea
  tests/functional_tests/t0_main/metaflow/wandb-example-flow-decoclass.yea
  tests/functional_tests/t0_main/metaflow/wandb-example-flow-decostep.yea
  tests/functional_tests/t0_main/metaflow/wandb-foreach-flow.yea
  tests/functional_tests/t0_main/metaflow/wandb-pytorch-flow.yea
  tests/functional_tests/t0_main/tensorflow/t2_tensorflow_hook.yea
  tests/pytest_tests/conftest.py
  tests/pytest_tests/system_tests/test_launch/test_github_reference.py
  tests/pytest_tests/system_tests/test_launch/test_job.py
  tests/pytest_tests/system_tests/test_launch/test_launch.py
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/system_tests/test_launch/test_launch_local_container.py
  tests/pytest_tests/system_tests/test_launch/test_launch_run.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep_cli.py
  tests/pytest_tests/system_tests/test_launch/test_wandb_reference.py
  tests/pytest_tests/system_tests/test_notebooks/conftest.py
  tests/pytest_tests/system_tests/test_notebooks/test_notebooks.py
  tests/standalone_tests/artifact_tests.yea
  tests/standalone_tests/executor_tests/executor-pex.sh
  tests/standalone_tests/table_mem_test.yea
  tests/standalone_tests/tweets.yea
  tools/coverage-tool.py
  tox.ini
Labels: cc-ci

#5405 chore(artifacts): create a new `LogicalPath` class
  requirements_dev.txt
  tests/pytest_tests/unit_tests/test_lib/test_paths.py
  wandb/sdk/lib/paths.py
Labels: cc-chore

#5466 ci(sdk): fix windows tests
  .circleci/config.yml
  .coveragerc
  tests/functional_tests/t0_main/core/t6_log_images_unix.yea
  tests/functional_tests/t0_main/core/t6_log_images_win.yea
  tests/functional_tests/t0_main/magic/t1_mnist_convnet.yea
  tests/functional_tests/t0_main/torch/t1_sparse_tensors.yea
  tests/functional_tests/t0_main/xgboost/xgboost_clf.yea
  tox.ini
Labels: cc-ci

#5464 chore(sweeps): scheduler command args remerge
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep_cli.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py
  wandb/cli/cli.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-chore

#5468 chore(sdk): make func sklearn test use a local data file
  tests/functional_tests/t0_main/sklearn/t1_plot_calibration_curve_nonbinary.py
  tests/functional_tests/t0_main/sklearn/wine.csv
Labels: cc-chore

#5469 test(sdk): add triggers to run windows tests in ci on specificly-named branches
  .circleci/config.yml
  tests/pytest_tests/unit_tests/test_lib/test_paths.py
Labels: cc-test

#5471 chore(sdk): print a silly greeting message with tox
  tox.ini
Labels: cc-chore

#5473 fix(sdk): permit `LogicalPath` to strip trailing slashes
  tests/pytest_tests/unit_tests/test_lib/test_paths.py
Labels: cc-fix

#5327 chore(launch): Launch agent creates a run in associated project
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#5340 chore(sweeps): sweeps on launch run deletion handling
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/scheduler_sweep.py
Labels: cc-chore

#5459 chore(sweeps): check job existence and remove num_workers param
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep_cli.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py
  wandb/cli/cli.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-chore

#5478 fix(sdk): exercise caution when creating ~/.config/wandb/settings file
  wandb/old/settings.py
Labels: cc-fix

#5456 feat(sweeps): launch sweeps controlled by wandb run
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep_cli.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py
  wandb/cli/cli.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/sweeps/__init__.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-feat

#5467 fix(integrations): update WandbTracer for new langchain release
  tests/functional_tests/t0_main/langchain/t1_v1.py
  tests/functional_tests/t0_main/langchain/t1_v1.yea
  wandb/integration/langchain/monkeypatch.py
  wandb/integration/langchain/util.py
  wandb/integration/langchain/wandb_tracer.py
Labels: cc-fix

#5490 fix(integrations): fix error message in langchain wandb_tracer version check
  wandb/integration/langchain/wandb_tracer.py
Labels: cc-fix

#5491 chore(sdk): bump version to 0.15.3.dev1 and update CHANGELOG.md
  CHANGELOG.md
  pyproject.toml
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5474 feat(integrations): add autolog for Cohere python SDK
  .circleci/config.yml
  tests/functional_tests/t0_main/langchain/t1_v1.yea
  tests/functional_tests/t0_main/llm/t1_llm_cohere_generate.py
  tests/functional_tests/t0_main/llm/t1_llm_cohere_generate.yea
  tests/functional_tests/t0_main/llm/t2_llm_openai_edit.py
  tests/functional_tests/t0_main/llm/t2_llm_openai_edit.yea
  tests/functional_tests/t0_main/llm/t3_llm_openai_completion.py
  tests/functional_tests/t0_main/llm/t3_llm_openai_completion.yea
  tests/functional_tests/t0_main/llm/t4_llm_openai_chat_completion.py
  tests/functional_tests/t0_main/llm/t4_llm_openai_chat_completion.yea
  tests/functional_tests/t0_main/llm/t5_llm_openai_edit_weird_autolog_api_usage.py
  tests/functional_tests/t0_main/llm/t5_llm_openai_edit_weird_autolog_api_usage.yea
  tests/functional_tests/t0_main/llm/t6_llm_openai_edit_weird_autolog_api_usage_2.py
  tests/functional_tests/t0_main/llm/t6_llm_openai_edit_weird_autolog_api_usage_2.yea
  tests/functional_tests/t0_main/llm/t7_llm_jerome_battle.py
  tests/functional_tests/t0_main/llm/t7_llm_jerome_battle.yea
  tox.ini
  wandb/integration/cohere/__init__.py
  wandb/integration/cohere/cohere.py
  wandb/integration/cohere/resolver.py
  wandb/integration/openai/__init__.py
  wandb/integration/openai/openai.py
  wandb/integration/openai/resolver.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/integration_utils/llm.py
  wandb/sdk/lib/timer.py
Labels: cc-feat

#5407 refactor(artifacts): replace `LogicalFilePathStr` and `to_forward_slash_path`
  requirements_dev.txt
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_lib/test_paths.py
  tests/pytest_tests/unit_tests/test_wandb_artifacts.py
  wandb/apis/public.py
  wandb/filesync/dir_watcher.py
  wandb/sdk/data_types/base_types/media.py
  wandb/sdk/data_types/image.py
  wandb/sdk/data_types/molecule.py
  wandb/sdk/data_types/object_3d.py
  wandb/sdk/data_types/saved_model.py
  wandb/sdk/interface/artifacts/artifact.py
  wandb/sdk/interface/artifacts/artifact_manifest.py
  wandb/sdk/internal/file_pusher.py
  wandb/sdk/internal/tb_watcher.py
  wandb/sdk/lib/paths.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-refactor

#5408 refactor(artifacts): replace `SaveName` with `LogicalPath`
  requirements_dev.txt
  wandb/filesync/dir_watcher.py
  wandb/filesync/step_checksum.py
  wandb/filesync/step_upload.py
  wandb/filesync/upload_job.py
  wandb/sdk/internal/file_pusher.py
Labels: cc-refactor

#5404 refactor(artifacts): infer the size from a local file if not passed in
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_wandb_artifacts.py
  wandb/sdk/interface/artifacts/artifact_manifest.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-refactor

#5508 test(integrations): fix executor-pex test
  tests/standalone_tests/executor_tests/executor-pex.sh
Labels: cc-test

#5472 fix(sdk): allow SKD to work if SA token can't be read
  wandb/util.py
Labels: cc-fix

#4852 fix(sdk): Fix custom chart query to work for more broad cases and add alternate constructor to simplify adding charts for tables
  wandb/apis/reports/_panels.py
Labels: cc-fix

#5486 feat(launch): support launching custom k8s objects
  tests/pytest_tests/unit_tests/test_launch/test_project/test_project.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-feat

#5377 fix(artifacts): add s3 multipart uploading for artifact files
  tests/pytest_tests/unit_tests/test_step_prepare.py
  tests/pytest_tests/unit_tests/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests_old/utils/mock_server.py
  tox.ini
  wandb/apis/internal.py
  wandb/filesync/step_prepare.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-fix

#5416 fix(sdk): Ensure artifact name strings conform to Artifacts requirements
  tests/pytest_tests/system_tests/test_importers/conftest.py
  tests/pytest_tests/system_tests/test_importers/test_import_mlflow.py
  wandb/apis/importers/base.py
  wandb/apis/importers/mlflow.py
Labels: cc-fix

#5519 refactor(artifacts): move EventJobDone to its point of use
  wandb/filesync/step_upload.py
  wandb/filesync/upload_job.py
Labels: cc-refactor

#5531 fix(launch): docker runner always pull for image sourced jobs
  tests/pytest_tests/system_tests/test_launch/test_launch_local_container.py
  wandb/sdk/launch/runner/local_container.py
Labels: cc-fix

#5528 refactor(artifacts): extract prepare_response from the body of the event loop
  wandb/filesync/step_prepare.py
Labels: cc-refactor

#5529 refactor(artifacts): consistently order ResponsePrepare fields
  tests/pytest_tests/unit_tests/test_step_prepare.py
  tests/pytest_tests/unit_tests/test_wandb_artifacts.py
  wandb/filesync/step_prepare.py
Labels: cc-refactor

#5530 refactor(artifacts): rename multipart_upload_url -> multipart_upload_urls
  tests/pytest_tests/unit_tests/test_step_prepare.py
  tests/pytest_tests/unit_tests/test_wandb_artifacts.py
  wandb/filesync/step_prepare.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-refactor

#5509 fix(launch): Better error handling in requirement installation
  wandb/sdk/launch/builder/templates/_wandb_bootstrap.py
Labels: cc-fix

#5538 fix(launch): custom k8s objects respect command/args overrides
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#5541 test(sdk): use `USER` env variable instead of `METAFLOW_USER` variable
  tests/functional_tests/t0_main/metaflow/wandb-example-flow-decoboth.py
  tests/functional_tests/t0_main/metaflow/wandb-example-flow-decoclass.py
  tests/functional_tests/t0_main/metaflow/wandb-example-flow-decostep.py
  tests/functional_tests/t0_main/metaflow/wandb-foreach-flow.py
  tests/functional_tests/t0_main/metaflow/wandb-pytorch-flow.py
Labels: cc-test

#5524 feat(artifacts): Artifacts: allow saved artifacts to be modified and logged as a new version
  wandb/apis/public.py
Labels: cc-feat

#5545 test(artifacts): Artifacts: remove unnecessary mock
  tests/pytest_tests/unit_tests/test_saved_model.py
Labels: cc-test

#5548 feat(launch): don't install frozen reqs if there is a reqs file
  wandb/sdk/launch/builder/build.py
Labels: cc-feat

#5482 fix(launch): Use env var to define launch agent base url
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  wandb/cli/cli.py
  wandb/sdk/launch/deploys/aws-eks/launch-agent.yaml
  wandb/sdk/launch/deploys/aws-eks/launch-config.yaml
  wandb/sdk/launch/deploys/gcp-gke/launch-agent.yaml
  wandb/sdk/launch/deploys/gcp-gke/launch-config.yaml
  wandb/sdk/launch/deploys/kubernetes/launch-agent.yaml
  wandb/sdk/launch/deploys/kubernetes/launch-config.yaml
  wandb/sdk/launch/launch.py
Labels: cc-fix

#5562 revert(sdk): update summary for changed keys only
  wandb/sdk/internal/handler.py
Labels: cc-revert

#5568 chore(sdk): bump version to 0.15.4.dev1 and update CHANGELOG.md
  CHANGELOG.md
  pyproject.toml
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5578 test(sdk): add a prefect-ray workflow execution test
  tests/functional_tests/t0_main/prefect_ray/t1_prefect_ray_workflow.py
  tests/functional_tests/t0_main/prefect_ray/t1_prefect_ray_workflow.yea
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/wandb_init.py
Labels: cc-test

#5584 ci(sdk): add github action to suggest and/or fix PR title
  .github/workflows/fix-pr-title.yml
  tools/pr-title-bot.py
Labels: cc-ci

#5585 ci(sdk): add github action to suggest and/or fix PR title
  .github/workflows/fix-pr-title.yml
Labels: cc-ci

#5586 ci(sdk): add github action to suggest and/or fix PR title
  .github/workflows/fix-pr-title.yml
Labels: cc-ci

#5589 ci(sdk): add github action to suggest and/or fix PR title
  .github/workflows/fix-pr-title.yml
Labels: cc-ci

#5590 ci(sdk): add github action to suggest and/or fix PR title
  .github/workflows/fix-pr-title.yml
Labels: cc-ci

#5596 feat(artifacts): don't remove temp files from artifacts cache by default
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/cli/cli.py
  wandb/sdk/interface/artifacts/artifact_cache.py
Labels: cc-feat

#5597 fix(artifacts): write to the cache defensively (catch OSError)
  tests/pytest_tests/unit_tests/test_wandb_artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-fix

#5609 test(sdk): fix prodigy integration test
  tests/functional_tests/t0_main/prodigy/prodigy_integration.py
Labels: cc-test

#5546 feat(artifacts): Artifacts: add .source_entity et al.
  tests/pytest_tests/unit_tests_old/test_wandb_run.py
  wandb/apis/public.py
  wandb/sdk/interface/artifacts/artifact.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-feat

#5370 feat(artifacts): add 'remove' to Artifacts API
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  wandb/apis/public.py
  wandb/sdk/interface/artifacts/artifact.py
  wandb/sdk/interface/artifacts/artifact_manifest.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-feat

#5610 fix(launch): Always fail run queue items if an exception is raised in thread
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#5551 refactor(artifacts): Artifacts: add missing type annotations
  mypy.ini
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  tests/pytest_tests/unit_tests_old/test_public_api.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_download_logger.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
  wandb/sdk/artifacts/downloaded_artifact_entry.py
  wandb/sdk/artifacts/lazy_artifact.py
  wandb/sdk/artifacts/local_artifact.py
  wandb/sdk/artifacts/public_artifact.py
  wandb/sdk/artifacts/storage_handlers/wb_artifact_handler.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
  wandb/sdk/artifacts/storage_policy.py
  wandb/sdk/data_types/helper_types/classes.py
  wandb/sdk/data_types/image.py
  wandb/sdk/data_types/saved_model.py
Labels: cc-refactor

#5547 refactor(artifacts): Artifacts: consolidate manifest entry classes
  tests/pytest_tests/unit_tests/test_saved_model.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
  wandb/sdk/artifacts/downloaded_artifact_entry.py
  wandb/sdk/artifacts/local_artifact.py
  wandb/sdk/artifacts/public_artifact.py
Labels: cc-refactor

#5613 chore(sweeps): quote run args
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-chore

#5614 docs(sdk): update contrib for yea-wandb changes
  CONTRIBUTING.md
Labels: cc-docs

#4900 feat(sweeps): optuna scheduler for sweeps on launch
  setup.py
  tests/pytest_tests/system_tests/test_launch/test_launch_local_container.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep_cli.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  wandb/apis/internal.py
  wandb/cli/cli.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/launch/sweeps/__init__.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/utils.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#5462 feat(launch): Support job creation for notebooks
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.py
  tests/pytest_tests/assets/notebooks/one_cell_disable_git.ipynb
  tests/pytest_tests/assets/notebooks/one_cell_set_git.ipynb
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/system_tests/test_notebooks/test_notebooks.py
  tests/pytest_tests/unit_tests/test_job_builder.py
  tests/pytest_tests/unit_tests/tests_launch/test_job.py
  wandb/apis/public.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/launch/utils.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#5602 fix(launch): add pull secrets for pre made images when registry is specified
  wandb/sdk/launch/builder/noop.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#5619 fix(launch): read kaniko pod sa name from env var
  wandb/sdk/launch/builder/kaniko_builder.py
Labels: cc-fix

#5575 chore(launch): improve layer caching in agent build script
  tools/build_launch_agent.py
Labels: cc-chore

#5621 ci(sdk): fix pr title bot github action
  .github/workflows/fix-pr-title.yml
Labels: cc-ci

#5622 ci(sdk): fix pr title bot github action
  .github/workflows/fix-pr-title.yml
Labels: cc-ci

#5623 ci(sdk): fix pr title bot github action
  .github/workflows/fix-pr-title.yml
Labels: cc-ci

#5606 test(integrations): add telemetry for LLM-focused libraries
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
Labels: cc-test

#5620 chore(sweeps): add warning for non-custom methods with scheduler jobs
  wandb/cli/cli.py
Labels: cc-chore

#5603 chore(launch): update job validation
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep_cli.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_jobs.py
  wandb/apis/public.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-chore

#5624 feat(launch): enable launch macros for all runners
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/runner/sagemaker_runner.py
  wandb/sdk/launch/runner/vertex_runner.py
Labels: cc-feat

#5626 fix(launch): misc gcp fixes
  wandb/sdk/launch/environment/gcp_environment.py
  wandb/sdk/launch/registry/google_artifact_registry.py
Labels: cc-fix

#5638 refactor(sdk): add thread local api settings for authentication
  tests/pytest_tests/unit_tests/test_public_api.py
  tests/pytest_tests/unit_tests/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests_old/utils/mock_requests.py
  tox.ini
  wandb/apis/public.py
  wandb/sdk/artifacts/artifacts_cache.py
  wandb/sdk/artifacts/public_artifact.py
  wandb/sdk/artifacts/storage_handlers/http_handler.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
  wandb/sdk/internal/file_stream.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/thread_local_settings.py
  wandb/sdk/lib/capped_dict.py
  wandb/util.py
Labels: cc-refactor

#5635 fix(launch): support ssh git urls and submodules in agent
  tests/pytest_tests/system_tests/test_launch/test_launch.py
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_gcp.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_aws.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_gcp.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_jobs.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_kubernetes.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_utils.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/builder/noop.py
  wandb/sdk/launch/environment/aws_environment.py
  wandb/sdk/launch/environment/gcp_environment.py
  wandb/sdk/launch/environment/local_environment.py
  wandb/sdk/launch/errors.py
  wandb/sdk/launch/github_reference.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/launch/loader.py
  wandb/sdk/launch/registry/elastic_container_registry.py
  wandb/sdk/launch/registry/google_artifact_registry.py
  wandb/sdk/launch/registry/local_registry.py
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/local_process.py
  wandb/sdk/launch/runner/sagemaker_runner.py
  wandb/sdk/launch/runner/vertex_runner.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/utils.py
  wandb/sdk/launch/utils.py
Labels: cc-fix
