Repository wandb/wandb, pull requests merged in 2023-03, with the labels that each got.

#5056 fix(artifacts): only re-download or overwrite files when there are changes
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  wandb/apis/public.py
Labels: cc-fix

#5002 fix(sdk): avoid introspection in offline mode
  wandb/sdk/data_types/image.py
Labels: cc-fix

#5031 fix(sdk): Allow pathlib.Path in ImageDataOrPathType
  wandb/sdk/data_types/image.py
Labels: cc-fix

#5073 feat(sdk): update .save method to accept pathlib.Path object
  tests/pytest_tests/unit_tests/test_wandb_save.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#4899 feat(sdk): OpenMetrics support for System Metrics
  requirements.txt
  requirements_dev.txt
  tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_open_metrics.py
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  wandb/proto/v3/wandb_server_pb2.py
  wandb/proto/v3/wandb_server_pb2.pyi
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_server_pb2.py
  wandb/proto/v4/wandb_server_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_server.proto
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/internal/settings_static.py
  wandb/sdk/internal/system/assets/__init__.py
  wandb/sdk/internal/system/assets/open_metrics.py
  wandb/sdk/internal/system/assets/trainium.py
  wandb/sdk/internal/system/system_monitor.py
  wandb/sdk/lib/proto_util.py
  wandb/sdk/service/service_base.py
  wandb/sdk/wandb_settings.py
  wandb/viz.py
Labels: cc-feat

#5034 feat(sdk): add ability to filter system metrics consumed from OpenMetrics endpoints
  tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_open_metrics.py
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  tests/standalone_tests/jupyter_test.ipynb
  wandb/proto/v3/wandb_server_pb2.py
  wandb/proto/v3/wandb_server_pb2.pyi
  wandb/proto/v4/wandb_server_pb2.py
  wandb/proto/v4/wandb_server_pb2.pyi
  wandb/proto/wandb_server.proto
  wandb/sdk/internal/settings_static.py
  wandb/sdk/internal/system/assets/open_metrics.py
  wandb/sdk/lib/proto_util.py
  wandb/sdk/service/service_base.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#5008 feat(sdk): add support for gymnasium env monitoring, in addition to gym
  wandb/integration/gym/__init__.py
Labels: cc-feat

#4022 chore(sdk): topological ordering of `wandb.Settings`
  CONTRIBUTING.md
  tests/functional_tests/t0_main/login/t3_login_cloud_local_key.yea
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  tools/generate-tool.py
  tox.ini
  wandb/sdk/lib/_settings_toposort_generate.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-chore

#5057 chore(launch): max_scheduler key in launch agent config
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/launch.py
Labels: cc-chore

#5079 fix(sdk): avoid lazy loading for tensorboard patching
  wandb/integration/tensorboard/monkeypatch.py
Labels: cc-fix

#5061 docs(artifacts): raise ArtifactFinalizedError instead of ValueError
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_init.py
Labels: cc-docs

#5080 chore(sdk): fix (ruff) pre-commit hook, update hook versions
  .pre-commit-config.yaml
Labels: cc-chore

#5037 feat(integrations): add an integration with `ultralytics` library for YOLOv8
  mypy.ini
  tests/functional_tests/t0_main/yolov8/test_yolov8_classification.py
  tests/functional_tests/t0_main/yolov8/test_yolov8_classification.yea
  tests/functional_tests/t0_main/yolov8/test_yolov8_detection.py
  tests/functional_tests/t0_main/yolov8/test_yolov8_detection.yea
  tests/functional_tests/t0_main/yolov8/test_yolov8_segmentation.py
  tests/functional_tests/t0_main/yolov8/test_yolov8_segmentation.yea
  wandb/integration/yolov8/__init__.py
  wandb/integration/yolov8/yolov8.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
Labels: cc-feat

#4951 chore(launch): Improved method for getting pod status
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_kubernetes.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-chore

#5086 docs(launch): Add hidden --url option ahead of implementing the actual feature
  wandb/cli/cli.py
Labels: cc-docs

#5044 feat(launch): Support cuda base image for launch runs
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_cli.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_sweep.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_docker.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_jobs.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#5091 ci(sdk): clean up auto-generated release notes by removing the dev section
  .github/release.yml
Labels: cc-ci

#5095 fix(sdk): temporarily remove local api key validation
  tests/functional_tests/t0_main/login/t3_login_cloud_local_key.yea
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#5098 test(launch): Fix malformed key in launch cuda tests
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_docker.py
Labels: cc-test

#5102 chore(sdk): bump version to 0.13.12.dev1 and update CHANGELOG.md
  CHANGELOG.md
  pyproject.toml
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5097 ci(integrations): do not run import tests in nightly
  .circleci/config.yml
Labels: cc-ci

#5064 chore(launch): sweep config image_uri and command arg handling
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#5090 chore(launch): Kubernetes runner doesn't require secret for LocalRegistry
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-chore

#5092 docs(launch): Remove stack trace when failing to connect to docker
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/utils.py
Labels: cc-docs

#5112 fix(launch): make launch on eks with instance roles work
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/deploys/aws-eks/launch-agent.yaml
  wandb/sdk/launch/deploys/aws-eks/launch-config.yaml
  wandb/sdk/launch/deploys/kubernetes/launch-agent.yaml
  wandb/sdk/launch/deploys/kubernetes/launch-config.yaml
  wandb/sdk/launch/environment/aws_environment.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/registry/elastic_container_registry.py
  wandb/sdk/launch/utils.py
Labels: cc-fix

#5124 fix(launch): More generic error message + thread handling when Docker fails
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#4996 fix(launch): Fix launch using cached images for mutable artifact aliases
  tests/pytest_tests/unit_tests/test_docker.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  tests/pytest_tests/unit_tests/test_launch/test_project/test_project.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_ecr.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_docker.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/registry/abstract.py
  wandb/sdk/launch/registry/elastic_container_registry.py
  wandb/sdk/launch/registry/google_artifact_registry.py
  wandb/sdk/launch/registry/local_registry.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/utils.py
Labels: cc-fix

#5115 chore(sweeps): split entrypoint in docker command
  tests/pytest_tests/system_tests/tests_launch/test_launch_local_container.py
  wandb/sdk/launch/runner/local_container.py
Labels: cc-chore

#5093 chore(launch): improved error messaging and style
  wandb/cli/cli.py
Labels: cc-chore

#5125 chore(launch): agent extra check when running sweep scheduler local-proc
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#5107 chore(sweeps): gracefully handle cancelled sweeps
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#5109 feat(launch): Warn users of which packages failed to install during build process
  wandb/docker/__init__.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/builder/templates/_wandb_bootstrap.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#4950 feat(sdk): Add support for importing runs from MLFlow
  mypy.ini
  requirements_dev.txt
  tests/pytest_tests/system_tests/test_importers/conftest.py
  tests/pytest_tests/system_tests/test_importers/test_import_mlflow.py
  wandb/apis/importers/__init__.py
  wandb/apis/importers/base.py
  wandb/apis/importers/mlflow.py
  wandb/cli/cli.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
Labels: cc-feat

#5126 security(launch): Warn when agent is started on a team queue
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/apis/internal.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-security

#5129 feat(launch): Fail queued runs items that fail to start
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/apis/internal.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/runner/abstract.py
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/runner/local_process.py
  wandb/sdk/launch/runner/sagemaker_runner.py
  wandb/sdk/launch/runner/vertex_runner.py
Labels: cc-feat

#5140 chore(launch): clean up run when rqi-state is failed
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#5141 fix(sdk): add telemetry when syncing tfevents files
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sync/sync.py
Labels: cc-fix

#5139 fix(sdk): fix regression preventing run stopping from working
  wandb/sdk/wandb_run.py
Labels: cc-fix

#5146 chore(launch): better job not found error msg
  wandb/sdk/launch/_project_spec.py
Labels: cc-chore

#5138 fix(launch): Display "install wandb[launch]" message when failing to import Kubernetes
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#5151 fix(launch): Remove confusing warning when using artifacts in launch context
  wandb/sdk/wandb_run.py
Labels: cc-fix

#5153 fix(launch): Hide unsupported CLI options from launch
  tests/pytest_tests/system_tests/tests_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/cli/cli.py
Labels: cc-fix

#5147 fix(launch): torch installs fixes
  wandb/sdk/launch/builder/templates/_wandb_bootstrap.py
Labels: cc-fix

#5111 chore(launch): Add sentry contexts for launch and sweep scheduler
  wandb/cli/cli.py
  wandb/sdk/launch/agent/agent.py
  wandb/util.py
Labels: cc-chore

#5020 chore(launch): hide launch internal project from logs
  tests/pytest_tests/system_tests/tests_launch/test_launch.py
  wandb/sdk/internal/internal_api.py
Labels: cc-chore

#5161 chore(sdk): bump version to 0.14.1.dev1 and update CHANGELOG.md
  CHANGELOG.md
  pyproject.toml
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5067 fix(artifacts): inform user they can set WANDB_DATA_DIR to another value
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/interface/artifacts.py
Labels: cc-fix

#5131 feat(artifacts): allow logging artifact from path/str directly
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#5060 refactor(artifacts): push common method defs to the parent class
  wandb/apis/public.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-refactor

#5045 chore(sdk): ignore unused import errors in __init__.py files generally
  .flake8-base
  pyproject.toml
Labels: cc-chore

#5050 refactor(artifacts): use 'secrets' module instead of custom random token generator
  wandb/sdk/interface/artifacts.py
  wandb/util.py
Labels: cc-refactor

#5175 chore(sdk): revert .vscode/settings.json changes
  .vscode/settings.json
Labels: cc-chore

#5178 refactor(artifacts): move _manifest_json_from_proto to sender.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/internal/artifacts.py
  wandb/sdk/internal/sender.py
Labels: cc-refactor

#5181 chore(artifacts): use absolute imports
  wandb/sdk/internal/artifacts.py
  wandb/sdk/internal/sender.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-chore

#5173 chore(sdk): warn the user if provided run_id is invalid (empty or allspaces)
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-chore

#5072 fix(launch): Fix Kubernetes default backoffLimit behavior to 0
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#5127 fix(sdk): remove default sorting when dumping config into a yaml file
  tests/pytest_tests/unit_tests/test_sender.py
  wandb/sdk/lib/config_util.py
Labels: cc-fix

#5081 chore(artifacts): add telemetry for async-uploads feature
  tests/pytest_tests/system_tests/test_core/test_telemetry_full.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/wandb_init.py
Labels: cc-chore

#5180 fix(media): fix encoding for html types on windows
  wandb/sdk/data_types/html.py
Labels: cc-fix

#5150 perf(sdk): save summary updates for changed keys only
  wandb/sdk/internal/handler.py
Labels: cc-perf

#4925 chore(sdk): do not repeat the "Saving files without folders" warning
  wandb/sdk/wandb_run.py
Labels: cc-chore

#5185 refactor(artifacts): move get_staging_directory() out of the interface and into the saver
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/internal/artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-refactor

#5075 feat(sdk): use a persistent session object for GraphQL requests
  mypy.ini
  tests/pytest_tests/unit_tests_old/utils/mock_server.py
  tox.ini
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/lib/gql_request.py
  wandb/sdk/verify/verify.py
Labels: cc-feat

#5184 fix(sdk): clear up auto resume artifacts after a non resume init call
  tests/pytest_tests/unit_tests/test_wandb_run.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#5023 fix(sdk): improve the error path during init for errors originating from the backend
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
  tests/pytest_tests/unit_tests/test_error_util.py
  tests/pytest_tests/unit_tests/test_normalize.py
  tests/pytest_tests/unit_tests/test_util.py
  tests/pytest_tests/unit_tests/test_wandb_init.py
  tests/pytest_tests/unit_tests_old/test_sender.py
  tests/pytest_tests/unit_tests_old/test_wandb_integration.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_jobs.py
  wandb/apis/normalize.py
  wandb/errors/__init__.py
  wandb/errors/util.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/backend/backend.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/sender.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-fix

#5200 refactor(sdk): replace `mp.synchronize.Event`s with `threading.Event`s throughout system metrics code
  tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_gpu.py
  tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_gpu_apple.py
  tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_ipu.py
  tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_tpu.py
  tests/pytest_tests/unit_tests/test_system_metric/test_system_monitor.py
  wandb/sdk/internal/system/assets/cpu.py
  wandb/sdk/internal/system/assets/disk.py
  wandb/sdk/internal/system/assets/gpu.py
  wandb/sdk/internal/system/assets/gpu_apple.py
  wandb/sdk/internal/system/assets/interfaces.py
  wandb/sdk/internal/system/assets/ipu.py
  wandb/sdk/internal/system/assets/memory.py
  wandb/sdk/internal/system/assets/network.py
  wandb/sdk/internal/system/assets/open_metrics.py
  wandb/sdk/internal/system/assets/tpu.py
  wandb/sdk/internal/system/assets/trainium.py
  wandb/sdk/internal/system/system_monitor.py
Labels: cc-refactor

#5229 chore(sdk): pin ruff to 0.0.258
  .pre-commit-config.yaml
  tests/standalone_tests/artifact_references.py
  tox.ini
Labels: cc-chore

#5227 fix(sdk): shut down system monitor in handler.finish
  tests/standalone_tests/artifact_references.py
  tox.ini
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/system/assets/interfaces.py
Labels: cc-fix

#5040 refactor(sdk): refactor and improve Sentry error management
  tests/functional_tests/t0_main/debug/sentry_third_party.py
  tests/functional_tests/t0_main/debug/t3_sentry_userproc.py
  tests/functional_tests/t0_main/debug/t6_sentry_third_party_no_wandb_error_reporting.yea
  tests/pytest_tests/unit_tests/test_library_public.py
  tests/pytest_tests/unit_tests/test_step_upload.py
  tests/pytest_tests/unit_tests/test_wandb_init.py
  wandb/__init__.py
  wandb/analytics/__init__.py
  wandb/analytics/sentry.py
  wandb/cli/cli.py
  wandb/filesync/upload_job.py
  wandb/sdk/internal/file_stream.py
  wandb/sdk/internal/internal.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/system/assets/__init__.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/lib/__init__.py
  wandb/sdk/service/service.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_manager.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-refactor

#4596 docs(launch): Add readmes to launch
  wandb/sdk/launch/agent/README.md
  wandb/sdk/launch/builder/README.md
  wandb/sdk/launch/runner/README.md
Labels: cc-docs

#5267 fix(sdk): fix bug in deciding prod vs dev sentry env
  tests/pytest_tests/unit_tests/test_datastore.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  tests/standalone_tests/artifact_load.py
  wandb/analytics/sentry.py
  wandb/sdk/lib/git.py
Labels: cc-fix
