Repository wandb/wandb, pull requests merged in 2023-01, with the labels that each got.

#4618 chore(sdk): make MetricsMonitor less verbose on errors
  wandb/sdk/internal/system/assets/interfaces.py
Labels: cc-chore

#4716 test(sdk): address fixture server move from port 9003 to 9010 in local-testcontainer
  tests/unit_tests/conftest.py
Labels: cc-test

#4622 chore(sdk): vendor promise==2.3.0 to unequivocally rm six dependency
  requirements.txt
  wandb/util.py
  wandb/vendor/graphql-core-1.1/wandb_graphql/execution/executor.py
  wandb/vendor/graphql-core-1.1/wandb_graphql/execution/executors/asyncio.py
  wandb/vendor/graphql-core-1.1/wandb_graphql/execution/executors/gevent.py
  wandb/vendor/graphql-core-1.1/wandb_graphql/execution/executors/process.py
  wandb/vendor/graphql-core-1.1/wandb_graphql/execution/executors/thread.py
  wandb/vendor/graphql-core-1.1/wandb_graphql/execution/experimental/executor.py
  wandb/vendor/graphql-core-1.1/wandb_graphql/execution/experimental/fragment.py
  wandb/vendor/graphql-core-1.1/wandb_graphql/execution/experimental/resolver.py
  wandb/vendor/graphql-core-1.1/wandb_graphql/execution/middleware.py
  wandb/vendor/promise-2.3.0/.coveragerc
  wandb/vendor/promise-2.3.0/.gitignore
  wandb/vendor/promise-2.3.0/.travis.yml
  wandb/vendor/promise-2.3.0/LICENSE
  wandb/vendor/promise-2.3.0/MANIFEST.in
  wandb/vendor/promise-2.3.0/README.md
  wandb/vendor/promise-2.3.0/README.rst
  wandb/vendor/promise-2.3.0/conftest.py
  wandb/vendor/promise-2.3.0/setup.cfg
  wandb/vendor/promise-2.3.0/setup.py
  wandb/vendor/promise-2.3.0/tests/__init__.py
  wandb/vendor/promise-2.3.0/tests/conftest.py
  wandb/vendor/promise-2.3.0/tests/test_awaitable.py
  wandb/vendor/promise-2.3.0/tests/test_awaitable_35.py
  wandb/vendor/promise-2.3.0/tests/test_benchmark.py
  wandb/vendor/promise-2.3.0/tests/test_complex_threads.py
  wandb/vendor/promise-2.3.0/tests/test_dataloader.py
  wandb/vendor/promise-2.3.0/tests/test_dataloader_awaitable_35.py
  wandb/vendor/promise-2.3.0/tests/test_dataloader_extra.py
  wandb/vendor/promise-2.3.0/tests/test_extra.py
  wandb/vendor/promise-2.3.0/tests/test_issues.py
  wandb/vendor/promise-2.3.0/tests/test_promise_list.py
  wandb/vendor/promise-2.3.0/tests/test_spec.py
  wandb/vendor/promise-2.3.0/tests/test_thread_safety.py
  wandb/vendor/promise-2.3.0/tests/utils.py
  wandb/vendor/promise-2.3.0/wandb-vendor.diff
  wandb/vendor/promise-2.3.0/wandb-vendor.md
  wandb/vendor/promise-2.3.0/wandb_promise/__init__.py
  wandb/vendor/promise-2.3.0/wandb_promise/async_.py
  wandb/vendor/promise-2.3.0/wandb_promise/compat.py
  wandb/vendor/promise-2.3.0/wandb_promise/dataloader.py
  wandb/vendor/promise-2.3.0/wandb_promise/iterate_promise.py
  wandb/vendor/promise-2.3.0/wandb_promise/promise.py
  wandb/vendor/promise-2.3.0/wandb_promise/promise_list.py
  wandb/vendor/promise-2.3.0/wandb_promise/py.typed
  wandb/vendor/promise-2.3.0/wandb_promise/pyutils/__init__.py
  wandb/vendor/promise-2.3.0/wandb_promise/pyutils/version.py
  wandb/vendor/promise-2.3.0/wandb_promise/schedulers/__init__.py
  wandb/vendor/promise-2.3.0/wandb_promise/schedulers/asyncio.py
  wandb/vendor/promise-2.3.0/wandb_promise/schedulers/gevent.py
  wandb/vendor/promise-2.3.0/wandb_promise/schedulers/immediate.py
  wandb/vendor/promise-2.3.0/wandb_promise/schedulers/thread.py
  wandb/vendor/promise-2.3.0/wandb_promise/utils.py
Labels: cc-chore

#4676 fix(sdk): remove duplicate generate_id functions, replace shortuuid with secrets
  requirements.txt
  tests/standalone_tests/artifact_references.py
  tests/standalone_tests/resuming_and_reinit.py
  tests/unit_tests/conftest.py
  tests/unit_tests/lib/test_runid.py
  tests/unit_tests/test_offline_sync.py
  tests/unit_tests/test_public_api.py
  tests/unit_tests/test_redir_full.py
  tests/unit_tests_old/conftest.py
  tests/unit_tests_old/tests_launch/test_launch.py
  wandb/apis/public.py
  wandb/data_types.py
  wandb/filesync/step_checksum.py
  wandb/sdk/data_types/base_types/json_metadata.py
  wandb/sdk/data_types/helper_types/image_mask.py
  wandb/sdk/data_types/html.py
  wandb/sdk/data_types/image.py
  wandb/sdk/data_types/molecule.py
  wandb/sdk/data_types/object_3d.py
  wandb/sdk/data_types/plotly.py
  wandb/sdk/data_types/saved_model.py
  wandb/sdk/data_types/video.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/runner/abstract.py
  wandb/sdk/lib/runid.py
  wandb/sdk/verify/verify.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_init.py
  wandb/sync/sync.py
  wandb/util.py
Labels: cc-fix

#4718 fix(integrations): fix type check for jax.Array introduced in jax==0.4.1
  requirements_dev.txt
  wandb/util.py
Labels: cc-fix

#4660 feat(launch): Auto create job artifacts from runs with required ingredients
  tests/functional_tests/t0_main/grpc/t3_use_artifact.py
  tests/functional_tests/t0_main/grpc/t3_use_artifact.yea
  tests/functional_tests/t0_main/jobs/job_artifact_creation.py
  tests/functional_tests/t0_main/jobs/job_container_creation.py
  tests/functional_tests/t0_main/jobs/job_repo_creation.py
  tests/unit_tests/test_job_builder.py
  tests/unit_tests/tests_launch/test_launch_run.py
  tests/unit_tests_old/test_wandb_run.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v3/wandb_server_pb2.py
  wandb/proto/v3/wandb_server_pb2_grpc.py
  wandb/proto/v3/wandb_server_pb2_grpc.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_server_pb2.py
  wandb/proto/v4/wandb_server_pb2_grpc.py
  wandb/proto/v4/wandb_server_pb2_grpc.pyi
  wandb/proto/wandb_internal.proto
  wandb/proto/wandb_server.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_grpc.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
  wandb/sdk/service/server_grpc.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#4405 fix(sdk): fix hang after failed wandb.init (add cancel)
  tests/functional_tests/t0_main/core/t8_init_fail.py
  tests/functional_tests/t0_main/offline/t1_no_network.py
  tests/unit_tests/conftest.py
  tests/unit_tests/test_system_info.py
  tests/unit_tests/test_wandb.py
  tests/unit_tests_old/conftest.py
  wandb/apis/normalize.py
  wandb/errors/__init__.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v3/wandb_server_pb2.py
  wandb/proto/v3/wandb_server_pb2_grpc.py
  wandb/proto/v3/wandb_server_pb2_grpc.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_server_pb2.py
  wandb/proto/v4/wandb_server_pb2_grpc.py
  wandb/proto/v4/wandb_server_pb2_grpc.pyi
  wandb/proto/wandb_internal.proto
  wandb/proto/wandb_server.proto
  wandb/sdk/backend/backend.py
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_grpc.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/context.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/internal.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/writer.py
  wandb/sdk/lib/mailbox.py
  wandb/sdk/lib/retry.py
  wandb/sdk/service/server_grpc.py
  wandb/sdk/service/server_sock.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_manager.py
  wandb/sync/sync.py
  wandb/util.py
Labels: cc-fix

#4729 feat(sdk): add generalized response injection pattern for tests
  tests/unit_tests/conftest.py
  tests/unit_tests/test_file_stream_internal.py
Labels: cc-feat

#3644 chore(artifacts): Allow setting artifact cache dir in wandb.init(...)
  tests/unit_tests/artifacts/test_wandb_artifacts_cache.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/wandb_settings.py
Labels: cc-chore

#4604 fix(sdk): allow users to provide path to custom executables
  .circleci/config.yml
  wandb/env.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#4575 fix(sdk): fix TypeError when trying to slice a Paginator object
  wandb/apis/public.py
Labels: contrib, cc-fix

#4724 feat(sdk): use transaction log to cap memory usage
  mypy.ini
  requirements.txt
  requirements_test.txt
  tests/functional_tests/t0_main/grpc/t4_status.py
  tests/functional_tests/t0_main/grpc/t4_status.yea
  tests/standalone_tests/mitm_tests/mem_pressure.py
  tests/standalone_tests/mitm_tests/t1_mem_pressure_init.yea
  tests/unit_tests/conftest.py
  tests/unit_tests/test_datastore.py
  tests/unit_tests/test_flow_control.py
  tests/unit_tests/test_fsm.py
  tests/unit_tests/test_library_public.py
  tests/unit_tests/test_redir_full.py
  tests/unit_tests/test_run_status.py
  tests/unit_tests_old/conftest.py
  tox.ini
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v3/wandb_server_pb2.py
  wandb/proto/v3/wandb_server_pb2_grpc.py
  wandb/proto/v3/wandb_server_pb2_grpc.pyi
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_server_pb2.py
  wandb/proto/v4/wandb_server_pb2_grpc.py
  wandb/proto/v4/wandb_server_pb2_grpc.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/proto/wandb_server.proto
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_grpc.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/context.py
  wandb/sdk/internal/datastore.py
  wandb/sdk/internal/flow_control.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/internal.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/internal/writer.py
  wandb/sdk/lib/fsm.py
  wandb/sdk/lib/proto_util.py
  wandb/sdk/service/server_grpc.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
  wandb/sync/sync.py
Labels: cc-feat

#4737 test(sdk): temporary lower network buffer for testing
  wandb/sdk/internal/flow_control.py
Labels: cc-test

#4671 feat(integrations): System Metrics for AWS Trainium
  tests/unit_tests/test_system_metrics_trainium.py
  tests/unit_tests/test_system_monitor.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/internal/settings_static.py
  wandb/sdk/internal/system/assets/__init__.py
  wandb/sdk/internal/system/assets/gpu_apple.py
  wandb/sdk/internal/system/assets/trainium.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#4747 chore(sdk): add telemetry if the user running in pex environment
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/wandb_init.py
Labels: cc-chore

#4468 docs(sdk): Update README.md
  README.md
  docs/README_images/Product_Icons_dark_background/artifacts_icon.svg
  docs/README_images/Product_Icons_dark_background/evaluations_icon.svg
  docs/README_images/Product_Icons_dark_background/experiments_icon.svg
  docs/README_images/Product_Icons_dark_background/launch_icon.svg
  docs/README_images/Product_Icons_dark_background/models_icon.svg
  docs/README_images/Product_Icons_dark_background/reports_icon.svg
  docs/README_images/Product_Icons_dark_background/sweeps_icon.svg
  docs/README_images/Product_Icons_dark_background/tables_icon.svg
  docs/README_images/Product_Icons_light/artifacts_icon.svg
  docs/README_images/Product_Icons_light/evaluations_icon.svg
  docs/README_images/Product_Icons_light/experiments_icon.svg
  docs/README_images/Product_Icons_light/launch_icon.svg
  docs/README_images/Product_Icons_light/models_icon.svg
  docs/README_images/Product_Icons_light/reports_icon.svg
  docs/README_images/Product_Icons_light/sweeps_icon.svg
  docs/README_images/Product_Icons_light/tables_icon.svg
  docs/README_images/wandb_demo_experiments.gif
Labels: cc-docs

#4749 chore(sdk): add settings and debug for service startup issues (wait_for_ports)
  wandb/sdk/service/_startup_debug.py
  wandb/sdk/service/server.py
  wandb/sdk/service/service.py
  wandb/sdk/wandb_manager.py
  wandb/sdk/wandb_settings.py
  wandb/sdk/wandb_setup.py
Labels: cc-chore

#4750 fix(launch): Remove args from jobs
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.py
  tests/unit_tests/test_job_builder.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
Labels: cc-fix

#4753 test(sdk): fix AWS Trainium test
  README.md
  tests/unit_tests/test_system_metrics_trainium.py
  wandb/sdk/internal/system/assets/trainium.py
Labels: cc-test

#4761 chore(sdk): fix status checker thread issue when user process exits without finish()
  wandb/sdk/wandb_run.py
Labels: cc-chore

#4763 chore(sdk): put the Tracking run with... message back in
  tests/unit_tests_old/tests_s_nb/test_notebooks.py
  wandb/sdk/wandb_run.py
Labels: changelog-ignore, cc-chore

#4764 chore(sdk): merge 0.13.8 release branch into main
  CHANGELOG.md
Labels: cc-chore

#4708 perf(artifacts): reuse session for file upload requests
  wandb/sdk/internal/internal_api.py
Labels: cc-perf

#4691 test(artifacts): ensure manifest version is verified
  tests/unit_tests/artifacts/test_wandb_artifacts.py
Labels: cc-test

#4768 chore(sdk): bump version 0.13.8.dev -> 0.13.9.dev
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#4769 fix(sdk): exercise extra caution when checking if AWS Trainium is available in the system
  wandb/sdk/internal/system/assets/trainium.py
Labels: cc-fix

#4692 test(sdk): add tests for custom SSL certs and disabling SSL
  tests/unit_tests/assets/ssl_certs/README.md
  tests/unit_tests/assets/ssl_certs/cc8b642c.0
  tests/unit_tests/assets/ssl_certs/localhost.crt
  tests/unit_tests/assets/ssl_certs/localhost.key
  tests/unit_tests/conftest.py
  tests/unit_tests/test_ssl.py
  wandb/apis/__init__.py
Labels: cc-test

#4776 fix(sdk): restore 'util.generate_id' for legacy / user code
  wandb/util.py
Labels: cc-fix

#4766 fix(sdk): replace `release` with `abandon` when releasing mailbox handle during init
  wandb/sdk/wandb_init.py
Labels: cc-fix

#4782 chore(sdk): post release 0.13.9 - bump version and update changelog
  CHANGELOG.md
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: changelog-ignore, cc-chore

#4752 fix(launch): Remove underscores from generated job name in kubernetes runner
  tests/unit_tests/assets/launch_k8s_config.yaml
  tests/unit_tests/tests_launch/test_launch_kubernetes.py
  tests/unit_tests_old/tests_launch/test_launch_kubernetes.py
  wandb/sdk/launch/runner/kubernetes.py
  wandb/sdk/launch/utils.py
Labels: cc-fix

#4786 revert(sdk): Revert "strengthen StepUpload tests; make exception-handling more thorough in upload/commit (#4677)"
  tests/unit_tests/artifacts/test_artifact_saver.py
  tests/unit_tests/test_step_upload.py
  wandb/filesync/step_checksum.py
  wandb/filesync/step_upload.py
  wandb/filesync/upload_job.py
  wandb/sdk/internal/artifacts.py
  wandb/sdk/internal/file_pusher.py
Labels: cc-revert

#4787 test(sdk): fix nightly docker builds
  .circleci/config.yml
  tests/unit_tests/test_system_monitor.py
Labels: cc-test

#4797 chore(sdk): dont create universal py2/py3 package
  setup.cfg
Labels: cc-chore

#4799 chore(sdk): fix flake8-bugbear B028 and ignore B017
  tests/unit_tests/test_internal_api.py
  tests/unit_tests/test_require_helpers.py
  tests/unit_tests/test_wandb.py
  tools/check-protobuf-version-compatibility.py
  tools/circleci-tool.py
  wandb/apis/public.py
  wandb/apis/reports/_helpers.py
  wandb/apis/reports/report.py
  wandb/cli/cli.py
  wandb/docker/auth.py
  wandb/integration/tensorboard/log.py
  wandb/sdk/internal/sender.py
  wandb/sdk/lib/_wburls_generate.py
  wandb/sdk/lib/config_util.py
  wandb/sdk/lib/preinit.py
  wandb/sdk/lib/printer.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_config.py
  wandb/sdk/wandb_require_helpers.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
  wandb/util.py
Labels: cc-chore

#4802 test(sdk): fix gcloud sdk version requested in nightly tests
  .circleci/config.yml
Labels: cc-test

#4678 chore(artifacts): remove unused parameters in StorageHandler.load_{path,file,reference}
  tests/unit_tests/artifacts/test_wandb_artifacts.py
  tests/unit_tests/artifacts/test_wandb_artifacts_cache.py
  wandb/apis/public.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-chore

#4814 test(sdk): address fixture server move from port 9010 to 9015 in local-testcontainer
  tests/pytest_tests/system_tests/conftest.py
Labels: cc-test

#4728 fix(sweeps): sweep command args can once again be int type
  wandb/wandb_agent.py
Labels: cc-fix

#4813 chore(sdk): add aliases to ac query response
  tests/pytest_tests/unit_tests_old/utils/mock_server.py
Labels: cc-chore

#4788 test(sdk): run regression suite nightly
  .circleci/config.yml
  tools/circleci-tool.py
  tools/coverage-tool.py
  tox.ini
Labels: cc-test

#4823 test(sdk): fix broken lightning test
  tests/functional_tests/t0_main/lightning/t0_strategy_ddp.yea
Labels: cc-test

#4784 chore(sdk): enable type checking for wandb_init.py
  mypy.ini
  wandb/integration/sagemaker/config.py
  wandb/sdk/lib/printer.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_setup.py
Labels: cc-chore

#4775 refactor(artifacts): Refactor Artifact query to fetch entity and project
  tests/pytest_tests/system_tests/test_public_api.py
  wandb/apis/public.py
Labels: cc-refactor

#4801 chore(launch): deprecate defaulting to default queue in launch-agent command
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/cli/cli.py
  wandb/sdk/launch/launch.py
Labels: cc-chore

#4800 test(launch): Add unit test for kubernetes runner with annotations
  tests/pytest_tests/system_tests/tests_launch/test_launch_kubernetes.py
Labels: cc-test

#4809 feat(artifacts): get aliases list for artifact collections
  tox.ini
  wandb/apis/public.py
Labels: cc-feat

#4831 test(integrations): fix train_gpu_ddp test
  tests/functional_tests/t0_main/lightning/train_gpu_ddp.yea
Labels: cc-test

#4838 chore(sdk): fix docker testimage to pull amd64 version
  tests/pytest_tests/system_tests/conftest.py
Labels: cc-chore

#4843 chore(sdk): fix codeowners after test restructure
  .github/CODEOWNERS
Labels: cc-chore

#4841 refactor(sdk): replace more communicate calls with deliver
  tests/pytest_tests/unit_tests/test_lib/test_run_messages.py
  tests/pytest_tests/unit_tests/test_lib/test_run_status.py
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_grpc.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/sender.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
Labels: cc-refactor

#4840 fix(sdk): fix md5 test failures on Windows
  tests/pytest_tests/unit_tests/test_lib/test_hashutil.py
Labels: cc-fix

#4837 chore(sdk): split out relay server so it can be shared with yea-wandb
  mypy.ini
  requirements_dev.txt
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/unit_tests/test_metaflow.py
  tox.ini
  wandb/testing/relay.py
Labels: cc-chore

#4806 chore(sdk): fix a flake8 complaint in a test
  tests/pytest_tests/unit_tests/test_internal_api.py
Labels: cc-chore

#4849 test(integrations): fix several import tests
  tests/functional_tests/t0_main/imports/09-batch9-requirements.txt
  tests/functional_tests/t0_main/imports/12-batch12-requirements.txt
Labels: cc-test

#4828 fix(artifacts): ensure prepared artifacts have the `latest` alias
  tests/pytest_tests/unit_tests/test_util.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-fix

#4851 feat(launch): Include username of run author in environment variables
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  wandb/sdk/launch/builder/build.py
Labels: cc-feat

#4846 feat(launch): Support local-container resource args
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_docker.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_kubernetes.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_local_process.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/abstract.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker.py
  wandb/sdk/launch/builder/kaniko.py
  wandb/sdk/launch/builder/noop.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/runner/aws.py
  wandb/sdk/launch/runner/gcp_vertex.py
  wandb/sdk/launch/runner/kubernetes.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#4847 test(sdk): don't use symlinks for SSL test assets, because Windows
  tests/pytest_tests/assets/ssl_certs/README.md
  tests/pytest_tests/assets/ssl_certs/cc8b642c.0
  tests/pytest_tests/assets/ssl_certs/localhost.crt
  tests/pytest_tests/unit_tests/test_ssl.py
Labels: cc-test

#4855 test(sdk): add unit tests for filesync.Stats
  tests/pytest_tests/unit_tests/test_file_stats.py
Labels: cc-test

#4738 chore(sdk): add async retry logic
  tests/pytest_tests/unit_tests/test_retry.py
  wandb/sdk/lib/retry.py
Labels: cc-chore

#4808 test(artifacts): strengthen tests for ArtifactSaver, StepUpload
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_saver.py
  tests/pytest_tests/unit_tests/test_step_upload.py
Labels: cc-test

#4868 fix(artifacts): catch FileNotFoundError and PermissionError during cache.cleanup()
  wandb/sdk/interface/artifacts.py
Labels: cc-fix

#4861 chore(launch): Agent logs full stack trace when catching exception
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#4839 fix(sdk): fix order of python executable resolves
  .circleci/config.yml
  tests/standalone_tests/executor_tests/executor-gunicorn.sh
  tests/standalone_tests/executor_tests/executor-pex.sh
  tests/standalone_tests/executor_tests/executor-uwsgi.sh
  tests/standalone_tests/executor_tests/flask_app.py
  tox.ini
  wandb/errors/__init__.py
  wandb/sdk/service/service.py
  wandb/sdk/wandb_settings.py
  wandb/util.py
Labels: cc-fix

#4835 chore(sdk): swallow warning printed by neuron-ls
  wandb/sdk/internal/system/assets/trainium.py
Labels: cc-chore

#4859 refactor(artifacts): internally use Future to communicate success/failure of commit, not threading.Event
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_saver.py
  tests/pytest_tests/unit_tests/test_step_upload.py
  wandb/filesync/step_checksum.py
  wandb/filesync/step_upload.py
  wandb/filesync/upload_job.py
  wandb/sdk/internal/artifacts.py
  wandb/sdk/internal/file_pusher.py
Labels: cc-refactor

#4877 fix(sdk): fix console handling when forking and setting stdout==stderr
  tests/functional_tests/t0_main/console/t4_fork_wrap.py
  tests/functional_tests/t0_main/console/t4_fork_wrap.yea
  tests/standalone_tests/executor_tests/flask_app.py
  wandb/sdk/lib/redirect.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#4871 build(sdk): pin pip and tox in development environments
  tools/setup_dev_environment.py
Labels: cc-build
