Repository wandb/wandb, pull requests merged in 2023-08, with the labels that each got.

#5645 chore(sdk): bump default API timeouts
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
Labels: cc-chore

#5705 test(sdk): use universal wheels in toxenvs
  tox.ini
Labels: cc-test

#5099 test(sdk): add ability to profile memory usage of wandb-service with memray
  tools/cli.py
  wandb/sdk/service/service.py
Labels: cc-test

#5964 chore(sdk): clean up setup files
  pyproject.toml
  requirements_build.txt
  requirements_sweeps.txt
  setup.cfg
  setup.py
Labels: cc-chore

#5986 chore(sdk): bump next dev version 0.15.9.dev1
  CHANGELOG.md
  setup.cfg
  wandb/__init__.py
Labels: cc-chore

#5993 chore(sweeps): catch set state error and remove cling api
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  wandb/cli/cli.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#5923 fix(launch): Extend try in agent loop to cover all job handling
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#5996 chore(launch): Add job CLI ref docs
  wandb/cli/cli.py
Labels: cc-chore

#5997 fix(sdk): guard against undefined filestream timeout
  wandb/sdk/internal/file_stream.py
Labels: cc-fix

#5959 fix(launch): error if code artifact underlying job has been deleted
  wandb/apis/public.py
Labels: cc-fix

#5998 chore(sweeps): sweeps that hit runcap are completed not paused
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#6001 docs(sdk): Bump docugen version
  .github/workflows/generate-docodile-documentation.yml
Labels: cc-docs

#5901 chore(sweeps): resume sweeps from the cli
  wandb/sdk/internal/internal_api.py
Labels: cc-chore

#5929 fix(artifacts): use a unique name for the artifact created by `verify`
  wandb/sdk/verify/verify.py
Labels: cc-fix

#6004 chore(artifacts): disable multiple writer safe_copy test on windows
  tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
Labels: cc-chore

#6002 fix(launch): Use resume=allow when auto requeuing
  wandb/sdk/launch/builder/build.py
Labels: cc-fix

#5903 fix(launch): correct entrypoint path from disabled git repo subir
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/system/system_info.py
  wandb/sdk/launch/create_job.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#6006 docs(sdk): Bump docugen version
  .github/workflows/generate-docodile-documentation.yml
Labels: cc-docs

#6016 chore(sdk): sync protobuf changes from wandb/nexus
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/proto/wandb_telemetry.proto
Labels: cc-chore

#5985 fix(sweeps): override individual job resource_args
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-fix

#6017 revert(sdk): reverts dropping the support for python 3.6
  pyproject.toml
  tests/pytest_tests/conftest.py
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  tests/pytest_tests/unit_tests_old/conftest.py
  tox.ini
  wandb/sdk/lib/_settings_toposort_generate.py
  wandb/sdk/wandb_settings.py
Labels: cc-revert

#6018 fix(sdk): fix import issue to support python 3.6
  wandb/sdk/interface/interface.py
Labels: cc-fix

#6026 chore(sdk): apply lint fixes for ruff 0.0.283
  .github/workflows/pre-commit.yml
  nexus/setup.py
  nexus/wandb_core/__init__.py
  tests/pytest_tests/unit_tests/test_cli.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests_old/test_offline_sync.py
  wandb/data_types.py
  wandb/docker/auth.py
  wandb/integration/kfp/kfp_patch.py
  wandb/integration/kfp/wandb_logging.py
  wandb/sdk/integration_utils/data_logging.py
  wandb/sdk/launch/launch.py
  wandb/sdk/wandb_config.py
Labels: cc-chore

#6027 chore(sdk): bump nexus version for alpha 0.0.1a3 release
  nexus/pkg/server/sender.go
  nexus/setup.py
Labels: cc-chore

#6028 chore(sdk): add precommit hooks for git push
  .github/ISSUE_TEMPLATE/old/client-bug.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  requirements_test.txt
  setup.cfg
  tools/wandb_export_history.py
  wandb/integration/yolov8/yolov8.py
  wandb/sdk/lib/fsm.py
Labels: cc-chore

#6033 fix(launch): Fix override entrypoint when using sweeps on launch without a scheduler job
  wandb/sdk/launch/runner/local_process.py
Labels: cc-fix

#6037 chore(sdk): add nexus scope
  .github/workflows/check-pr-title.yml
Labels: cc-chore

#6031 chore(launch): Remove threadpool in launch agent
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#5966 chore(launch): don't fill resource args macros in place
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/unit_tests/test_launch/test_project/test_project.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/runner/vertex_runner.py
Labels: cc-chore

#6041 chore(nexus): reorganize filestream into a package
  nexus/pkg/filestream/filestream.go
  nexus/pkg/filestream/filestream_test.go
  nexus/pkg/filestream/loop_feedback.go
  nexus/pkg/filestream/loop_process.go
  nexus/pkg/filestream/loop_transmit.go
  nexus/pkg/server/clients.go
  nexus/pkg/server/filestream.go
  nexus/pkg/server/sender.go
Labels: cc-chore

#6048 refactor(artifacts): move staging logic to separate file
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/artifacts/staging.py
Labels: cc-refactor

#5859 feat(artifacts): set ttl(time to live) for artifact versions
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/unit_tests/test_library_public.py
  tests/pytest_tests/unit_tests_old/utils/mock_server.py
  tox.ini
  wandb/__init__.py
  wandb/apis/public.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/artifacts/artifact_ttl.py
  wandb/sdk/interface/interface.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/sender.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#6050 chore(artifacts): small improvements for server side not incompatible situations for Artifact TTL
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/internal/internal_api.py
Labels: cc-chore

#6051 chore(artifacts): artifact ttl older server check for ttldurationseconds
  wandb/sdk/internal/internal_api.py
Labels: cc-chore

#6053 chore(artifacts): edit check for termwarn to covers more artifact ttl older scenarios
  wandb/sdk/artifacts/artifact.py
Labels: cc-chore

#6055 fix(nexus): fix resume reference when nil
  nexus/pkg/server/resume.go
  nexus/pkg/server/sender.go
Labels: cc-fix

#6054 ci(nexus): add basic ci testing for nexus
  .circleci/config.yml
  .codecov.yml
  nexus/pkg/server/handler.go
  tox.ini
Labels: cc-ci

#6032 fix(sdk): further speed up import time
  wandb/sdk/lib/ipython.py
Labels: cc-fix

#6036 feat(nexus): add support for define metric
  nexus/cmd/test/trie.go
  nexus/internal/nexuslib/protolib.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/history.go
  nexus/pkg/server/metric.go
  nexus/pkg/server/sender.go
Labels: cc-feat

#6056 ci(sdk): fix codecov-check bug
  .codecov.yml
Labels: cc-ci

#6060 chore(sdk): update yea-wandb version
  tests/pytest_tests/unit_tests_old/utils/artifact_emu.py
  tests/pytest_tests/unit_tests_old/utils/mock_server.py
  tox.ini
Labels: cc-chore

#6047 chore(nexus): improve chunking of filestream
  .circleci/config.yml
  .codecov.yml
  nexus/internal/clienttest/clienttest.go
  nexus/internal/clienttest/clienttest_gen.go
  nexus/internal/clienttest/generate.go
  nexus/pkg/filestream/collector.go
  nexus/pkg/filestream/collector_test.go
  nexus/pkg/filestream/filestream.go
  nexus/pkg/filestream/filestream_test.go
  nexus/pkg/filestream/loop_process.go
  nexus/pkg/filestream/loop_transmit.go
  nexus/pkg/filestream/loop_transmit_test.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/resume.go
  nexus/pkg/server/sender.go
  tools/coverage-tool.py
Labels: cc-chore

#6061 docs(nexus): add package level docstrings for filestream
  nexus/pkg/filestream/filestream.go
Labels: cc-docs

#6057 fix(launch): Fix sample kubernetes agent manifest secret mount
  wandb/sdk/launch/deploys/kubernetes/launch-agent.yaml
Labels: cc-fix

#5970 feat(launch): Include agent version when creating launch agent
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tools/build_launch_agent.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-feat

#6069 chore(nexus): update to go 1.21
  .circleci/config.yml
  .github/workflows/pre-commit.yml
  nexus/cmd/nexus/main.go
  nexus/go.mod
  nexus/go.sum
  nexus/internal/uploader/uploader.go
  nexus/pkg/filestream/loop_transmit_test.go
  nexus/pkg/observability/logging.go
  nexus/pkg/observability/sentry.go
  nexus/pkg/server/clients.go
  nexus/pkg/server/connection.go
  nexus/pkg/server/lib.go
  nexus/pkg/server/logging.go
  nexus/pkg/server/server.go
  nexus/pkg/server/stream_mux.go
  nexus/pkg/server/tokenizer.go
  nexus/pkg/server/util.go
  nexus/scripts/update-dev-env.txt
Labels: cc-chore

#6063 chore(artifacts): get length from ArtifactManifest
  tests/pytest_tests/unit_tests/test_wandb_artifacts.py
  wandb/sdk/artifacts/artifact_manifest.py
Labels: cc-chore

#6080 ci(sdk): fix broken win tests
  .circleci/config.yml
Labels: cc-ci

#6070 test(artifacts): make general-purpose artifacts test fixtures more available
  tests/pytest_tests/conftest.py
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/unit_tests/test_artifacts/conftest.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_internal_api.py
Labels: cc-test

#6019 feat(artifacts): retrieve the parent collection from an Artifact
  tests/pytest_tests/system_tests/test_artifacts/conftest.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-feat

#6052 feat(nexus): improve file uploads
  .pre-commit-config.yaml
  nexus/go.mod
  nexus/internal/uploader/rlimit.go
  nexus/internal/uploader/rlimit_win.go
  nexus/internal/uploader/upload_manager.go
  nexus/internal/uploader/upload_task.go
  nexus/internal/uploader/uploader.go
  nexus/internal/uploader/uploader_default.go
  nexus/pkg/artifacts/artifacts.go
  nexus/pkg/server/sender.go
Labels: cc-feat

#6082 chore(nexus): remove a print statement in rlimit.go
  nexus/internal/uploader/rlimit.go
Labels: cc-chore

#6085 fix(nexus): rm unused import
  nexus/internal/uploader/rlimit.go
Labels: cc-fix

#6022 fix(launch): watch to get kuberntes run statuses
  tests/pytest_tests/unit_tests/test_launch/conftest.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_kubernetes.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#6064 refactor(artifacts): add convenience function _ensure_logged
  wandb/sdk/artifacts/artifact.py
Labels: cc-refactor

#6074 feat(artifacts): Add run id option to artifact put method to log artifacts to existing runs
  wandb/cli/cli.py
Labels: cc-feat

#6062 fix(artifacts): copy parent source project info to new draft artifact
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#6042 fix(artifacts): prohibit saving artifacts to a different project than their base artifact
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#6034 fix(artifacts): require existing artifacts to save to their source entity/project
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#6087 fix(nexus): adjust system monitor start and stop functionality
  nexus/pkg/filestream/collector.go
  nexus/pkg/filestream/filestream.go
  nexus/pkg/monitor/monitor.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/history.go
  wandb/sdk/internal/handler.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#6098 chore(nexus): fix dev script which doesnt work with bash
  nexus/scripts/setup-nexus-path.sh
Labels: cc-chore

#6097 chore(nexus): remove accidental checkin of trie test code
  nexus/cmd/test/trie.go
Labels: cc-chore

#6100 feat(public-api): add metadata property to Run object
  nexus/pkg/server/handler.go
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  wandb/apis/public.py
  wandb/util.py
Labels: cc-feat

#6076 chore(nexus): add a preliminary go client library and C bindings
  nexus/cmd/benchmark/main.go
  nexus/cmd/examples/embed/.gitignore
  nexus/cmd/examples/embed/embed-nexus.bin
  nexus/cmd/examples/embed/main.go
  nexus/internal/execbin/execbin.go
  nexus/internal/execbin/forkexec_linux.go
  nexus/internal/execbin/forkexec_notlinux.go
  nexus/internal/launcher/launcher.go
  nexus/internal/shared/headfoot.go
  nexus/internal/shared/shared.go
  nexus/internal/shared/shortid.go
  nexus/internal/shared/shortid_test.go
  nexus/lib/.gitignore
  nexus/lib/build.sh
  nexus/lib/clib/libwandb.c
  nexus/lib/clib/libwandb.h
  nexus/lib/examples/train.c
  nexus/lib/wandbcore/.gitignore
  nexus/lib/wandbcore/embed-nexus.bin
  nexus/lib/wandbcore/generate.go
  nexus/lib/wandbcore/runkeeper.go
  nexus/lib/wandbcore/wandbcore.go
  nexus/pkg/gowandb/connection.go
  nexus/pkg/gowandb/gowandb.go
  nexus/pkg/gowandb/initrun.go
  nexus/pkg/gowandb/mailbox.go
  nexus/pkg/gowandb/manager.go
  nexus/pkg/gowandb/opts/opts.go
  nexus/pkg/gowandb/opts/session/opts.go
  nexus/pkg/gowandb/run.go
  nexus/pkg/gowandb/session.go
  nexus/pkg/gowandb/settings.go
  nexus/pkg/lib/libwb_js.go
  nexus/pkg/lib/libwbnexus.go
  nexus/pkg/server/connection.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/lib.go
  nexus/pkg/server/stream.go
  nexus/pkg/server/tokenizer.go
  nexus/pkg/server/util.go
Labels: cc-chore

#6102 style(sdk): fix to new ruff rule E721 additions
  wandb/data_types.py
  wandb/sdk/internal/sender.py
Labels: cc-style

#6095 fix(launch): Default log_code exclusion behavior now correctly handles `wandb` in the root path prefix.
  tests/pytest_tests/unit_tests/test_lib/test_filenames.py
  wandb/sdk/lib/filenames.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#6011 fix(launch): disallow project queue creation
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
Labels: cc-fix

#6104 feat(launch): Support setting a custom Dockerfile in launch overrides
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-feat

#6091 fix(launch): catch all sweep set state errors
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#6081 feat(nexus): add Nvidia GPU asset to system monitor
  nexus/cmd/nexus/main.go
  nexus/go.mod
  nexus/go.sum
  nexus/pkg/monitor/cpu.go
  nexus/pkg/monitor/disk.go
  nexus/pkg/monitor/gpu_nvidia.go
  nexus/pkg/monitor/memory.go
  nexus/pkg/monitor/monitor.go
  nexus/pkg/monitor/network.go
  nexus/pkg/monitor/noop.go
  nexus/setup.py
Labels: cc-feat

#6117 test(artifacts): fix directory fallback on Windows
  wandb/sdk/lib/filesystem.py
Labels: cc-test

#6119 docs(nexus): add basic developer guide
  nexus/docs/contributing.md
Labels: cc-docs

#6068 fix(launch): create_job now works from jupyter notebook
  tests/pytest_tests/unit_tests/test_job_builder.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/launch/create_job.py
Labels: cc-fix

#6020 feat(artifacts): enable deleting artifact collections from SDK
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  wandb/apis/public.py
Labels: cc-feat

#6125 fix(nexus): fix race condition for defer and update control
  nexus/pkg/server/handler.go
  nexus/pkg/server/writer.go
Labels: cc-fix

#6086 fix(sdk): improved handling and logging of tensor types
  wandb/wandb_torch.py
Labels: cc-fix

#6126 refactor(nexus): move nil checks to the structs methods
  nexus/internal/uploader/upload_manager.go
  nexus/pkg/filestream/filestream.go
  nexus/pkg/monitor/monitor.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
Labels: cc-refactor

#6110 test(integrations): fix cohere llm test by adding safer language to prevent Usage Violations
  tests/functional_tests/t0_main/cohere/t2_cohere_chat.py
  tests/functional_tests/t0_main/cohere/t3_cohere_chat_with_history.py
Labels: cc-test

#6112 feat(sweeps): launch sweep schedulers to team queues from UI
  wandb/sdk/internal/internal_api.py
Labels: cc-feat

#6071 chore(artifacts): add informative error and clean up when cache runs out of disk space
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/artifacts/artifacts_cache.py
  wandb/util.py
Labels: cc-chore

#6067 test(artifacts): ensure unlogged Artifacts can't access invalid properties
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-test

#6122 feat(launch): Add dockerfile CLI param & use Dockerfile.wandb by default if present
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_docker.py
  wandb/cli/cli.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/build.py
Labels: cc-feat

#6127 chore(nexus): fix output timestamps and alert duration
  nexus/api/graphql/genqlient.yaml
  nexus/internal/gql/gql_gen.go
  nexus/pkg/server/sender.go
  tests/pytest_tests/unit_tests_old/utils/mock_server.py
  tox.ini
Labels: cc-chore

#6078 fix(launch): launch cli command should exit with non-zero status if underlying launched run exits with non-zero status
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/cli/cli.py
Labels: cc-fix

#6133 chore(artifacts): ignore PermissionError when removing temp cache files
  wandb/sdk/artifacts/artifacts_cache.py
Labels: cc-chore

#6135 chore(sdk): gitignore the .wandb run directory
  .gitignore
Labels: cc-chore

#6124 refactor(artifacts): move Artifact retrieval out of ArtifactManifestEntry
  tests/pytest_tests/unit_tests/test_saved_model.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
Labels: cc-refactor

#6088 feat(launch): make vertex launcher more customizable
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_gcp.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_vertex.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_gcp.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/environment/gcp_environment.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/loader.py
  wandb/sdk/launch/runner/vertex_runner.py
Labels: cc-feat

#6134 fix(sdk): avoid error at end of run with bigints
  tests/pytest_tests/unit_tests/test_handler.py
  wandb/sdk/internal/handler.py
Labels: cc-fix

#6101 refactor(nexus): minor clean up of the stream
  nexus/pkg/server/handler.go
  nexus/pkg/server/responder.go
  nexus/pkg/server/resume.go
  nexus/pkg/server/sender.go
  nexus/pkg/server/sender_test.go
  nexus/pkg/server/stream.go
  nexus/pkg/server/writer.go
Labels: cc-refactor

#6148 fix(launch): manually created image jobs can rerun correctly
  wandb/sdk/interface/interface.py
Labels: cc-fix

#6150 chore(nexus): remove system metric extra channel
  nexus/pkg/monitor/monitor.go
  nexus/pkg/server/handler.go
Labels: cc-chore

#6151 test(public-api): mark test_run_metadata as xfail
  tests/pytest_tests/system_tests/test_core/test_public_api.py
Labels: cc-test

#6153 refactor(artifacts): simplify artifact saver
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/create_job.py
Labels: cc-refactor

#6156 chore(nexus): consolidate wandb/proto and nexus protobuf
  nexus/api/proto/wandb_base.proto
  nexus/api/proto/wandb_internal.proto
  nexus/api/proto/wandb_server.proto
  nexus/api/proto/wandb_settings.proto
  nexus/api/proto/wandb_telemetry.proto
  nexus/pkg/service/wandb_base.pb.go
  nexus/pkg/service/wandb_internal.pb.go
  nexus/pkg/service/wandb_server.pb.go
  nexus/pkg/service/wandb_settings.pb.go
  nexus/pkg/service/wandb_telemetry.pb.go
  nexus/scripts/generate-proto.sh
  nexus/scripts/update-dev-env.sh
Labels: cc-chore

#6161 chore(artifacts): remove unused S3StoragePolicy
  wandb/sdk/artifacts/storage_policies/s3_bucket_policy.py
Labels: cc-chore

#6141 refactor(sdk): remove support for grpc interface
  .circleci/config.yml
  .codecov.yml
  .coveragerc
  .gitattributes
  docs/dev/diagrams.md
  docs/dev/service-artifact.md
  docs/dev/wandb-service.md
  nexus/cmd/nexus/main.go
  nexus/pkg/service/wandb_server.pb.go
  pyproject.toml
  tests/functional_tests/t0_main/grpc/t1_simple.py
  tests/functional_tests/t0_main/grpc/t1_simple.yea
  tests/functional_tests/t0_main/grpc/t2_mp_log_image_sequence.py
  tests/functional_tests/t0_main/grpc/t2_mp_log_image_sequence.yea
  tests/functional_tests/t0_main/grpc/t3_use_artifact.py
  tests/functional_tests/t0_main/grpc/t3_use_artifact.yea
  tests/functional_tests/t0_main/grpc/t4_status.py
  tests/functional_tests/t0_main/grpc/t4_status.yea
  tests/standalone_tests/grpc_client.py
  tests/standalone_tests/grpc_server_test.sh
  tox.ini
  wandb/cli/cli.py
  wandb/proto/v3/wandb_server_pb2.py
  wandb/proto/v3/wandb_server_pb2_grpc.py
  wandb/proto/v3/wandb_server_pb2_grpc.pyi
  wandb/proto/v4/wandb_server_pb2.py
  wandb/proto/v4/wandb_server_pb2_grpc.py
  wandb/proto/v4/wandb_server_pb2_grpc.pyi
  wandb/proto/wandb_internal_codegen.py
  wandb/proto/wandb_server.proto
  wandb/proto/wandb_server_pb2_grpc.py
  wandb/sdk/backend/backend.py
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_grpc.py
  wandb/sdk/service/port_file.py
  wandb/sdk/service/server.py
  wandb/sdk/service/server_grpc.py
  wandb/sdk/service/service.py
  wandb/sdk/service/service_base.py
  wandb/sdk/service/service_grpc.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_manager.py
  wandb/sdk/wandb_run.py
Labels: cc-refactor

#6152 feat(artifacts): extend cache cleanup to allow specifying a target fraction
  wandb/sdk/artifacts/artifacts_cache.py
Labels: cc-feat

#6140 refactor(artifacts): remove explicit dependency on WandbStoragePolicy
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_manifest.py
  wandb/sdk/artifacts/artifact_manifests/artifact_manifest_v1.py
  wandb/sdk/artifacts/storage_policies/__init__.py
  wandb/sdk/artifacts/storage_policies/register.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
  wandb/sdk/artifacts/storage_policy.py
Labels: cc-refactor

#6138 chore(artifacts): consolidate LinkArtifact calls
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-chore

#6162 chore(artifacts): remove legacy messages from proto
  nexus/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/sender.py
Labels: cc-chore

#6163 refactor(sdk): remove communicate function on the interface
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_core/test_sender.py
  tests/pytest_tests/unit_tests_old/conftest.py
  tests/pytest_tests/unit_tests_old/test_sender.py
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/interface/interface_sock.py
Labels: cc-refactor

#6147 test(artifacts): test for ignoring missing files during cleanup (Windows fix)
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/artifacts/artifacts_cache.py
Labels: cc-test

#6144 fix(integrations): fix wandb ultralytics callback activation
  wandb/integration/ultralytics/callback.py
Labels: cc-fix

#6157 test(artifacts): add a benchmark for ArtifactsCache.cleanup
  tests/standalone_tests/benchmark_cache_cleanup.py
Labels: cc-test

#6132 feat(artifacts): add an eval-able repr to ArtifactManifestEntry
  tests/pytest_tests/unit_tests/test_artifacts/test_artifact_manifest_entry.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
Labels: cc-feat

#6165 chore(sdk): add back missing utils from importer revert
  wandb/util.py
Labels: cc-chore

#6166 fix(nexus): fix correctness for offline mode
  nexus/internal/uploader/upload_manager.go
  nexus/pkg/server/handler.go
  tests/pytest_tests/system_tests/test_nexus/test_nexus.py
Labels: cc-fix

#6118 feat(nexus): enable docker-based wheel building for nexus
  nexus/docs/contributing.md
  nexus/scripts/build/Dockerfile
  nexus/setup.py
  noxfile.py
  requirements_build.txt
  tools/build_install_nexus
  tox.ini
Labels: cc-feat

#6167 fix(sdk): reports api - fix media_keys json path
  wandb/apis/reports/_panels.py
Labels: cc-fix

#6131 feat(nexus): add Nvidia GPU asset to system monitor
  nexus/cmd/nexus/main.go
  nexus/go.mod
  nexus/go.sum
  nexus/pkg/monitor/cpu.go
  nexus/pkg/monitor/disk.go
  nexus/pkg/monitor/gpu_nvidia.go
  nexus/pkg/monitor/memory.go
  nexus/pkg/monitor/monitor.go
  nexus/pkg/monitor/network.go
  nexus/pkg/monitor/noop.go
Labels: cc-feat

#6154 refactor(artifacts): delay directory creation until write will occur
  wandb/sdk/artifacts/artifacts_cache.py
Labels: cc-refactor

#6149 feat(artifacts): clear the cache on add to prevent overflow
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/artifacts/artifacts_cache.py
Labels: cc-feat

#6106 feat(sdk): capture disk i/o utilization in system metrics
  tests/pytest_tests/unit_tests/test_system_metrics/test_disk.py
  wandb/sdk/internal/system/assets/disk.py
Labels: cc-feat

#6137 feat(launch): default to noop builder if docker not installed
  wandb/docker/__init__.py
  wandb/sdk/launch/loader.py
Labels: cc-feat

#6043 fix(sdk): Allow uint8 images to be logged as wandb.Image()
  tests/pytest_tests/unit_tests/test_data_types.py
  wandb/sdk/data_types/image.py
Labels: cc-fix

#6105 chore(nexus): add prototype c++ implementation
  nexus/cmd/benchmark/main.go
  nexus/cmd/examples/embed/main.go
  nexus/lang/.gitignore
  nexus/lang/build.sh
  nexus/lang/c/examples/train.c
  nexus/lang/c/lib/libwandb.c
  nexus/lang/c/lib/libwandb.h
  nexus/lang/core/.gitignore
  nexus/lang/core/embed-nexus.bin
  nexus/lang/core/generate.go
  nexus/lang/core/runkeeper.go
  nexus/lang/core/wandbcore.go
  nexus/lang/cpp/examples/train.cpp
  nexus/lang/cpp/lib/libwandb_cpp.cpp
  nexus/lang/cpp/lib/libwandb_cpp.h
  nexus/lib/build.sh
  nexus/pkg/gowandb/gowandb.go
  nexus/pkg/gowandb/run.go
  nexus/pkg/gowandb/settings.go
  nexus/pkg/monitor/gpu_nvidia.go
  nexus/pkg/monitor/noop.go
Labels: cc-chore

#6172 refactor(artifacts): simplify ArtifactsCache with pathlib and tempfile
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/env.py
  wandb/sdk/artifacts/artifacts_cache.py
  wandb/sdk/lib/filesystem.py
Labels: cc-refactor

#6175 fix(sdk): fall back to /tmp/username/.config/wandb in old settings
  wandb/old/settings.py
Labels: cc-fix

#6178 chore(sdk): bump version to 0.15.10.dev1 and update changelog
  CHANGELOG.md
  setup.cfg
  wandb/__init__.py
Labels: cc-chore

#6181 chore(artifacts): copy data directly into file handle rather than getting the file name
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
Labels: cc-chore

#6180 chore(artifacts): manually manage temp file deletion
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/artifacts_cache.py
Labels: cc-chore

#6121 chore(artifacts): add initial support for reflinking on linux and macos
  tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
  wandb/sdk/lib/filesystem.py
Labels: cc-chore

#6187 chore(artifacts): better check of when to warn user of ttl disabling after linking
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/wandb_run.py
Labels: cc-chore

#6158 test(nexus): run all pytest system tests with nexus
  .circleci/config.yml
  nexus/internal/nexuslib/protolib.go
  nexus/pkg/monitor/monitor.go
  nexus/pkg/server/connection.go
  nexus/pkg/server/sender.go
  pyproject.toml
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_core/test_cli_full.py
  tests/pytest_tests/system_tests/test_core/test_data_types_full.py
  tests/pytest_tests/system_tests/test_core/test_file_upload.py
  tests/pytest_tests/system_tests/test_core/test_footer.py
  tests/pytest_tests/system_tests/test_core/test_keras_full.py
  tests/pytest_tests/system_tests/test_core/test_kfp.py
  tests/pytest_tests/system_tests/test_core/test_metric_full.py
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  tests/pytest_tests/system_tests/test_core/test_redir_full.py
  tests/pytest_tests/system_tests/test_core/test_sender.py
  tests/pytest_tests/system_tests/test_core/test_system_info.py
  tests/pytest_tests/system_tests/test_core/test_validation_data_logger.py
  tests/pytest_tests/system_tests/test_core/test_wandb.py
  tests/pytest_tests/system_tests/test_core/test_wandb_integration.py
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
  tests/pytest_tests/system_tests/test_core/test_wandb_tensorflow.py
  tox.ini
  wandb/sdk/internal/handler.py
Labels: cc-test

#6189 chore(sdk): close temp file before saving image
  tests/pytest_tests/unit_tests/test_data_types.py
Labels: cc-chore

#6171 refactor(artifacts): move artifact caching out of file cache
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  wandb/filesync/step_checksum.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_cache.py
  wandb/sdk/artifacts/artifacts_cache.py
  wandb/sdk/artifacts/storage_handlers/wb_local_artifact_handler.py
  wandb/sdk/artifacts/storage_policy.py
  wandb/sdk/internal/file_pusher.py
  wandb/sdk/internal/sender.py
Labels: cc-refactor

#6177 test(artifacts): use real MD5 hashes for ArtifactsCache tests
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
Labels: cc-test

#6129 fix(integrations): fix issue when ultralytics trainer.model is DDP
  wandb/integration/ultralytics/callback.py
Labels: cc-fix

#6196 feat(sdk): make paths for disk usage monitoring configurable
  CONTRIBUTING.md
  nexus/pkg/monitor/disk.go
  nexus/pkg/service/wandb_settings.pb.go
  tests/pytest_tests/unit_tests/test_system_metrics/test_disk.py
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/internal/system/assets/disk.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#6199 test(sdk): pin `anyio` until prefect updates to anyio>=4
  tests/functional_tests/t0_main/prefect_ray/t1_prefect_ray_workflow.yea
Labels: cc-test

#6198 feat(sweeps): Use `WANDB_SWEEP_ID` to include a run in an existing sweep
  tests/pytest_tests/system_tests/test_sweep/test_wandb_sweep.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
  wandb/testing/relay.py
Labels: cc-feat

#6160 feat(artifacts): Handle LinkArtifact calls made to Nexus Core
  nexus/api/graphql/mutation_artifact_link.graphql
  nexus/internal/gql/gql_gen.go
  nexus/internal/nexustest/nexustest.go
  nexus/pkg/artifacts/artifacts.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
  nexus/pkg/server/sender_test.go
Labels: cc-feat

#6190 refactor(artifacts): simplify artifact saver
  tests/pytest_tests/unit_tests_old/test_cli.py
  wandb/cli/cli.py
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/internal/internal_api.py
Labels: cc-refactor

#6182 feat(nexus): fix retry logic for http clients and allow user customization
  nexus/api/graphql/schemas/README.md
  nexus/internal/clients/clients.go
  nexus/internal/uploader/upload_manager.go
  nexus/internal/uploader/uploader_default.go
  nexus/pkg/filestream/filestream_test.go
  nexus/pkg/gowandb/settings.go
  nexus/pkg/server/clients.go
  nexus/pkg/server/sender.go
  nexus/pkg/server/sender_test.go
  nexus/pkg/service/wandb_settings.pb.go
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_core/test_wandb_init.py
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
  wandb/testing/relay.py
Labels: cc-feat

#6207 fix(nexus): use UpsertBucketRetryPolicy in all gql.UpsertBucket calls
  nexus/pkg/server/sender.go
Labels: cc-fix
