Repository wandb/wandb, pull requests merged in 2023-10, with the labels that each got.

#6396 fix(sdk): fix graphql type mapping
  nexus/api/graphql/genqlient.yaml
  nexus/internal/gql/gql_gen.go
Labels: cc-fix

#6238 feat(nexus): expose system metrics in the run object (PoC)
  nexus/pkg/monitor/monitor.go
  nexus/pkg/server/handler.go
  nexus/pkg/service/wandb_internal.pb.go
  nexus/pkg/service/wandb_settings.pb.go
  tests/pytest_tests/system_tests/test_system_metrics/test_system_monitor.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/proto/wandb_settings.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/system/system_monitor.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#6399 fix(sdk): fix concurrency limit in uploader
  nexus/go.mod
  nexus/internal/uploader/rlimit.go
  nexus/internal/uploader/rlimit_win.go
  nexus/internal/uploader/upload_manager.go
Labels: cc-fix

#6400 refactor(sdk): allow uploader to communicate errors back to the caller
  nexus/internal/uploader/upload_manager.go
  nexus/internal/uploader/upload_task.go
  nexus/internal/uploader/uploader_default.go
  nexus/pkg/artifacts/saver.go
Labels: cc-refactor

#6405 ci(sdk): bring ci into a sane state
  .circleci/config.yml
  requirements_dev.txt
  requirements_test.txt
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  tests/pytest_tests/unit_tests/test_docker.py
  tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
  tox.ini
  wandb/__init__.py
  wandb/sdk/lib/config_util.py
Labels: cc-ci

#6391 feat(integrations): Pin ultralytics version support to `v8.0.186`
  wandb/integration/ultralytics/callback.py
Labels: cc-feat

#6408 test(integrations): skip test_tb_watcher_logdir_not_exists on circle'…
  tests/pytest_tests/unit_tests_old/test_tb_watcher.py
Labels: cc-test

#6413 chore(sdk): bump dev version 0.15.13.dev1
  CHANGELOG.md
  setup.cfg
  wandb/__init__.py
Labels: cc-chore

#6414 chore(sdk): fix generate-docodile-documentation.yml
  .github/workflows/generate-docodile-documentation.yml
Labels: cc-chore

#6415 test(integrations): disable obsolete LC tests
  tests/functional_tests/t0_main/langchain/t1_v1.yea
  tests/functional_tests/t0_main/langchain/t2_v1.yea
Labels: cc-test

#6260 fix(sdk): ensures that complete run.config is captured in SageMaker
  tests/pytest_tests/unit_tests/test_sagemaker_config_parse.py
  wandb/integration/sagemaker/config.py
  wandb/sdk/internal/system/assets/gpu_amd.py
Labels: cc-fix

#6410 Improve error handling for gitlib for FileNotFoundErrors
  wandb/sdk/lib/gitlib.py
Labels: contrib

#6397 refactor(sdk): create NilIfZero util
  nexus/pkg/server/resume.go
  nexus/pkg/server/sender.go
  nexus/pkg/utils/utils.go
Labels: cc-refactor

#6398 fix(sdk): increase max message size, handle errors
  nexus/pkg/server/connection.go
Labels: cc-fix

#6417 feat(nexus): add nested config support
  nexus/pkg/server/sender.go
Labels: cc-feat

#6296 feat(nexus): finish artifact saver
  nexus/api/graphql/mutation_artifact.graphql
  nexus/api/graphql/mutation_artifact_commit.graphql
  nexus/api/graphql/mutation_artifact_files.graphql
  nexus/api/graphql/mutation_artifact_manifest.graphql
  nexus/api/graphql/mutation_commit_artifact.graphql
  nexus/api/graphql/mutation_create_artifact.graphql
  nexus/api/graphql/mutation_create_artifact_files.graphql
  nexus/api/graphql/mutation_create_artifact_manifest.graphql
  nexus/api/graphql/mutation_link_artifact.graphql
  nexus/api/graphql/mutation_use_artifact.graphql
  nexus/api/graphql/query_client_id_mapping.graphql
  nexus/internal/gql/gql_gen.go
  nexus/pkg/artifacts/manifest.go
  nexus/pkg/artifacts/saver.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
  nexus/pkg/utils/hash.go
  tests/pytest_tests/system_tests/test_core/test_data_types_full.py
  tests/pytest_tests/system_tests/test_core/test_keras_full.py
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  tests/pytest_tests/system_tests/test_core/test_wandb.py
  wandb/apis/public.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#6416 chore(nexus): release 0.16.0b2
  nexus/README.md
  nexus/internal/version/version.go
  nexus/setup.py
  nexus/wandb_core/__init__.py
  noxfile.py
  pyproject.toml
  wandb/__init__.py
Labels: cc-chore

#6418 fix(launch): Agent better balances multiple queues
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#6429 chore(artifacts): remove dead code
  wandb/sdk/artifacts/storage_handlers/gcs_handler.py
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
Labels: cc-chore

#6371 feat(nexus): add sync file counts in the footer
  docs/README.md
  nexus/internal/uploader/upload_manager.go
  nexus/internal/uploader/upload_task.go
  nexus/pkg/artifacts/saver.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
  nexus/pkg/server/stream.go
  nexus/pkg/server/writer.go
  wandb/sdk/internal/sender.py
Labels: cc-feat

#6430 fix(artifacts): remove versioning enabled check in GCS reference handler
  wandb/sdk/artifacts/storage_handlers/gcs_handler.py
Labels: cc-fix

#6425 test(artifacts): move tests from standalone_tests to system_tests
  tests/pytest_tests/system_tests/test_artifacts/test_misc.py
  tests/pytest_tests/system_tests/test_artifacts/test_object_references.py
  tests/standalone_tests/artifact_tests.yea
Labels: cc-test

#6438 test(artifacts): remove dead code
  tests/pytest_tests/unit_tests_old/test_wandb_artifacts.py
Labels: cc-test

#6440 fix(launch): add google-cloud-aiplatform to launch shard
  pyproject.toml
Labels: cc-fix

#6294 chore(launch): code jobs runtime support handling
  tests/pytest_tests/system_tests/test_launch/test_job.py
  tests/pytest_tests/unit_tests/test_launch/test_create_job.py
  tests/pytest_tests/unit_tests/tests_launch/test_job.py
  tests/pytest_tests/unit_tests_old/test_wandb_run.py
  wandb/sdk/internal/job_builder.py
Labels: cc-chore

#6257 feat(nexus): implement directory watcher and related functionality
  nexus/go.mod
  nexus/go.sum
  nexus/internal/watcher/watcher.go
  nexus/pkg/server/files.go
  nexus/pkg/server/handler.go
  wandb/sdk/wandb_run.py
Labels: cc-feat

#6439 test(artifacts): move tests from unit_tests_old to system_tests
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_artifacts/test_misc2.py
  tests/pytest_tests/system_tests/test_core/test_wandb_init.py
  wandb/testing/relay.py
Labels: cc-test

#6431 test(artifacts): rm abandoned standalone_tests
  tests/standalone_tests/artifact_benchmark.py
  tests/standalone_tests/artifact_load.py
  tests/standalone_tests/artifact_load_30m.sh
  tests/standalone_tests/artifact_load_delete.sh
  tests/standalone_tests/artifact_load_distributed.sh
  tests/standalone_tests/artifact_load_large.sh
  tests/standalone_tests/artifact_load_small.sh
  tests/standalone_tests/artifact_load_small_blocking.sh
  tests/standalone_tests/artifact_references.py
  tests/standalone_tests/artifact_storage.py
  tests/standalone_tests/artifact_table_load.py
  tests/standalone_tests/benchmark_cache_cleanup.py
  tests/standalone_tests/history_step_guardrail_log_artifact.py
  tests/standalone_tests/offline_artifacts.py
Labels: cc-test

#6375 chore(launch): include queue name and run queue item id in run config
  tests/pytest_tests/system_tests/test_launch/test_launch.py
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/system_tests/test_launch/test_launch_local_container.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sagemaker.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  wandb/env.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/wandb_run.py
Labels: cc-chore

#6447 fix(nexus): add use_artifact as passthrough messages
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
  tests/pytest_tests/system_tests/test_core/test_runtime.py
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
Labels: cc-fix

#6436 chore(launch): add more error and warning coverage
  tests/pytest_tests/unit_tests/test_job_builder.py
  tests/pytest_tests/unit_tests_old/conftest.py
  tests/pytest_tests/unit_tests_old/test_tb_watcher.py
  wandb/sdk/internal/job_builder.py
Labels: cc-chore

#6444 chore(nexus): bump version and update readme for 0.16.0b3 release
  .github/pull_request_template.md
  nexus/README.md
  nexus/internal/version/version.go
  nexus/setup.py
  nexus/wandb_core/__init__.py
  noxfile.py
  pyproject.toml
  wandb/__init__.py
Labels: cc-chore

#6463 test(sdk): handle case `HTTPError.response` is `None` for mypy
  wandb/data_types.py
  wandb/integration/sacred/__init__.py
  wandb/sdk/data_types/_dtypes.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/verify/verify.py
  wandb/sync/sync.py
  wandb/util.py
Labels: cc-test

#6443 fix(launch): adjust vertex environment variables
  tests/pytest_tests/system_tests/test_launch/test_launch_vertex.py
  wandb/sdk/launch/runner/vertex_runner.py
Labels: contrib, cc-fix

#6384 feat(launch): run agent on an event loop
  pyproject.toml
  requirements_test.txt
  tests/pytest_tests/system_tests/test_launch/test_job_status_tracker.py
  tests/pytest_tests/system_tests/test_launch/test_launch.py
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/system_tests/test_launch/test_launch_local_container.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sagemaker.py
  tests/pytest_tests/system_tests/test_launch/test_launch_vertex.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_kaniko.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_azure.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_gcp.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_acr.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_ecr.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_gcp_artifact_registry.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_safe_watch.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_vertex.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_aws.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/cli/cli.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/_launch_add.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/agent/job_status_tracker.py
  wandb/sdk/launch/builder/abstract.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/builder/noop.py
  wandb/sdk/launch/environment/abstract.py
  wandb/sdk/launch/environment/aws_environment.py
  wandb/sdk/launch/environment/azure_environment.py
  wandb/sdk/launch/environment/gcp_environment.py
  wandb/sdk/launch/environment/local_environment.py
  wandb/sdk/launch/loader.py
  wandb/sdk/launch/registry/abstract.py
  wandb/sdk/launch/registry/azure_container_registry.py
  wandb/sdk/launch/registry/elastic_container_registry.py
  wandb/sdk/launch/registry/google_artifact_registry.py
  wandb/sdk/launch/registry/local_registry.py
  wandb/sdk/launch/runner/abstract.py
  wandb/sdk/launch/runner/kubernetes_monitor.py
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/runner/local_process.py
  wandb/sdk/launch/runner/sagemaker_runner.py
  wandb/sdk/launch/runner/vertex_runner.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#6437 fix(artifacts): update artifacts cache file permissions for NamedTemporaryFile
  tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
  wandb/sdk/artifacts/artifacts_cache.py
  wandb/sdk/lib/filesystem.py
Labels: cc-fix

#6492 feat(nexus): add sampled history
  nexus/pkg/server/handler.go
  nexus/pkg/server/history.go
Labels: cc-feat

#6491 fix(nexus): fix a number of issues
  .vscode/settings.json
  nexus/pkg/gowandb/mailbox.go
  nexus/pkg/server/files.go
  nexus/pkg/server/tokenizer.go
  nexus/scripts/generate-proto.sh
  tests/functional_tests/t0_main/cohere/t2_cohere_chat.py
  tests/functional_tests/t0_main/cohere/t3_cohere_chat_with_history.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep.py
Labels: cc-fix

#6465 saving mlp figure to buffer and reading with PIL should specify format
  wandb/sdk/data_types/image.py
Labels: contrib

#6495 chore(nexus): track nexus usage
  nexus/pkg/observability/logging.go
  nexus/pkg/server/connection.go
Labels: cc-chore

#6205 feat(artifacts): prototype for models api
  tests/pytest_tests/system_tests/test_core/test_model_workflow.py
  tests/pytest_tests/unit_tests/test_library_public.py
  wandb/__init__.py
  wandb/sdk/lib/module.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#6488 perf(launch): register sweep scheduler virtual agents async
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-perf

#6401 fix(nexus): send content-length, check response status code in uploader
  nexus/internal/uploader/uploader_default.go
  nexus/pkg/server/sender.go
Labels: cc-fix

#6504 chore(sdk): add logging for http errors
  nexus/internal/clients/clients.go
  nexus/internal/clients/clients_test.go
  nexus/pkg/server/sender.go
Labels: cc-chore

#6516 chore(launch): improve launch test flake
  tests/pytest_tests/system_tests/test_launch/test_job_status_tracker.py
Labels: cc-chore

#6517 chore(sdk): format protobuf files
  .clang-format
  .pre-commit-config.yaml
  nexus/pkg/service/wandb_telemetry.pb.go
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/proto/wandb_server.proto
  wandb/proto/wandb_settings.proto
  wandb/proto/wandb_telemetry.proto
Labels: cc-chore

#6509 feat(nexus): make file uploads work with local
  nexus/internal/uploader/upload_manager.go
  nexus/internal/uploader/upload_task.go
  nexus/pkg/filestream/collector.go
  nexus/pkg/filestream/collector_test.go
  nexus/pkg/filestream/filestream.go
  nexus/pkg/filestream/loop_process.go
  nexus/pkg/server/sender.go
  nexus/pkg/service/wandb_internal.pb.go
  wandb/filesync/upload_job.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
Labels: cc-feat

#6513 docs(public-api): Fix suggested command for uploading artifacts
  wandb/apis/public.py
Labels: cc-docs

#6422 feat(sdk): allow users to log custom chart tables in a different section
  wandb/plot/bar.py
  wandb/plot/confusion_matrix.py
  wandb/plot/histogram.py
  wandb/plot/line.py
  wandb/plot/line_series.py
  wandb/plot/pr_curve.py
  wandb/plot/roc_curve.py
  wandb/plot/scatter.py
  wandb/sdk/wandb_run.py
  wandb/viz.py
Labels: cc-feat

#6522 fix(sdk): pin ipython version <8.17.1
  tox.ini
Labels: cc-fix

#6480 fix(sdk): fix step logic when resuming runs with no metrics logged
  wandb/sdk/internal/sender.py
Labels: cc-fix

#6445 feat(nexus): generalize uploader to filemanager to allow downloads
  nexus/internal/filetransfer/file_transfer_default.go
  nexus/internal/filetransfer/file_transfer_default_test.go
  nexus/internal/filetransfer/file_transfer_manager.go
  nexus/internal/filetransfer/tasks.go
  nexus/internal/uploader/upload_manager.go
  nexus/internal/uploader/uploader_default.go
  nexus/pkg/artifacts/saver.go
  nexus/pkg/server/sender.go
  nexus/pkg/service/wandb_settings.pb.go
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#3443 build(sdk): vendor relevant parts of the `pathtools` library
  requirements.txt
  wandb/vendor/watchdog_0_9_0/wandb_watchdog/events.py
  wandb/vendor/watchdog_0_9_0/wandb_watchdog/observers/kqueue.py
  wandb/vendor/watchdog_0_9_0/wandb_watchdog/patterns.py
  wandb/vendor/watchdog_0_9_0/wandb_watchdog/wandb-vendor.md
Labels: cc-build

#6409 test(sdk): add support of python 3.12 + tests
  .circleci/config.yml
  .codecov.yml
  pyproject.toml
  requirements_dev.txt
  tests/pytest_tests/system_tests/test_core/test_keras_full.py
  tests/pytest_tests/system_tests/test_core/test_kfp.py
  tests/pytest_tests/system_tests/test_core/test_torch_full.py
  tests/pytest_tests/system_tests/test_core/test_wandb_tensorflow.py
  tests/pytest_tests/unit_tests/test_data_types.py
  tests/pytest_tests/unit_tests/test_keras.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_safe_watch.py
  tests/pytest_tests/unit_tests/test_lib/test_redir.py
  tests/pytest_tests/unit_tests/test_metaflow.py
  tests/pytest_tests/unit_tests/test_profiler.py
  tests/pytest_tests/unit_tests/test_ssl.py
  tests/pytest_tests/unit_tests/test_torch.py
  tests/pytest_tests/unit_tests/test_util.py
  tests/pytest_tests/unit_tests/tests_launch/test_job.py
  tests/pytest_tests/unit_tests_old/test_keras.py
  tests/pytest_tests/unit_tests_old/test_tb_watcher.py
  tox.ini
  wandb/vendor/graphql-core-1.1/wandb_graphql/language/lexer.py
Labels: cc-test

#6493 feat(sdk): drop python 3.6 support
  pyproject.toml
  tests/pytest_tests/conftest.py
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  tests/pytest_tests/unit_tests_old/conftest.py
  tox.ini
  wandb/sdk/lib/_settings_toposort_generate.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#6528 chore(launch): xfail two broken tests on win
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
Labels: cc-chore

#6527 test(launch): finish run in test_launch_agent_scheduler
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep.py
Labels: cc-test

#6529 feat(artifacts): delete staging files in Nexus
  nexus/pkg/artifacts/saver.go
  nexus/pkg/server/sender.go
  nexus/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/interface/interface.py
Labels: cc-feat

#6530 chore(artifacts): make @wandb/mlw-team own artifacts code
  .github/CODEOWNERS
Labels: cc-chore

#6514 chore(launch): scheduler run not hidden and consistently named
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py
  wandb/cli/cli.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-chore
