Repository wandb/wandb, pull requests merged in 2023-12, with the labels that each got.

#6645 fix(nexus): minor fix up for non server cases
  nexus/pkg/server/sender.go
Labels: cc-fix

#6280 feat(sdk): Adding parameter to image to specify file type jpg, png, bmp, gif
  tests/pytest_tests/unit_tests/test_dtypes.py
  wandb/sdk/data_types/image.py
Labels: cc-feat

#6660 fix(sdk): handle tags when resuming a run
  nexus/api/graphql/query_run_resume_status.graphql
  nexus/internal/gql/gql_gen.go
  nexus/pkg/server/resume.go
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_core/test_resume.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/sender.py
  wandb/sdk/wandb_init.py
Labels: cc-fix

#6662 test(sdk): fix a couple tests broken on win
  tests/functional_tests/t0_main/mp/17-service-crash.yea
  tests/functional_tests/t0_main/mp/20-1-process-pool-executor.yea
  tests/pytest_tests/unit_tests/test_lib/test_redir.py
  tests/pytest_tests/unit_tests/test_wandb_settings_old.py
Labels: cc-test

#6664 test(sdk): fix a few func tests
  .circleci/config.yml
  tests/functional_tests/t0_main/lightning/t0_strategy_ddp.yea
  tests/functional_tests/t0_main/lightning/t1_strategy_ddp_spawn.yea
  tests/functional_tests/t0_main/mp/01-2-simple-no-finish.yea
  tests/functional_tests/t0_main/mp/13-synctb-gradienttape.yea
  tests/functional_tests/t0_main/mp/18-multiple-crash.yea
  tests/functional_tests/t0_main/torch/t1_sparse_tensors.yea
  tests/functional_tests/t0_main/torch/t2_mp_simple.yea
  tests/functional_tests/t0_main/torch/t3_ddp_basic.yea
Labels: cc-test

#6665 chore(sdk): bump version to 0.16.2.dev1 and update changelog
  .bumpversion.wandb.cfg
  CHANGELOG.md
  wandb/__init__.py
Labels: cc-chore

#6667 fix(nexus): update error message and remove extra
  .bumpversion.core.cfg
  pyproject.toml
  wandb/util.py
Labels: cc-fix

#6668 chore(sdk): update mypy to latest
  mypy.ini
  tox.ini
  wandb/apis/importers/base.py
  wandb/apis/importers/mlflow.py
  wandb/docker/auth.py
  wandb/env.py
  wandb/integration/fastai/__init__.py
  wandb/integration/lightgbm/__init__.py
  wandb/integration/xgboost/xgboost.py
  wandb/integration/yolov8/yolov8.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/storage_handlers/wb_local_artifact_handler.py
  wandb/sdk/backend/backend.py
  wandb/sdk/internal/sender.py
  wandb/sdk/launch/_launch_add.py
  wandb/sdk/launch/create_job.py
  wandb/sdk/launch/runner/sagemaker_runner.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/lib/apikey.py
  wandb/sdk/lib/json_util.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-chore

#6674 chore(nexus): fix broken benchmark tool
  nexus/pkg/gowandb/run.go
Labels: cc-chore

#6512 chore(nexus): add artifact builder
  nexus/pkg/artifacts/builder.go
  nexus/pkg/artifacts/builder_test.go
  nexus/pkg/artifacts/manifest.go
  nexus/pkg/utils/files.go
  nexus/pkg/utils/files_test.go
  nexus/pkg/utils/hash.go
  nexus/pkg/utils/hash_test.go
Labels: cc-chore

#6676 chore(sdk): minor clean up of config and gitignore
  .circleci/config.yml
  .gitignore
Labels: cc-chore

#6677 fix(nexus): clean up issues with file sending
  nexus/pkg/server/handler.go
  nexus/pkg/server/responder.go
  nexus/pkg/server/sender.go
Labels: cc-fix

#6684 chore(launch): Fix optionality of prioritization_mode parameter to create_run_queue
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
Labels: cc-chore

#6681 chore(nexus): rename nexus to core
  .bumpversion.core.cfg
  .circleci/config.yml
  .github/workflows/check-pr-title.yml
  nexus/.gitignore
  nexus/README.md
  nexus/cmd/nexus/main.go
  nexus/docs/contributing.md
  nexus/internal/clients/clients.go
  nexus/internal/debounce/debounce.go
  nexus/internal/filetransfer/file_transfer_default.go
  nexus/internal/filetransfer/file_transfer_default_test.go
  nexus/internal/filetransfer/file_transfer_manager.go
  nexus/internal/watcher/watcher.go
  nexus/pkg/artifacts/linker.go
  nexus/pkg/filestream/filestream.go
  nexus/pkg/filestream/filestream_test.go
  nexus/pkg/filestream/loop_transmit_test.go
  nexus/pkg/monitor/monitor.go
  nexus/pkg/observability/logging.go
  nexus/pkg/server/files.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/handler_test.go
  nexus/pkg/server/logging.go
  nexus/pkg/server/responder.go
  nexus/pkg/server/sender.go
  nexus/pkg/server/sender_test.go
  nexus/pkg/server/store.go
  nexus/pkg/server/store_test.go
  nexus/pkg/server/stream.go
  nexus/pkg/server/writer.go
  nexus/setup.py
  nexus/wandb_core/__init__.py
  noxfile.py
  pyproject.toml
  tests/pytest_tests/system_tests/test_artifacts/test_public_api.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/system_tests/test_core/test_cli_full.py
  tests/pytest_tests/system_tests/test_core/test_file_stream_internal.py
  tests/pytest_tests/system_tests/test_core/test_file_upload.py
  tests/pytest_tests/system_tests/test_core/test_footer.py
  tests/pytest_tests/system_tests/test_core/test_keras_full.py
  tests/pytest_tests/system_tests/test_core/test_metric_full.py
  tests/pytest_tests/system_tests/test_core/test_model_workflow.py
  tests/pytest_tests/system_tests/test_core/test_redir_full.py
  tests/pytest_tests/system_tests/test_core/test_sender.py
  tests/pytest_tests/system_tests/test_core/test_system_info.py
  tests/pytest_tests/system_tests/test_core/test_validation_data_logger.py
  tests/pytest_tests/system_tests/test_core/test_wandb_init.py
  tests/pytest_tests/system_tests/test_core/test_wandb_integration.py
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
  tests/pytest_tests/system_tests/test_core/test_wandb_tensorflow.py
  tests/pytest_tests/system_tests/test_notebooks/test_notebooks.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_cli.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_public_api.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_data_types.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_wandb_run.py
  tests/pytest_tests/unit_tests_old/test_core/test_wandb.py
  tox.ini
  wandb/sdk/internal/system/system_monitor.py
  wandb/util.py
Labels: cc-chore

#6626 feat(launch): add registry uri field to builders
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_docker.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_kaniko.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_acr.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_ecr.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_gcp_artifact_registry.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/environment/gcp_environment.py
  wandb/sdk/launch/loader.py
  wandb/sdk/launch/registry/abstract.py
  wandb/sdk/launch/registry/azure_container_registry.py
  wandb/sdk/launch/registry/elastic_container_registry.py
  wandb/sdk/launch/registry/google_artifact_registry.py
  wandb/sdk/launch/registry/local_registry.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#6689 chore(core): release `wandb-core==0.17.0b3`
  .bumpversion.core.cfg
  .circleci/config.yml
  core/README.md
  core/internal/version/version.go
  core/setup.py
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
Labels: cc-chore

#6691 test(core): replace logger with a no-op logger for testing
  core/pkg/filestream/filestream_test.go
  core/pkg/filestream/loop_transmit_test.go
  core/pkg/observability/logging.go
  core/pkg/observability/logging_test.go
  core/pkg/observability/sentry.go
  core/pkg/server/handler_test.go
  core/pkg/server/logging.go
  core/pkg/server/sender_test.go
  core/pkg/server/store_test.go
Labels: cc-test

#6692 chore(core): release wandb-core==0.17.0b4
  .bumpversion.core.cfg
  core/README.md
  core/internal/version/version.go
  core/setup.py
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
Labels: cc-chore

#6695 test(core): check wandb-core compatibility with latest wandb from pypi
  .github/workflows/release-core.yml
Labels: cc-test

#6697 test(core): fix non-determinism in the log message
  core/pkg/observability/logging_test.go
Labels: cc-test

#6696 chore(sdk): move mypy config to pyproject.toml
  mypy.ini
  pyproject.toml
  tox.ini
Labels: cc-chore

#6688 refactor(launch): improved static validation of agent config
  pyproject.toml
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_config.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_cli.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/agent/config.py
  wandb/sdk/launch/environment/aws_environment.py
  wandb/sdk/launch/environment/azure_environment.py
  wandb/sdk/launch/environment/gcp_environment.py
  wandb/sdk/launch/utils.py
Labels: cc-refactor

#6700 chore(core): rename default binary from core to wandb-core
  core/cmd/wandb-core/main.go
  core/pkg/gowandb/session.go
  core/pkg/server/sender.go
  core/setup.py
Labels: cc-chore

#6706 fix(core): add jitter to retry clients' backoff strategy
  core/internal/clients/backoff.go
  core/internal/clients/backoff_test.go
  core/internal/clients/clients.go
  core/internal/clients/clients_test.go
  core/internal/clients/retry_policy_test.go
  core/pkg/server/sender.go
  core/pkg/server/sync.go
  core/pkg/server/sync_test.go
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#6694 fix(artifacts): only skip file download if digest matches
  core/pkg/artifacts/downloader.go
  core/pkg/utils/files.go
  core/pkg/utils/hash.go
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
Labels: cc-fix

#6679 feat(launch): CLI supports allow-listed queue parameters
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#6715 chore(launch): Better check for empty cli template vars
  wandb/cli/cli.py
Labels: cc-chore

#6716 docs(sdk): Corrected description for email field
  wandb/apis/public.py
Labels: cc-docs

#6703 test(artifacts): move tests from unit_tests_old to system_tests
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_cli.py
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_public_api.py
  tests/pytest_tests/system_tests/test_artifacts/test_data_types.py
  tests/pytest_tests/system_tests/test_artifacts/test_public_api.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_run.py
  tests/pytest_tests/system_tests/test_core/test_keras_full.py
  tests/pytest_tests/system_tests/test_core/test_validation_data_logger.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_cli.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_public_api.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_data_types.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_wandb_run.py
  wandb/apis/public.py
  wandb/cli/cli.py
Labels: cc-test

#6714 fix(core): fix resume and add tests
  core/pkg/server/resume.go
  core/pkg/server/resume_test.go
  core/pkg/server/sender.go
Labels: cc-fix

#6712 refactor(core): re-org code so that stream is more clear
  core/pkg/server/connection.go
  core/pkg/server/handler.go
  core/pkg/server/handler_test.go
  core/pkg/server/history.go
  core/pkg/server/metric.go
  core/pkg/server/responder.go
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/summary.go
  core/pkg/server/writer.go
Labels: cc-refactor

#6663 test(integrations): update `pytorch-lightning` to `lightning`
  tests/functional_tests/t0_main/lightning/pl_base.py
  tests/functional_tests/t0_main/lightning/t0_strategy_ddp.py
  tests/functional_tests/t0_main/lightning/t0_strategy_ddp.yea
  tests/functional_tests/t0_main/lightning/t1_strategy_ddp_spawn.py
  tests/functional_tests/t0_main/lightning/t1_strategy_ddp_spawn.yea
  tests/functional_tests/t0_main/lightning/train_gpu_ddp.py
  tests/functional_tests/t0_main/lightning/train_gpu_ddp.yea
  tests/functional_tests/t0_main/lightning/train_tpu_ddp.py
  tests/functional_tests/t0_main/lightning/train_tpu_ddp.yea
Labels: cc-test

#6725 chore(sdk): remove .test_duration file
  .test_durations
Labels: cc-chore

#6730 fix(launch): capture errors from the creation of k8s job from yaml
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#6734 refactor(artifacts): rename cache modules
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_artifacts/conftest.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  wandb/cli/cli.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_file_cache.py
  wandb/sdk/artifacts/artifact_instance_cache.py
  wandb/sdk/artifacts/storage_handlers/azure_handler.py
  wandb/sdk/artifacts/storage_handlers/gcs_handler.py
  wandb/sdk/artifacts/storage_handlers/http_handler.py
  wandb/sdk/artifacts/storage_handlers/local_file_handler.py
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
  wandb/sdk/artifacts/storage_handlers/wb_artifact_handler.py
  wandb/sdk/artifacts/storage_handlers/wb_local_artifact_handler.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
Labels: cc-refactor

#6721 feat(core): add support for requirements and patch.diff
  core/go.mod
  core/go.sum
  core/pkg/server/files.go
  core/pkg/server/git.go
  core/pkg/server/git_test.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/stream.go
  core/pkg/service/wandb_internal.pb.go
  tests/pytest_tests/system_tests/test_core/test_file_upload.py
  tests/pytest_tests/system_tests/test_core/test_system_info.py
  tests/pytest_tests/system_tests/test_core/test_wandb_integration.py
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
  tests/pytest_tests/unit_tests_old/test_core/test_file_upload.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/system/system_info.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#6729 chore(sdk): remove copilot from PR template
  .github/pull_request_template.md
Labels: cc-chore

#6710 feat(core): capture SLURM-related env vars in metadata
  core/pkg/monitor/monitor.go
  core/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
Labels: cc-feat

#6737 test(core): enable system tests of system monitor
  .circleci/config.yml
  tests/pytest_tests/system_tests/test_system_metrics/test_open_metrics.py
Labels: cc-test

#6745 fix(launch): Get default entity before checking template vars
  wandb/cli/cli.py
  wandb/sdk/launch/utils.py
Labels: cc-fix

#6731 chore(launch): improve error message when job cannot be loaded
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_jobs.py
  wandb/sdk/launch/_project_spec.py
Labels: cc-chore

#6736 chore(core): release wandb-core==0.17.0b5
  .bumpversion.core.cfg
  .github/workflows/release-core.yml
  core/README.md
  core/internal/version/version.go
  core/setup.py
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
Labels: cc-chore

#6735 refactor(sdk): split public API into multiple files
  tests/pytest_tests/unit_tests/test_launch/test_job.py
  wandb/apis/attrs.py
  wandb/apis/paginator.py
  wandb/apis/public.py
  wandb/apis/public/__init__.py
  wandb/apis/public/api.py
  wandb/apis/public/artifacts.py
  wandb/apis/public/const.py
  wandb/apis/public/files.py
  wandb/apis/public/history.py
  wandb/apis/public/jobs.py
  wandb/apis/public/projects.py
  wandb/apis/public/query_generator.py
  wandb/apis/public/reports.py
  wandb/apis/public/runs.py
  wandb/apis/public/sweeps.py
  wandb/apis/public/teams.py
  wandb/apis/public/users.py
Labels: cc-refactor

#6746 fix(artifacts): remove run creation for artifact downloads if not using core
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.yea
  tests/functional_tests/t0_main/keras/keras_subclassed_test_tf_2_6.yea
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#6749 refactor(artifacts): clean up public API
  wandb/apis/public/__init__.py
  wandb/apis/public/api.py
  wandb/apis/public/artifacts.py
  wandb/apis/public/projects.py
Labels: cc-refactor

#6630 test(sdk): disable sentry in dev
  tests/functional_tests/t0_main/debug/t3_sentry_userproc_unix.yea
  tests/functional_tests/t0_main/debug/t4_sentry_tags.py
  tests/functional_tests/t0_main/debug/t5_sentry_third_party.yea
  tests/functional_tests/t0_main/debug/t7_sentry_session.py
  tests/functional_tests/t0_main/debug/t8_sentry_session_no_finish.py
  tests/pytest_tests/unit_tests/test_library_public.py
  tox.ini
  wandb/__init__.py
Labels: cc-test

#6705 feat(launch): --priority flag on `wandb launch` command to specify priority when enqueuing jobs.
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/system_tests/tests_launch/test_public_api.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_cli.py
  wandb/apis/public/jobs.py
  wandb/cli/cli.py
  wandb/sdk/internal/internal_api.py
Labels: cc-feat

#6747 feat(sdk): add verify feature to wandb login
  tests/pytest_tests/unit_tests/test_wandb_login.py
  wandb/cli/cli.py
  wandb/sdk/wandb_login.py
Labels: cc-feat

#6748 chore(sdk): explicit overrides in mypy config
  pyproject.toml
  tests/pytest_tests/system_tests/test_core/test_offline_sync.py
  wandb/__init__.py
  wandb/analytics/sentry.py
  wandb/errors/term.py
  wandb/errors/util.py
  wandb/sdk/internal/datastore.py
  wandb/sdk/internal/system/system_info.py
  wandb/sdk/lib/redirect.py
  wandb/sdk/wandb_summary.py
  wandb/sdk/wandb_watch.py
  wandb/vendor/pynvml/pynvml.py
Labels: cc-chore

#6752 chore(launch): improve error message for git repo missing requirements.txt
  wandb/sdk/launch/create_job.py
Labels: cc-chore

#6756 feat(launch): Sweeps on Launch honors selected job priority for sweep runs
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-feat

#6000 feat(core): 🦀 commence operation SDKrab 🦀
  .github/workflows/rust.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  client/Cargo.lock
  client/Cargo.toml
  client/build.rs
  client/pyproject.toml
  client/src/connection.rs
  client/src/launcher.rs
  client/src/lib.rs
  client/src/printer.rs
  client/src/run.rs
  client/src/session.rs
  client/src/settings.rs
  client/src/wandb_internal.rs
  client/wandb/__init__.py
  core/setup.py
  noxfile.py
Labels: cc-feat

#6497 feat(artifacts): make upload request async to support progress reporting
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_saver.py
  tests/pytest_tests/system_tests/test_artifacts/test_misc2.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/system_tests/test_core/test_cli_full.py
  tests/pytest_tests/system_tests/test_core/test_model_workflow.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#6759 fix(artifacts): Retrieve ETag for ObjectVersion instead of Object for versioned buckets
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
Labels: cc-fix

#6774 fix(artifacts): revert #6759 and read object version etag in place
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
Labels: cc-fix
