Repository wandb/wandb, pull requests merged in 2023-09, with the labels that each got.

#6203 fix(sdk): update report id validation and encoding
  tests/pytest_tests/system_tests/test_core/test_report_api.py
  wandb/apis/reports/report.py
Labels: cc-fix

#6210 test(sdk): unpin anyio as it was fixed by prefect
  tests/functional_tests/t0_main/prefect_ray/t1_prefect_ray_workflow.yea
Labels: cc-test

#6208 feat(nexus): support user defined headers in the gql client transport
  nexus/internal/clients/clients.go
  nexus/internal/clients/retry_policy.go
  nexus/pkg/server/sender.go
  nexus/pkg/server/stream.go
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#6212 build(nexus): fix config flag for the nexus build
  noxfile.py
Labels: cc-build

#6213 build(nexus): enhance nox session for building nexus
  nexus/pkg/monitor/gpu_nvidia.go
  nexus/scripts/build/Dockerfile
  nexus/setup.py
  noxfile.py
Labels: cc-build

#6193 docs(cli): Added more context for lauch job describe description.
  wandb/cli/cli.py
Labels: cc-docs

#6219 feat(sdk): enable set types in wandb.Config
  tests/pytest_tests/unit_tests/test_wandb_run.py
  wandb/util.py
Labels: cc-feat

#5884 fix(sdk): remove unnecessary initialization of save in __init__.py
  wandb/__init__.py
Labels: contrib

#6228 feat(sdk): add exponential decay sampling utility for line_plot
  tests/pytest_tests/unit_tests/test_util.py
  wandb/plot/line_series.py
  wandb/util.py
Labels: cc-feat

#4603 feat(sdk): always print the traceback inside of the `wandb.init` context manager
  wandb/sdk/wandb_run.py
Labels: cc-feat

#5803 fix(sdk): add support for propagating messages from the internal process
  nexus/pkg/server/handler.go
  nexus/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/handler.py
  wandb/sdk/lib/_wburls_generated.py
  wandb/sdk/lib/wburls.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#6230 feat(sdk): add setting to to disable automatic machine info capture
  nexus/pkg/service/wandb_settings.pb.go
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#6232 chore(sdk): bump SDK version to 0.15.11.dev1
  setup.cfg
  wandb/__init__.py
Labels: cc-chore

#6239 chore(sdk): set default http timeout in internal_api.py to 20s
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
Labels: cc-chore

#6240 chore(sdk): set default init timeout to 90s
  wandb/sdk/wandb_settings.py
Labels: cc-chore

#6241 build(sdk): switch to build for releases and update changelog for 0.15.10
  CHANGELOG.md
  Makefile
  pyproject.toml
Labels: cc-build

#6242 ci(sdk): fix automated reference docs generation upon a release
  .github/workflows/generate-docodile-documentation.yml
Labels: cc-ci

#6246 fix(sdk): Fix logger when logging filestream exception
  wandb/sdk/internal/file_stream.py
Labels: cc-fix

#6226 fix(launch): use watch api to monitor launched CRDs
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#6209 chore(nexus): add parallel benchmark
  nexus/cmd/benchmark/main.go
  nexus/cmd/examples/embed/main.go
  nexus/lang/core/wandbcore.go
  nexus/pkg/gowandb/gowandb.go
  nexus/pkg/gowandb/initrun.go
  nexus/pkg/gowandb/manager.go
  nexus/pkg/gowandb/opts/runopts/runopts.go
  nexus/pkg/gowandb/opts/session/opts.go
  nexus/pkg/gowandb/opts/sessionopts/sessionopts.go
  nexus/pkg/gowandb/session.go
  nexus/pkg/gowandb/settings/settings.go
  nexus/pkg/server/stream_mux.go
Labels: cc-chore

#6248 fix(launch): forbid enqueing docker images without target project
  wandb/cli/cli.py
  wandb/sdk/launch/utils.py
Labels: cc-fix

#6250 chore(launch): dont forbid waiting on container jobs
  wandb/apis/public.py
Labels: cc-chore

#6243 feat(nexus): add support for code saving in script mode
  nexus/go.mod
  nexus/go.sum
  nexus/pkg/server/handler.go
  nexus/pkg/server/util.go
  nexus/pkg/service/wandb_internal.pb.go
  nexus/pkg/service/wandb_settings.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/proto/wandb_settings.proto
  wandb/sdk/internal/system/system_info.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#6254 chore(nexus): minor clean up
  nexus/pkg/server/connection.go
  nexus/pkg/server/handler.go
Labels: cc-chore

#6252 docs(sdk): fixes a broken link in Image docs.
  wandb/sdk/data_types/image.py
Labels: cc-docs

#6263 chore(sdk): update requirements_build.txt
  requirements_build.txt
Labels: cc-chore

#6265 test(launch): don't assert that waiting on container job should raise launch error
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_jobs.py
Labels: cc-test

#6191 docs(nexus): add docs on running nexus-related system tests locally
  nexus/docs/contributing.md
  noxfile.py
Labels: cc-docs

#6267 feat(nexus): add support for `policy=end` in `wandb.save`
  nexus/pkg/server/files.go
  nexus/pkg/server/handler.go
Labels: cc-feat

#6268 build(nexus): add nexus proto gen to tox and make
  .circleci/config.yml
  Makefile
  tox.ini
Labels: cc-build

#6270 feat(nexus): add nvidia gpu system info to metadata
  nexus/pkg/monitor/cpu.go
  nexus/pkg/monitor/disk.go
  nexus/pkg/monitor/gpu_nvidia.go
  nexus/pkg/monitor/memory.go
  nexus/pkg/server/handler.go
  nexus/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
Labels: cc-feat

#6261 fix(sdk): add missing Twitter import for API users
  .vscode/settings.json
  wandb/apis/reports/blocks.py
Labels: cc-fix

#6262 test(sweeps): Add basic sweeps on launch regression test
  tests/release_tests/test_launch/conftest.py
  tests/release_tests/test_launch/launch-config-patch.yaml
  tests/release_tests/test_launch/test_kubernetes.py
  tests/release_tests/test_launch/utils.py
Labels: cc-test

#6255 fix(artifacts): get S3 versionIDs from directory references
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
Labels: cc-fix

#6276 docs(nexus): add user-facing Nexus docs for Beta release
  nexus/README.md
  nexus/pkg/service/wandb_telemetry.pb.go
  pyproject.toml
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/wandb_init.py
Labels: cc-docs

#6282 test(integrations): fix XGBoost example test to work with xgb>=2
  tests/functional_tests/t0_main/xgboost/test_xgboost_clf.py
  tests/functional_tests/t0_main/xgboost/xgboost_clf.yea
  wandb/integration/xgboost/xgboost.py
Labels: cc-test

#6272 fix(launch): make watch streams recover from connection reset
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_safe_watch.py
  wandb/sdk/launch/runner/kubernetes_monitor.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#6283 chore(launch): Refactor launch code with better structure for reference documentation
  tests/pytest_tests/system_tests/test_launch/test_launch.py
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/unit_tests/test_launch/test_launch_docker.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_aws.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_docker.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_jobs.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_local_process.py
  tests/release_tests/test_launch/test_kubernetes.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/sdk/launch/__init__.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/_launch_add.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/agent/run_queue_item_file_saver.py
  wandb/sdk/launch/runner/abstract.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-chore

#6266 chore(sdk): Pin PyYAML version
  pyproject.toml
Labels: cc-chore

#6295 refactor(artifacts): split file
  nexus/pkg/artifacts/linker.go
  nexus/pkg/artifacts/saver.go
Labels: cc-refactor

#6299 fix(public-api): use json.loads(..., strict=False) to ignore invalid utf-8 and control characters in api.Run.load
  wandb/apis/public.py
Labels: cc-fix

#6284 build(nexus): streamline nexus build pipeline
  .github/workflows/build-core.yml
  nexus/MANIFEST.in
  nexus/README.md
  nexus/pkg/server/sender.go
  nexus/scripts/build/install_go.py
  nexus/setup.py
  nexus/wandb_core/__init__.py
  noxfile.py
  pyproject.toml
  wandb/__init__.py
  wandb/env.py
  wandb/sdk/service/service.py
Labels: cc-build

#6301 build(nexus): fix reading readme on windows
  nexus/setup.py
Labels: cc-build

#6303 build(nexus): publish to wandb-core on testpypi
  .github/workflows/build-core.yml
Labels: cc-build

#6258 chore(launch): Delete kubernetes jobs when calling cancel instead of suspending
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-chore

#6308 fix(sdk): correctly identify colab as a jupyter-like env in settings
  wandb/sdk/lib/ipython.py
Labels: cc-fix

#6309 docs(nexus): fix pip install nexus instruction
  nexus/README.md
Labels: cc-docs

#6310 chore(sdk): fix bump2version config file to include alpha and beta pr…
  setup.cfg
Labels: cc-chore

#6312 build(sdk): automate release
  .github/CODEOWNERS
  .github/workflows/publish-to-pypi.yml
  .github/workflows/release-core.yml
  .github/workflows/release-sdk.yml
Labels: cc-build

#6313 build(sdk): automate release
  .github/workflows/release-sdk.yml
Labels: cc-build

#6314 build(sdk): automate release
  .github/workflows/release-sdk.yml
Labels: cc-build

#6316 build(sdk): fix verify test pypi upload in release-sdk.yml workflow
  .github/workflows/release-core.yml
  .github/workflows/release-sdk.yml
Labels: cc-build

#6281 chore(launch): Add launch agent build and release process
  .github/workflows/build-launch-agent.yml
  .github/workflows/release-launch-agent.yml
  tools/launch/build/Dockerfile
  tools/launch/release/Dockerfile
Labels: cc-chore

#6319 chore(artifacts): reduce ttl link warning
  wandb/sdk/wandb_run.py
Labels: cc-chore

#6317 feat(launch): delete run queues with public api
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  wandb/apis/public.py
Labels: cc-feat

#6300 feat(sdk): introduce custom proxy support for wandb http(s) traffic
  nexus/pkg/service/wandb_settings.pb.go
  tests/pytest_tests/unit_tests_old/utils/mock_requests.py
  tox.ini
  wandb/apis/public.py
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/internal/file_stream.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/lib/gql_request.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#5569 fix(sdk): improve memory management for summary updates
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/sender.py
  wandb/sdk/service/service.py
Labels: cc-fix

#6322 chore(nexus): set nexus codeowners to sdk-team
  .github/CODEOWNERS
Labels: cc-chore

#6321 test(launch): Add docker queue regression test
  tests/release_tests/test_launch/README.md
  tests/release_tests/test_launch/test_docker.py
  tests/release_tests/test_launch/test_kubernetes.py
  tests/release_tests/test_launch/utils.py
Labels: cc-test

#6329 test(artifacts): fix standalone_tests/artifact_tests.py::test_artifact_creation_with_diff_type
  tests/standalone_tests/artifact_tests.py
  wandb/sdk/wandb_run.py
Labels: cc-test

#6330 chore(sdk): lint util.py
  wandb/util.py
Labels: cc-chore

#6323 fix(artifacts): Add environment variable to configure batch size for download urls
  wandb/env.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#6324 fix(launch): fail rqis if no run is created
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#6343 test(sdk): increase the perf values
  tests/functional_tests/t0_main/perf/t1_basic.yea
Labels: cc-test

#6339 fix(launch): get logs from failed k8s pods
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#6347 chore(sdk): bump version 0.15.12.dev1
  CHANGELOG.md
  setup.cfg
  wandb/__init__.py
Labels: cc-chore

#6350 docs(sdk): fix reference docs GH action
  .github/workflows/generate-docodile-documentation.yml
Labels: cc-docs

#6349 chore(sdk): fix release gh actions
  .github/workflows/release-core.yml
  .github/workflows/release-sdk.yml
Labels: cc-chore

#6351 docs(sdk): Update generate-docodile-documentation.yml
  .github/workflows/generate-docodile-documentation.yml
Labels: cc-docs

#6346 fix(artifacts): Allow adding s3 bucket as reference artifact
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
Labels: cc-fix

#6338 chore(launch): Fix launch agent build action typo
  .github/workflows/build-launch-agent.yml
Labels: cc-chore

#6352 fix(launch): Fix race condition in agent thread clean up
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#6353 chore(launch): Reduce polling interval when launch agent receives a job
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#6363 fix(artifacts): don't assume run and its i/o artifacts are in the same project
  wandb/apis/public.py
Labels: cc-fix

#6334 chore(sdk): improve observability by altering the log handling for errors and panics
  nexus/internal/version/version.go
  nexus/pkg/observability/logging.go
  nexus/pkg/observability/sentry.go
  nexus/pkg/server/connection.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/responder.go
  nexus/pkg/server/sender.go
  nexus/pkg/server/stream.go
  nexus/pkg/server/writer.go
Labels: cc-chore

#6362 fix(artifacts): fix wandb.Api().run(run_name).log_artifact(artifact)
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  tests/pytest_tests/unit_tests_old/test_public_api.py
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
Labels: cc-fix

#6365 test(nexus): skip test_run_log_artifact test
  tests/pytest_tests/system_tests/test_core/test_public_api.py
Labels: cc-test

#6364 fix(sweeps): ValueError with None value in sweep
  tests/pytest_tests/system_tests/test_sweep/test_wandb_agent.py
  tests/pytest_tests/system_tests/test_sweep/test_wandb_sweep.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-fix

#6367 chore(launch): Add repo checkout to launch actions
  .github/workflows/build-launch-agent.yml
  .github/workflows/release-launch-agent.yml
Labels: cc-chore

#6331 feat(nexus): implement config debouncing mechanism
  nexus/go.mod
  nexus/go.sum
  nexus/internal/debounce/debounce.go
  nexus/internal/debounce/debounce_test.go
  nexus/pkg/observability/logging.go
  nexus/pkg/server/sender.go
  tests/pytest_tests/system_tests/test_core/test_metric_full.py
Labels: cc-feat

#6370 test(integrations): pin tf<2.14
  requirements_dev.txt
Labels: cc-test

#6377 fix(artifacts): fix the argument order for new argument target_fraction
  wandb/sdk/artifacts/artifacts_cache.py
Labels: cc-fix

#6382 feat(integrations): fix channel swapping on ultrlytics classification task
  wandb/integration/ultralytics/classification_utils.py
Labels: bug, cc-feat

#6358 feat(nexus): implement nexus alpha cpp interface
  nexus/internal/gowandb/internal_runopts/runopts.go
  nexus/internal/shared/headfoot.go
  nexus/lang/c/lib/libwandb.c
  nexus/lang/c/lib/libwandb.h
  nexus/lang/core/partialdata.go
  nexus/lang/core/wandbcore.go
  nexus/lang/cpp/examples/train.cpp
  nexus/lang/cpp/examples/train_session.cpp
  nexus/lang/cpp/lib/libwandb_cpp.cpp
  nexus/lang/cpp/lib/libwandb_cpp.h
  nexus/lang/docs/README-libwandb-cpp.md
  nexus/lang/scripts/base-build.sh
  nexus/lang/scripts/build-dist-libwandb-cpp.sh
  nexus/lang/scripts/format.sh
  nexus/pkg/gowandb/manager.go
  nexus/pkg/gowandb/opts/runopts/runopts.go
  nexus/pkg/gowandb/run.go
  nexus/pkg/gowandb/runconfig/runconfig.go
  nexus/pkg/gowandb/session.go
  nexus/pkg/gowandb/settings/settings.go
  nexus/pkg/server/sender.go
  nexus/pkg/server/sender_test.go
  nexus/pkg/server/stream.go
  nexus/pkg/server/writer.go
  nexus/pkg/service/wandb_telemetry.pb.go
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
Labels: cc-feat

#6374 chore(launch): Improve run stopping robustness for launch runs
  tests/pytest_tests/system_tests/test_launch/test_job_status_tracker.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/agent/job_status_tracker.py
Labels: cc-chore

#6229 chore(sdk): rm unnecessary top-level wandb save
  wandb/__init__.py
  wandb/sdk/__init__.py
  wandb/sdk/wandb_save.py
Labels: cc-chore

#6385 fix(nexus): fix potential race in config debouncer
  nexus/internal/debounce/debounce.go
  nexus/internal/debounce/debounce_test.go
  nexus/pkg/server/sender.go
  tests/pytest_tests/system_tests/test_core/test_metric_full.py
Labels: cc-fix
