Repository wandb/wandb, pull requests merged in 2023-02, with the labels that each got.

#4860 refactor(sdk): use stdlib ThreadPoolExecutor in StepUpload instead of managing our own
  wandb/filesync/step_upload.py
  wandb/filesync/upload_job.py
Labels: cc-refactor

#4884 fix(launch): Fix issue where job artifacts are being logged without latest alias
  wandb/sdk/internal/sender.py
Labels: cc-fix

#4734 docs(sdk): Docodoile autogen docs
  .github/workflows/generate-docodile-documentation.yml
Labels: cc-docs

#4848 feat(sdk): add the ability to append to a run with `wandb sync --append`
  tests/functional_tests/t0_main/sync/t1_sync_append.py
  tests/functional_tests/t0_main/sync/t1_sync_append.yea
  wandb/cli/cli.py
  wandb/sdk/internal/sender.py
  wandb/sync/sync.py
Labels: cc-feat

#4904 revert(artifacts): revert "allow setting artifact cache dir in wandb.init(...)"
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_cache.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/wandb_settings.py
Labels: cc-revert

#4889 fix(launch): Ensure job names do not exceed maximum allowable for artifacts
  tests/pytest_tests/unit_tests/test_job_builder.py
  wandb/sdk/internal/job_builder.py
  wandb/util.py
Labels: cc-fix

#4901 feat(launch): add an escape hatch (`disable_job_creation`) to disable automatic job creation
  tests/functional_tests/t0_main/jobs/job_artifact_creation_disabled.py
  tests/functional_tests/t0_main/jobs/job_artifact_creation_disabled.yea
  tests/pytest_tests/unit_tests/test_job_builder.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#4906 chore(sdk): open up 0.13.11 development
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: changelog-ignore, cc-chore

#4915 test(sdk): fix broken dependencies in tests
  requirements_dev.txt
  tests/functional_tests/t0_main/sb3/t1_stable_baselines3.yea
Labels: cc-test

#4922 chore(sdk): Update CHANGELOG.md for 0.13.10
  CHANGELOG.md
Labels: cc-chore

#4912 fix(sdk): clean up IPython's widget deprecation warning
  wandb/sdk/lib/ipython.py
Labels: cc-fix

#4890 fix(sdk): add special Exceptions for the manager logic, when trying to connect to a gone service
  wandb/errors/__init__.py
  wandb/sdk/service/service.py
  wandb/sdk/wandb_manager.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#4689 fix(sdk): Fix issue where global config directory had to be writable to use Api
  tests/pytest_tests/unit_tests/test_internal_api.py
  wandb/old/settings.py
  wandb/sdk/launch/deploys/aws-eks/launch-agent.yaml
  wandb/sdk/launch/deploys/kubernetes/launch-agent.yaml
Labels: cc-fix

#4909 fix(sdk): make error message during run initialization more actionable and fix uncaught exception
  tests/pytest_tests/system_tests/test_sender.py
  tests/pytest_tests/unit_tests/test_util.py
  wandb/sdk/internal/sender.py
  wandb/util.py
Labels: cc-fix

#4891 fix(sdk): add deepcopy dunder method to the Run class
  tests/pytest_tests/unit_tests/test_wandb_run.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#4936 fix(launch): mkdir_exists_ok now (again) checks permission on existence
  wandb/sdk/lib/filesystem.py
Labels: cc-fix

#4886 fix(launch): Only log the received job when launching something sourced from a job
  wandb/sdk/launch/_project_spec.py
Labels: cc-fix

#4701 fix(launch): Fix issue where queued runs sourced from images would vanish in URI
  tests/pytest_tests/system_tests/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_kubernetes.py
  wandb/sdk/launch/runner/kubernetes.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/wandb_init.py
Labels: cc-fix

#4641 fix(artifacts): add write permissions to copied artifacts
  tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
  tests/pytest_tests/unit_tests/test_saved_model.py
  wandb/apis/public.py
  wandb/sdk/lib/filesystem.py
Labels: cc-fix

#4941 chore(sweeps): remove queue=default and add -q shortcut
  wandb/cli/cli.py
Labels: cc-chore

#4817 fix(sdk): when in disable mode don't spin up service
  tests/functional_tests/t0_main/debug/t4_sentry_tags.py
  tests/pytest_tests/system_tests/test_data_types_full.py
  tests/pytest_tests/system_tests/test_mp_full.py
  tests/pytest_tests/system_tests/test_wandb.py
  tests/pytest_tests/system_tests/test_wandb_run.py
  tests/pytest_tests/system_tests/test_wandb_settings.py
  tests/pytest_tests/unit_tests/test_wandb_run.py
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  wandb/__init__.py
  wandb/cli/cli.py
  wandb/env.py
  wandb/sdk/internal/internal.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_require.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
  wandb/sdk/wandb_setup.py
  wandb/util.py
Labels: cc-fix

#4960 style(sdk): fix bugbear B028 add stacklevel
  wandb/integration/sacred/__init__.py
Labels: cc-style

#4923 chore(sdk): Add mlw-team as codeowners of tests_launch folders
  .github/CODEOWNERS
Labels: cc-chore

#4896 fix(artifacts): API - ArtifactFiles no longer errors when accessing an item
  tests/pytest_tests/system_tests/test_public_api.py
  wandb/apis/public.py
Labels: cc-fix

#4943 chore(sweeps): confirm job exists before launching the 8 jobs
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#4964 fix(sdk): handle system metrics requiring extra setup and teardown steps
  tests/pytest_tests/unit_tests_old/assets/notebooks/code_saving.ipynb
  tests/pytest_tests/unit_tests_old/assets/notebooks/login_timeout.ipynb
  tests/pytest_tests/unit_tests_old/assets/notebooks/setup.ipynb
  wandb/sdk/internal/system/assets/interfaces.py
  wandb/sdk/internal/system/assets/trainium.py
Labels: cc-fix

#4404 ci(sdk): automate release
  .github/workflows/bump-dev-version.yml
  .github/workflows/bump-version.yml
  .github/workflows/contributing.yml
  .github/workflows/python-package.yml
  .github/workflows/release.yml
  pyproject.toml
  setup.cfg
  tools/circleci-tool.py
Labels: cc-ci

#4971 ci(sdk): update auto-release workflow
  .github/workflows/release.yml
Labels: cc-ci

#4972 ci(sdk): more tweaks to the auto-release workflow
  .github/workflows/bump-version.yml
Labels: cc-ci

#4975 ci(sdk): fix bump version workflow
  .github/workflows/bump-version.yml
Labels: cc-ci

#4978 ci(sdk): use the commitizen action
  .github/workflows/bump-version.yml
Labels: cc-ci

#4981 chore(sdk): unpin mypy to fix new request typing
  tox.ini
  wandb/integration/tensorboard/monkeypatch.py
Labels: cc-chore

#4973 docs(cli): Formatted wandb.apis.public.Run.history docstring
  wandb/apis/public.py
Labels: cc-docs

#4974 chore(launch): More detailed logging in runners
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/runner/aws.py
  wandb/sdk/launch/runner/gcp_vertex.py
  wandb/sdk/launch/runner/kubernetes.py
  wandb/sdk/launch/runner/local_container.py
Labels: cc-chore

#4984 fix(sdk): fix a typo in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: cc-fix

#4987 fix(sdk): correctly detect notebook name and fix code saving in Colab
  tests/pytest_tests/unit_tests_old/tests_s_nb/test_notebooks.py
  wandb/jupyter.py
Labels: cc-fix

#4991 fix(artifacts): allow up to max_artifacts (fix off by 1 error)
  wandb/sdk/wandb_artifacts.py
Labels: cc-fix

#4952 chore(sdk): Ignore wandb run data
  .gitignore
Labels: cc-chore

#4994 test(sdk): fix admin user creation and setting up passwords for ui for --wandb-debug
  tests/pytest_tests/system_tests/conftest.py
Labels: cc-test

#4995 style(launch): move launch errors closer to the code
  tests/pytest_tests/system_tests/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_aws.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_docker.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_gcp.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_jobs.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_kubernetes.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_utils.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/docker/__init__.py
  wandb/errors/__init__.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker.py
  wandb/sdk/launch/builder/kaniko.py
  wandb/sdk/launch/builder/loader.py
  wandb/sdk/launch/builder/noop.py
  wandb/sdk/launch/github_reference.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/launch/runner/aws.py
  wandb/sdk/launch/runner/gcp_vertex.py
  wandb/sdk/launch/runner/kubernetes.py
  wandb/sdk/launch/runner/loader.py
  wandb/sdk/launch/runner/local_process.py
  wandb/sdk/launch/utils.py
Labels: cc-style

#4993 test(sdk): create a shard for sweep and artifact system tests
  .circleci/config.yml
  .codecov.yml
  tests/pytest_tests/system_tests/test_core/test_cli_full.py
  tests/pytest_tests/system_tests/test_core/test_data_types_full.py
  tests/pytest_tests/system_tests/test_core/test_file_stream_internal.py
  tests/pytest_tests/system_tests/test_core/test_file_upload.py
  tests/pytest_tests/system_tests/test_core/test_footer.py
  tests/pytest_tests/system_tests/test_core/test_keras_full.py
  tests/pytest_tests/system_tests/test_core/test_kfp.py
  tests/pytest_tests/system_tests/test_core/test_label_full.py
  tests/pytest_tests/system_tests/test_core/test_metric_full.py
  tests/pytest_tests/system_tests/test_core/test_metric_internal.py
  tests/pytest_tests/system_tests/test_core/test_mode_disabled_full.py
  tests/pytest_tests/system_tests/test_core/test_model_workflow.py
  tests/pytest_tests/system_tests/test_core/test_mp_full.py
  tests/pytest_tests/system_tests/test_core/test_offline_sync.py
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  tests/pytest_tests/system_tests/test_core/test_redir_full.py
  tests/pytest_tests/system_tests/test_core/test_report_api.py
  tests/pytest_tests/system_tests/test_core/test_runtime.py
  tests/pytest_tests/system_tests/test_core/test_save_policies.py
  tests/pytest_tests/system_tests/test_core/test_sender.py
  tests/pytest_tests/system_tests/test_core/test_start_method.py
  tests/pytest_tests/system_tests/test_core/test_system_info.py
  tests/pytest_tests/system_tests/test_core/test_tb_watcher.py
  tests/pytest_tests/system_tests/test_core/test_telemetry_full.py
  tests/pytest_tests/system_tests/test_core/test_time_resolution.py
  tests/pytest_tests/system_tests/test_core/test_torch_full.py
  tests/pytest_tests/system_tests/test_core/test_validation_data_logger.py
  tests/pytest_tests/system_tests/test_core/test_wandb.py
  tests/pytest_tests/system_tests/test_core/test_wandb_integration.py
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
  tests/pytest_tests/system_tests/test_core/test_wandb_settings.py
  tests/pytest_tests/system_tests/test_core/test_wandb_tensorflow.py
  tests/pytest_tests/system_tests/test_core/test_wandb_verify.py
Labels: cc-test

#4997 style(sdk): move mailbox error closer to the code
  wandb/apis/normalize.py
  wandb/errors/__init__.py
  wandb/sdk/internal/sender.py
  wandb/sdk/lib/mailbox.py
  wandb/sdk/lib/retry.py
  wandb/sdk/wandb_run.py
Labels: cc-style

#5007 chore(sdk): exercise extra caution when starting asset monitoring threads
  wandb/sdk/internal/system/assets/interfaces.py
Labels: cc-chore

#4979 test(sdk): unit tests for StepPrepare
  tests/pytest_tests/unit_tests/test_step_prepare.py
  wandb/filesync/step_prepare.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-test

#5010 chore(launch): log better when default project
  wandb/sdk/launch/launch_add.py
Labels: cc-chore

#4937 chore(launch): sweep run_cap now works for launch sweeps
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/scheduler_sweep.py
Labels: cc-chore

#4976 feat(sweeps): launch sweep jobs from image_uri
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/cli/cli.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-feat

#4999 style(sdk): add unsupported error type
  tests/pytest_tests/unit_tests/test_require_user.py
  wandb/errors/__init__.py
  wandb/sdk/wandb_require.py
  wandb/sdk/wandb_run.py
Labels: cc-style

#4967 chore(sdk): Add codeql scanning on PR for python changes
  .github/workflows/codeql-analysis.yml
Labels: cc-chore

#4875 docs(sdk): update references to test file locations in documentation
  CONTRIBUTING.md
  tools/loop.sh
Labels: cc-docs

#4945 style(sdk): add support for the ruff linter
  .pre-commit-config.yaml
  .vscode/settings.json
  pyproject.toml
  tests/ruff.toml
  tests/standalone_tests/grpc_client.py
  tools/ruff.toml
  tools/tracelog-tool.py
  wandb/apis/public.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-style

#4892 build(sdk): fix editable mode with latest version of pip
  pyproject.toml
  tools/setup_dev_environment.py
Labels: cc-build

#5021 refactor(sweeps): cosmetic changes for readability
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_wandb_agent.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/scheduler_sweep.py
  wandb/wandb_agent.py
Labels: cc-refactor

#5025 chore(sweeps): cast num_workers as string in sweep command
  wandb/cli/cli.py
Labels: cc-chore

#5027 chore(sdk): add ruff rules to replace pyupgrade
  .pre-commit-config.yaml
  pyproject.toml
  wandb/cli/cli.py
  wandb/sdk/launch/utils.py
Labels: cc-chore

#5035 chore(launch): num_workers now in launch_config
  tests/pytest_tests/system_tests/tests_launch/test_launch_cli.py
  wandb/cli/cli.py
Labels: cc-chore

#5026 feat(artifacts): raise ArtifactNotLoggedError instead of ValueError
  .gitignore
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests_old/test_wandb_artifacts.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#4858 fix(artifacts): Fix the file reference added to the verification artifact
  wandb/sdk/verify/verify.py
Labels: cc-fix

#4916 chore(launch): Introduce Environment and Registry
  requirements_dev.txt
  setup.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_gcp.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_ecr.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_gcp_artifact_registry.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_aws.py
  wandb/sdk/launch/environment/abstract.py
  wandb/sdk/launch/environment/aws_environment.py
  wandb/sdk/launch/environment/gcp_environment.py
  wandb/sdk/launch/registry/abstract.py
  wandb/sdk/launch/registry/elastic_container_registry.py
  wandb/sdk/launch/registry/google_artifact_registry.py
  wandb/sdk/launch/runner/loader.py
  wandb/sdk/launch/runner/sagemaker_runner.py
Labels: cc-chore

#5033 feat(launch): Launch agent uses thread pool to run jobs
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  wandb/apis/internal.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-feat

#5047 docs(sdk): fix missed docstring lint errors reported by ruff
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py
  tests/pytest_tests/unit_tests/test_library_public.py
  tests/standalone_tests/artifact_load.py
  wandb/apis/internal.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-docs

#5046 test(artifacts): move artifacts unit tests
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_artifacts/conftest.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-test

#5049 refactor(artifacts): remove the artifact from the manifest
  wandb/apis/public.py
  wandb/sdk/interface/artifacts.py
  wandb/sdk/internal/artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-refactor

#5052 style(artifacts): enable typechecking for interface.artifacts and add type hints / casts
  mypy.ini
  wandb/sdk/interface/artifacts.py
  wandb/sdk/interface/interface.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-style

#4824 chore(sdk): type-annotate wandb_setup.py
  mypy.ini
  wandb/errors/term.py
  wandb/sdk/lib/config_util.py
  wandb/sdk/lib/server.py
  wandb/sdk/wandb_settings.py
  wandb/sdk/wandb_setup.py
  wandb/util.py
Labels: cc-chore

#4961 chore(launch): special handling for sweeps scheduler in agent
  tests/pytest_tests/system_tests/tests_launch/test_launch_sweep.py
  wandb/cli/cli.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/sweeps/__init__.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/scheduler_sweep.py
Labels: cc-chore

#5058 style(sdk): remove unused #noqa directives
  tests/functional_tests/t0_main/imports/01-batch1.py
  tests/functional_tests/t0_main/kfp/kfp-pipeline-helper.py
  tests/functional_tests/t0_main/kfp/kfp-pipeline-sklearn.py
  tests/functional_tests/t0_main/magic/t1_mnist_convnet.py
  tests/pytest_tests/unit_tests/test_data_types.py
  tests/pytest_tests/unit_tests/test_metaflow.py
  tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_tpu.py
  tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_trainium.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/integration/kfp/kfp_patch.py
  wandb/integration/tensorboard/log.py
  wandb/jupyter.py
  wandb/sdk/internal/datastore.py
  wandb/sdk/internal/system/assets/gpu_apple.py
  wandb/sdk/internal/system/system_info.py
  wandb/sdk/internal/tb_watcher.py
  wandb/sdk/launch/runner/kubernetes.py
  wandb/sdk/launch/utils.py
  wandb/sdk/lib/redirect.py
  wandb/sdk/service/service.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_helper.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-style

#4894 chore(sdk): update links for new docs
  README.md
  tests/functional_tests/t0_main/raytune/t1_example.py
  tests/functional_tests/t0_main/raytune/t5_colab.py
  wandb/__init__.py
  wandb/sdk/lib/wburls.py
  wandb/sdk/wandb_config.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_sweep.py
Labels: cc-chore

#5028 chore(sdk): Add tox sections for ruff check/fix
  .circleci/config.yml
  .pre-commit-config.yaml
  pyproject.toml
  tox.ini
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/wandb_settings.py
Labels: cc-chore
