Repository wandb/wandb, pull requests merged in 2023-07, with the labels that each got.

#5639 fix(launch): Support namespace in metadata key of resource args
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#5704 chore(cli): change docstring single quotes to multiline triple quotes
  wandb/cli/cli.py
Labels: cc-chore

#5838 test(integrations): fix multiple broken tests
  .circleci/config.yml
  .codecov.yml
  tests/pytest_tests/system_tests/test_core/test_keras_full.py
  tox.ini
  wandb/integration/keras/keras.py
Labels: cc-test

#5839 fix(launch): use "" instead of None for project kwarg when no project given
  wandb/sdk/launch/utils.py
Labels: cc-fix

#5835 chore(launch): remove gcp region check to avoid perm requirement
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_gcp.py
  wandb/sdk/launch/environment/gcp_environment.py
Labels: cc-chore

#5833 fix(launch): add + to torch cpu regex + tests
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_bootstrap.py
  wandb/sdk/launch/builder/templates/_wandb_bootstrap.py
Labels: cc-fix

#5841 chore(launch): fix launch ci test failures
  .circleci/config.yml
  .codecov.yml
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_aws.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
Labels: cc-chore

#5812 fix(sdk): implement timeout for file_stream and add debug logs
  .circleci/config.yml
  .codecov.yml
  .coveragerc
  .flake8-base
  .flake8-darglint
  .flake8-docstrings
  .github/wb-logo-darkbg.png
  .github/wb-logo-lightbg.png
  .github/workflows/bump-dev-version.yml
  .github/workflows/bump-version.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/contributing.yml
  .github/workflows/generate-documentation.yml
  .github/workflows/nightly-darglint.yml
  .github/workflows/publish-to-pypi.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  .pylintrc
  CONTRIBUTING.md
  pyproject.toml
  setup.cfg
  tests/.isort.cfg
  tests/standalone_tests/mitm_tests/fs_inject.py
  tests/standalone_tests/mitm_tests/t1_mem_pressure_init.yea
  tests/standalone_tests/mitm_tests/t2_fs_inject.yea
  tests/standalone_tests/mitm_tests/t3_fs_inject_no_timeout.yea
  tools/.isort.cfg
  tools/locate-py-files.py
  tox.ini
  wandb/sdk/internal/file_stream.py
  wandb/sdk/internal/progress.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#5842 chore(launch): Deep copy resource args in LaunchProject to allow mutating
  wandb/sdk/launch/_project_spec.py
Labels: cc-chore

#5817 chore(artifacts): fix artifacts test regression by sorting lists before comparing
  tests/standalone_tests/artifact_tests.py
Labels: cc-chore

#5810 fix(artifacts): fix collection filtering when getting aliases
  tests/pytest_tests/unit_tests/test_saved_model.py
  tests/pytest_tests/unit_tests_old/utils/mock_server.py
  tox.ini
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#5821 chore(artifacts): fix import for getting artifacts cache in standalone test
  tests/standalone_tests/artifact_object_reference_test.py
Labels: cc-chore

#5786 refactor(sdk): make settings natively protobuf-friendly
  .pre-commit-config.yaml
  CONTRIBUTING.md
  pyproject.toml
  pytest.ini
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_core/test_cli_full.py
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
  tests/pytest_tests/system_tests/test_core/test_wandb_settings.py
  tests/pytest_tests/unit_tests/test_flow_control.py
  tests/pytest_tests/unit_tests/test_job_builder.py
  tests/pytest_tests/unit_tests/test_sender.py
  tests/pytest_tests/unit_tests/test_step_upload.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_gpu.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_gpu_amd.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_gpu_apple.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_ipu.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_open_metrics.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_system_monitor.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_trainium.py
  tests/pytest_tests/unit_tests/test_wandb_login.py
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  tools/pr-title-bot.py
  tox.ini
  wandb/analytics/sentry.py
  wandb/apis/__init__.py
  wandb/apis/public.py
  wandb/proto/v3/wandb_server_pb2.py
  wandb/proto/v3/wandb_server_pb2.pyi
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_server_pb2.py
  wandb/proto/v4/wandb_server_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_internal_codegen.py
  wandb/proto/wandb_server.proto
  wandb/proto/wandb_settings.proto
  wandb/proto/wandb_settings_pb2.py
  wandb/sdk/artifacts/artifacts_cache.py
  wandb/sdk/artifacts/storage_handlers/azure_handler.py
  wandb/sdk/backend/backend.py
  wandb/sdk/internal/internal.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/internal/system/system_info.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/lib/proto_util.py
  wandb/sdk/service/server_grpc.py
  wandb/sdk/service/server_sock.py
  wandb/sdk/service/service.py
  wandb/sdk/service/service_base.py
  wandb/sdk/service/service_grpc.py
  wandb/sdk/service/service_sock.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_manager.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
Labels: cc-refactor

#5849 ci(sdk): free Dobby, the title checking Elf
  .github/workflows/check-pr-title.yml
Labels: cc-ci

#5767 feat(launch): add job link to wandb footer
  tests/pytest_tests/system_tests/test_core/test_footer.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v3/wandb_server_pb2.py
  wandb/proto/v3/wandb_server_pb2_grpc.py
  wandb/proto/v3/wandb_server_pb2_grpc.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_server_pb2.py
  wandb/proto/v4/wandb_server_pb2_grpc.py
  wandb/proto/v4/wandb_server_pb2_grpc.pyi
  wandb/proto/wandb_internal.proto
  wandb/proto/wandb_server.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_grpc.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
  wandb/sdk/lib/printer.py
  wandb/sdk/service/server_grpc.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#5850 chore(launch): always pull latest tag
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/system_tests/test_launch/test_launch_local_container.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/utils.py
Labels: cc-chore

#5852 chore(sdk): clean up unused configs
  pyproject.toml
  tests/functional_tests/t0_main/metaflow/wandb-pytorch-flow.py
  wandb/env.py
  wandb/integration/keras/keras.py
  wandb/keras/__init__.py
  wandb/viz.py
Labels: cc-chore

#5822 feat(launch): re-implement job requeueing, fixed cancel behavior
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/agent/job_status_tracker.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/runner/abstract.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-feat

#5797 chore(sweeps): better resource defaults for launch sweeps
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep_cli.py
  wandb/cli/cli.py
Labels: cc-chore

#5731 perf(sdk): use mutation createRunFiles to get uploadUrls
  tests/pytest_tests/unit_tests/test_step_upload.py
  wandb/filesync/upload_job.py
  wandb/sdk/internal/internal_api.py
  wandb/testing/relay.py
Labels: cc-perf

#5863 fix(sdk): replace `dir_watcher` settings with SettingsStatic
  wandb/filesync/dir_watcher.py
  wandb/sdk/internal/sender.py
  wandb/sync/sync.py
Labels: cc-fix

#5869 chore(sdk): disable flake8 in Visual Studio Code
  .vscode/settings.json
Labels: cc-chore

#5864 test(artifacts): fix video fixture
  tests/standalone_tests/artifact_object_reference_test.py
Labels: cc-test

#5661 feat(launch): manually create jobs from cli
  tests/pytest_tests/system_tests/test_launch/test_github_reference.py
  tests/pytest_tests/system_tests/test_launch/test_job.py
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests/test_launch/test_create_job.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
  wandb/sdk/launch/create_job.py
  wandb/sdk/launch/github_reference.py
Labels: cc-feat

#5878 build(sdk): add wheel to requirements_build.txt
  requirements_build.txt
Labels: cc-build

#5791 feat(launch): allow users to specify job name via the `job_name` setting
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/internal/job_builder.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#5825 refactor(launch): take build out of runner.run
  tests/pytest_tests/system_tests/test_launch/test_launch.py
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/system_tests/test_launch/test_launch_local_container.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/loader.py
  wandb/sdk/launch/runner/abstract.py
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/runner/sagemaker_runner.py
  wandb/sdk/launch/runner/vertex_runner.py
Labels: cc-refactor

#5800 chore(sweeps): scheduler job failing should set sweep state
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#5882 chore(sdk): fix UP032 linting errors
  tests/pytest_tests/system_tests/test_core/test_wandb_integration.py
  tools/circleci-tool.py
  wandb/cli/cli.py
  wandb/docker/__init__.py
  wandb/docker/auth.py
  wandb/filesync/upload_job.py
  wandb/sdk/data_types/_dtypes.py
  wandb/sdk/data_types/base_types/media.py
  wandb/sdk/internal/datastore.py
  wandb/sdk/internal/sender.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/runner/vertex_runner.py
  wandb/sdk/wandb_run.py
  wandb/wandb_torch.py
Labels: cc-chore

#5876 test(artifacts): fix broken tests
  wandb/sdk/artifacts/artifact.py
Labels: cc-test

#5662 test(launch): Add Launch release tests for kubernetes runner
  tests/release_tests/test_launch/README.md
  tests/release_tests/test_launch/conftest.py
  tests/release_tests/test_launch/launch-agent-patch.yaml
  tests/release_tests/test_launch/launch-config-patch.yaml
  tests/release_tests/test_launch/local-agent-config.yml
  tests/release_tests/test_launch/test_kubernetes.py
  tests/release_tests/test_launch/utils.py
  tox.ini
Labels: cc-test

#5880 fix(launch): drop https from azure registries to ensure compatibility with ${image_uri} macro
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_acr.py
  wandb/sdk/launch/registry/azure_container_registry.py
Labels: cc-fix

#5890 test(sdk): pin lightgbm
  tests/functional_tests/t0_main/lightgbm/t1_regression.yea
Labels: cc-test

#5888 chore(launch): skip job create test broken on windows
  tests/pytest_tests/unit_tests/test_launch/test_create_job.py
Labels: cc-chore

#5904 chore(sdk): remove _log_thread_stacks function from util.py
  requirements_dev.txt
  wandb/util.py
Labels: cc-chore

#5910 fix(artifacts): handle None description correctly
  wandb/sdk/internal/sender.py
Labels: cc-fix

#5883 chore(sdk): add ability to launch nexus from dev dir
  wandb/sdk/service/service.py
Labels: cc-chore

#5915 test(integrations): add telemetry for new libraries
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
Labels: cc-test

#5874 feat(launch): add create_run_queue to public API
  wandb/apis/internal.py
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
Labels: cc-feat

#5887 docs(sdk): Add introspection section to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cc-docs

#5911 perf(sdk): add hidden option to use orjson instead of json
  requirements_dev.txt
  setup.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/data_types/utils.py
  wandb/sdk/interface/interface.py
  wandb/sdk/lib/json_util.py
  wandb/util.py
Labels: cc-perf

#5900 fix(launch): Don't create k8s secret if it already exists
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#5794 feat(sdk): Add an simplified trace API to log prompt traces
  tests/pytest_tests/unit_tests/test_trace_tree.py
  wandb/sdk/data_types/trace_tree.py
Labels: cc-feat

#5781 chore(sdk): Add more record options to _make_record
  wandb/sdk/interface/interface_shared.py
Labels: cc-chore

#5780 chore(sdk): Cleanup Report API for Importer
  wandb/apis/reports/mutations.py
  wandb/apis/reports/report.py
Labels: cc-chore

#5783 refactor(sdk): transition sender classes to use custom protocols
  wandb/apis/importers/base.py
  wandb/apis/importers/mlflow.py
  wandb/sdk/internal/sender.py
  wandb/util.py
Labels: cc-chore

#5917 fix(sdk): use default settings for project retrieval if available
  wandb/sdk/internal/internal_api.py
Labels: cc-fix

#5921 chore(launch): full path to sweep in set state
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#5925 feat(launch): Improve error message when building with noop builder
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  wandb/sdk/launch/builder/noop.py
Labels: cc-feat

#5893 feat(launch): create launch agent includes agent config if present
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/utils/mock_server.py
  tox.ini
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-feat

#5932 chore(launch): special handling for resumed sweep runs
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#5940 chore(sdk): fix new lint issues identified by ruff 0.0.280
  tests/standalone_tests/simpsons_data_frames.py
  wandb/analytics/sentry.py
  wandb/docker/auth.py
  wandb/filesync/dir_watcher.py
  wandb/filesync/stats.py
  wandb/filesync/step_prepare.py
  wandb/filesync/step_upload.py
  wandb/integration/keras/keras.py
  wandb/integration/tensorboard/log.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/artifacts/artifacts_cache.py
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
  wandb/sdk/backend/backend.py
  wandb/sdk/integration_utils/auto_logging.py
  wandb/sdk/integration_utils/data_logging.py
  wandb/sdk/internal/file_pusher.py
  wandb/sdk/internal/file_stream.py
  wandb/sdk/internal/flow_control.py
  wandb/sdk/internal/internal.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/progress.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/system/assets/cpu.py
  wandb/sdk/internal/system/assets/ipu.py
  wandb/sdk/internal/system/assets/open_metrics.py
  wandb/sdk/internal/system/assets/trainium.py
  wandb/sdk/internal/system/system_monitor.py
  wandb/sdk/internal/tb_watcher.py
  wandb/sdk/internal/writer.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/lib/mailbox.py
  wandb/sdk/lib/tracelog.py
  wandb/sdk/service/server_sock.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_setup.py
  wandb/testing/relay.py
  wandb/util.py
Labels: cc-chore

#5927 fix(artifacts): wrap call to get S3 bucket version to guard against permission errors
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
Labels: cc-fix

#5946 chore(sdk): bump sdk dev version 0.15.7.dev1 and changelog
  CHANGELOG.md
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5947 docs(sdk): update GH action to generate reference docs and clean up docstrings
  .github/workflows/generate-docodile-documentation.yml
  CONTRIBUTING.md
  wandb/integration/keras/callbacks/tables_builder.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/service/_startup_debug.py
  wandb/sdk/service/server.py
  wandb/sdk/wandb_run.py
Labels: cc-docs

#5951 revert(sdk): revert support for migrating W&B runs and reports between instances (#5777)
  .circleci/config.yml
  .codecov.yml
  requirements_dev.txt
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/helpers.py
  tests/pytest_tests/system_tests/test_importers/conftest.py
  tests/pytest_tests/system_tests/test_importers/test_import_wandb.py
  wandb/apis/importers/__init__.py
  wandb/apis/importers/base.py
  wandb/apis/importers/wandb.py
  wandb/cli/cli.py
  wandb/filesync/dir_watcher.py
  wandb/util.py
Labels: cc-revert

#5899 fix(sdk): speed up import time and fix `pkg_resources` DeprecationWarning
  wandb/apis/public.py
Labels: cc-fix

#5954 chore(sdk): bump sdk version to 0.15.8dev
  CHANGELOG.md
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5891 docs(sdk): update `README.md` to unify the spelling of `Hugging Face`
  README.md
Labels: cc-docs

#4344 feat(sdk): speed up iterating over directory in the `filtered_dir` function by also filtering by directories
  wandb/sdk/lib/filenames.py
Labels: contrib, cc-feat

#5956 test(sdk): skip broken tests and fix CI
  requirements_dev.txt
  tests/functional_tests/t0_main/console/t1_tqdm_wrap.yea
  tests/functional_tests/t0_main/console/t2_tqdm_nested_wrap.yea
  tests/functional_tests/t0_main/console/t5_tqdm_post_finish.yea
  tests/functional_tests/t0_main/core/t5_log_media.py
  tests/functional_tests/t0_main/core/t6_log_images_win.yea
  tests/functional_tests/t0_main/kfp/kfp-pipeline-pytorch.yea
  tests/functional_tests/t0_main/kfp/kfp-pipeline-simple.yea
  tests/functional_tests/t0_main/kfp/kfp-pipeline-sklearn.yea
  tests/functional_tests/t0_main/lightgbm/t1_regression.yea
  tests/functional_tests/t0_main/lightgbm/t2_regression.yea
  tests/functional_tests/t0_main/magic/t1_mnist_convnet.yea
  tests/functional_tests/t0_main/tensorflow/t1_tensorflow_log.yea
  tests/functional_tests/t0_main/tensorflow/t2_tensorflow_hook.yea
  tests/functional_tests/t0_main/torch/t1_sparse_tensors.yea
  tests/functional_tests/t0_main/xgboost/xgboost_clf.yea
Labels: cc-test

#5942 feat(launch): Check if job ingredients exist before making job
  wandb/sdk/internal/job_builder.py
Labels: cc-feat

#5945 feat(launch): Gracefully handle Kubernetes 404 error
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-feat

#5978 chore(launch): try/catch local docker image pull
  wandb/sdk/launch/runner/local_container.py
Labels: cc-chore
