Repository wandb/wandb, pull requests merged in 2023-11, with the labels that each got.

#6432 feat(artifacts): nexus artifact file download
  nexus/api/graphql/query_artifact_by_id.graphql
  nexus/api/graphql/query_artifact_by_name.graphql
  nexus/api/graphql/query_artifact_file_urls.graphql
  nexus/api/graphql/query_artifact_manifest.graphql
  nexus/internal/filetransfer/file_transfer_manager.go
  nexus/internal/gql/gql_gen.go
  nexus/pkg/artifacts/downloader.go
  nexus/pkg/artifacts/file_path_utils.go
  nexus/pkg/artifacts/manifest.go
  nexus/pkg/artifacts/name_utils.go
  nexus/pkg/artifacts/reference_artifacts_utils.go
  nexus/pkg/env/artifacts.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
  nexus/pkg/utils/hash.go
  wandb/sdk/artifacts/artifact.py
Labels: cc-feat

#6531 refactor(artifacts): replace communicate call for artifact download with deliver
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
Labels: cc-refactor

#6275 feat(artifacts): set up artifact downloads to use sdk nexus core
  nexus/api/graphql/query_artifact_by_id.graphql
  nexus/api/graphql/query_artifact_by_name.graphql
  nexus/api/graphql/query_artifact_file_urls.graphql
  nexus/api/graphql/query_artifact_manifest.graphql
  nexus/internal/filetransfer/file_transfer_manager.go
  nexus/internal/gql/gql_gen.go
  nexus/pkg/artifacts/downloader.go
  nexus/pkg/artifacts/file_path_utils.go
  nexus/pkg/artifacts/manifest.go
  nexus/pkg/artifacts/name_utils.go
  nexus/pkg/artifacts/reference_artifacts_utils.go
  nexus/pkg/env/artifacts.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
  nexus/pkg/service/wandb_internal.pb.go
  nexus/pkg/utils/hash.go
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.yea
  tests/functional_tests/t0_main/keras/keras_subclassed_test_tf_2_6.yea
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests_old/test_cli.py
  tests/pytest_tests/unit_tests_old/test_public_api.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
Labels: cc-feat

#6525 chore(launch): logging slightly less
  wandb/sdk/internal/job_builder.py
Labels: cc-chore

#6503 fix(sdk): hook_handle being set to list instead of dict on unhook
  wandb/wandb_torch.py
Labels: cc-fix

#6518 feat(nexus): add file upload progress and make completion callback a list of callbacks
  nexus/internal/clients/clients.go
  nexus/internal/filetransfer/file_transfer_default.go
  nexus/internal/filetransfer/file_transfer_manager.go
  nexus/internal/filetransfer/tasks.go
  nexus/pkg/artifacts/downloader.go
  nexus/pkg/artifacts/saver.go
  nexus/pkg/server/files.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
  nexus/pkg/service/wandb_internal.pb.go
  tests/pytest_tests/system_tests/test_notebooks/test_notebooks.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/lib/printer.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#6537 fix(launch): verify gcp credentials before creating vertex job
  tests/pytest_tests/system_tests/test_launch/test_launch_vertex.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_vertex.py
  wandb/sdk/launch/runner/vertex_runner.py
Labels: cc-fix

#6508 fix(launch): add load option to docker buildx
  tests/pytest_tests/unit_tests/test_docker.py
  wandb/docker/__init__.py
Labels: cc-fix

#6538 chore(nexus): bump version and update readme for 0.17.0b1 release
  .bumpversion.nexus.cfg
  .bumpversion.wandb.cfg
  .circleci/config.yml
  .codecov.yml
  nexus/README.md
  nexus/internal/version/version.go
  nexus/setup.py
  nexus/wandb_core/__init__.py
  noxfile.py
  pyproject.toml
  wandb/__init__.py
Labels: cc-chore

#6543 feat(launch): add wandb.ai/run-id label to jobs
  wandb/sdk/launch/runner/kubernetes_monitor.py
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/sagemaker_runner.py
  wandb/sdk/launch/runner/vertex_runner.py
Labels: cc-feat

#6551 test(sdk): update jax to use python > 3.7
  .circleci/config.yml
  .codecov.yml
  .coveragerc
  requirements_dev.txt
  tests/functional_tests/t0_main/xgboost/xgboost_clf.yea
  tests/functional_tests/t0_main/xgboost/xgboost_clf_old.yea
  tests/functional_tests/t0_main/xgboost/xgboost_reg.yea
  tests/pytest_tests/unit_tests/test_util.py
Labels: cc-test

#6535 fix(artifacts): fix perf regressions in artifact downloads and fix file download location
  tests/pytest_tests/unit_tests_old/test_cli.py
  tests/pytest_tests/unit_tests_old/test_public_api.py
  wandb/env.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifacts_cache.py
Labels: cc-fix

#6532 fix(sdk): add warning when `log_code` can't locate any files
  wandb/sdk/wandb_run.py
Labels: cc-fix

#6563 fix(sdk): adjust ipython hooks for v8.17
  wandb/sdk/wandb_init.py
Labels: cc-fix

#6564 chore(sdk): bump version to 0.16.1.dev1 and update changelog
  .bumpversion.wandb.cfg
  .github/workflows/release-core.yml
  .github/workflows/release-sdk.yml
  CHANGELOG.md
  wandb/__init__.py
Labels: cc-chore

#6549 test(sdk): move from old to new and re-org
  .circleci/config.yml
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_artifacts/test_public_api.py
  tests/pytest_tests/system_tests/test_core/test_file_stream_internal.py
  tests/pytest_tests/system_tests/test_core/test_metric_internal.py
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  tests/pytest_tests/system_tests/test_core/test_sender.py
  tests/pytest_tests/system_tests/test_core/test_wandb_init.py
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
  tests/pytest_tests/system_tests/test_core/test_wandb_settings.py
  tests/pytest_tests/system_tests/test_importers/test_report_api.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_cli.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_public_api.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_data_types.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_wandb_run.py
  tests/pytest_tests/unit_tests_old/test_core/internal_update_test.py
  tests/pytest_tests/unit_tests_old/test_core/test_cli.py
  tests/pytest_tests/unit_tests_old/test_core/test_file_stream.py
  tests/pytest_tests/unit_tests_old/test_core/test_file_upload.py
  tests/pytest_tests/unit_tests_old/test_core/test_offline_sync.py
  tests/pytest_tests/unit_tests_old/test_core/test_public_api.py
  tests/pytest_tests/unit_tests_old/test_core/test_tb_watcher.py
  tests/pytest_tests/unit_tests_old/test_core/test_wandb.py
  tests/pytest_tests/unit_tests_old/test_footer.py
  tests/pytest_tests/unit_tests_old/test_internal_api.py
  tests/pytest_tests/unit_tests_old/test_launch/__init__.py
  tests/pytest_tests/unit_tests_old/test_launch/test_cli.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_aws.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_docker.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_jobs.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_local_process.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_utils.py
  tests/pytest_tests/unit_tests_old/test_launch/test_public_api.py
  tests/pytest_tests/unit_tests_old/test_launch/test_wandb_agent.py
  tests/pytest_tests/unit_tests_old/test_launch/test_wandb_controller.py
  tests/pytest_tests/unit_tests_old/test_launch/test_wandb_run.py
  tests/pytest_tests/unit_tests_old/test_logging.py
  tests/pytest_tests/unit_tests_old/test_metric_internal.py
  tests/pytest_tests/unit_tests_old/test_public_api.py
  tests/pytest_tests/unit_tests_old/test_runtime.py
  tests/pytest_tests/unit_tests_old/test_sender.py
  tests/pytest_tests/unit_tests_old/test_summary.py
  tests/pytest_tests/unit_tests_old/test_time_resolution.py
  tests/pytest_tests/unit_tests_old/test_wandb.py
  wandb/testing/relay.py
Labels: cc-test

#6560 chore(launch): add `author` macro for use in resource configs
  tests/pytest_tests/unit_tests/test_launch/test_project/test_project.py
  wandb/sdk/launch/_project_spec.py
Labels: cc-chore

#6545 refactor(launch): fetch git repos with protocol in remote url
  tests/pytest_tests/system_tests/test_launch/test_github_reference.py
  tests/pytest_tests/system_tests/test_launch/test_job.py
  wandb/cli/cli.py
  wandb/sdk/launch/create_job.py
  wandb/sdk/launch/git_reference.py
  wandb/sdk/launch/github_reference.py
  wandb/sdk/launch/utils.py
Labels: cc-refactor

#6550 chore(launch): --log-file flag for wandb launch-agent to set internal log destination
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  wandb/cli/cli.py
  wandb/sdk/launch/_launch.py
Labels: cc-chore

#6544 perf(artifacts): remove recursive download
  nexus/api/graphql/query_artifact_by_id.graphql
  nexus/internal/gql/gql_gen.go
  nexus/pkg/artifacts/downloader.go
  nexus/pkg/artifacts/reference_artifacts_utils.go
  nexus/pkg/server/sender.go
  nexus/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/interface/interface.py
Labels: cc-perf

#6448 refactor(artifacts): rename get_path() to get_entry()
  tests/pytest_tests/system_tests/test_artifacts/test_misc2.py
  tests/pytest_tests/system_tests/test_artifacts/test_object_references.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_public_api.py
  tests/standalone_tests/dsviz_demo.py
  wandb/data_types.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
  wandb/sdk/artifacts/storage_handlers/wb_artifact_handler.py
  wandb/sdk/data_types/base_types/media.py
  wandb/sdk/data_types/base_types/wb_value.py
  wandb/sdk/data_types/helper_types/image_mask.py
  wandb/sdk/data_types/html.py
  wandb/sdk/data_types/image.py
  wandb/sdk/data_types/saved_model.py
  wandb/sdk/interface/interface.py
Labels: cc-refactor

#6569 fix(nexus): make offline sync work properly
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
  nexus/pkg/server/timer.go
  nexus/pkg/server/writer.go
  tools/inspect-tool.py
  tox.ini
  wandb/sdk/internal/writer.py
Labels: cc-fix

#6548 fix(launch): Fix run existence check to not depend on files being uploaded in the run
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#6570 feat(nexus): add debounce summary in handler
  nexus/pkg/server/handler.go
  nexus/pkg/server/history.go
  nexus/pkg/server/sender.go
Labels: cc-feat

#6559 refactor(nexus): remove unnecessary code from artifact downloads
  nexus/api/graphql/query_artifact_by_name.graphql
  nexus/api/graphql/query_artifact_manifest.graphql
  nexus/internal/gql/gql_gen.go
  nexus/pkg/artifacts/downloader.go
  nexus/pkg/artifacts/file_path_utils.go
  nexus/pkg/artifacts/manifest.go
  nexus/pkg/artifacts/name_utils.go
  nexus/pkg/env/artifacts.go
  nexus/pkg/server/sender.go
  nexus/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/interface/interface.py
Labels: cc-refactor

#6577 chore(artifacts): update Nexus readme
  nexus/README.md
Labels: cc-chore

#6575 chore(nexus): release 0.17.0b2
  .bumpversion.nexus.cfg
  nexus/README.md
  nexus/internal/version/version.go
  nexus/setup.py
  nexus/wandb_core/__init__.py
  noxfile.py
  pyproject.toml
  wandb/__init__.py
Labels: cc-chore

#6581 fix(launch): gcp storage uri verifaction failed due to improper async wrapping
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_gcp.py
  wandb/sdk/launch/environment/gcp_environment.py
Labels: cc-fix

#6586 docs(integrations): fix doc-string typo in a keras callback
  wandb/integration/keras/callbacks/model_checkpoint.py
Labels: contrib, cc-docs

#6596 test(sdk): disable broken functional llm tests
  .circleci/config.yml
  .codecov.yml
  .coveragerc
Labels: cc-test

#6597 refactor(nexus): improve internal stream logic and interfaces
  nexus/internal/debounce/debounce.go
  nexus/pkg/server/connection.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/stream.go
Labels: cc-refactor

#6598 chore(sdk): update pr-title-bot to use openai v>1
  .github/workflows/fix-pr-title.yml
  tools/pr-title-bot.py
Labels: cc-chore

#6595 test(nexus): test history handle
  nexus/pkg/server/handler.go
  nexus/pkg/server/handler_test.go
  nexus/pkg/server/history.go
  nexus/pkg/server/history_test.go
  tools/pr-title-bot.py
Labels: cc-test

#6578 fix(sdk): updating summary with nested dicts now doesn't throw an error
  tests/pytest_tests/unit_tests/test_wandb_summary.py
  wandb/old/summary.py
Labels: cc-fix

#6573 chore(launch): Launch runner fails when env is null
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-chore

#6599 chore(launch): Add prioritization mode to create_run_queue
  tests/pytest_tests/unit_tests/test_launch/test_internal_api.py
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
Labels: cc-chore

#6605 feat(integrations): fix bug in ultralytics import and version pinning
  wandb/integration/ultralytics/callback.py
Labels: cc-feat

#6600 test(nexus): generate coverage reports for system tests
  .circleci/config.yml
  .codecov.yml
  .coveragerc
  nexus/setup.py
  noxfile.py
  tox.ini
Labels: cc-test

#6607 test(sdk): clean up coverage for pytest
  .circleci/config.yml
  .coveragerc
  pyproject.toml
  requirements_dev.txt
  requirements_test.txt
  tox.ini
Labels: cc-test

#6602 feat(launch): Support template variables when queueing launch runs
  tests/pytest_tests/system_tests/test_core/test_public_api.py
  tests/pytest_tests/system_tests/test_launch/test_job.py
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/system_tests/tests_launch/test_public_api.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_jobs.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/_launch_add.py
Labels: cc-feat

#6610 fix(launch): Add prioritization mode to RunQueue create
  wandb/apis/public.py
Labels: cc-fix

#6557 fix(sdk): add size limit on the file stream queue
  wandb/cli/cli.py
  wandb/sync/sync.py
Labels: cc-fix

#6609 chore(nexus): use segmentio's json package instead of stdlib's
  nexus/go.mod
  nexus/go.sum
  nexus/internal/nexuslib/summarylib.go
  nexus/internal/nexustest/nexustest.go
  nexus/pkg/artifacts/manifest.go
  nexus/pkg/filestream/filestream_test.go
  nexus/pkg/filestream/loop_process.go
  nexus/pkg/filestream/loop_transmit.go
  nexus/pkg/filestream/loop_transmit_test.go
  nexus/pkg/gowandb/run.go
  nexus/pkg/monitor/monitor.go
  nexus/pkg/server/history.go
  nexus/pkg/server/resume.go
  nexus/pkg/server/sender.go
Labels: cc-chore

#6612 chore(launch): Add priority field for pushing to run queue
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/unit_tests/test_launch/test_internal_api.py
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/_launch_add.py
Labels: cc-chore

#6613 chore(nexus): prep for wandb-core roll-out
  .bumpversion.core.cfg
  .github/workflows/release-core.yml
  nexus/README.md
  nexus/docs/contributing.md
  nexus/wandb_core/__init__.py
  pyproject.toml
  tests/pytest_tests/system_tests/test_nexus/conftest.py
  tox.ini
  wandb/__init__.py
  wandb/sdk/service/service.py
  wandb/sdk/wandb_require.py
Labels: cc-chore

#6616 chore(nexus): clean up require codepath
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/service/service.py
  wandb/util.py
Labels: cc-chore

#6618 ci(nexus): turn nexus on in CI by default, phase 1
  .circleci/config.yml
  tests/functional_tests/t0_main/artifacts/log-model.yea
  tests/functional_tests/t0_main/artifacts/use-model.yea
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/system_tests/test_notebooks/test_notebooks.py
  tests/pytest_tests/unit_tests/test_internal_api.py
  tests/pytest_tests/unit_tests/test_launch/test_job.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_cli.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_public_api.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_data_types.py
  tests/pytest_tests/unit_tests_old/test_artifacts/test_wandb_run.py
  tests/pytest_tests/unit_tests_old/test_core/test_wandb.py
  tox.ini
Labels: cc-ci

#6617 chore(launch): misc error message improvements in launch sdk
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_azure.py
  tests/pytest_tests/unit_tests/test_launch/test_environment/test_gcp.py
  wandb/sdk/launch/environment/aws_environment.py
  wandb/sdk/launch/environment/azure_environment.py
  wandb/sdk/launch/environment/gcp_environment.py
Labels: cc-chore

#6572 chore(artifacts): update python docstrings for model APIs
  tests/pytest_tests/system_tests/test_core/test_model_workflow.py
  wandb/sdk/wandb_run.py
Labels: cc-chore

#6629 test(sdk): use asyncio.run instead of homemade solutions, now that we require py37
  tests/pytest_tests/unit_tests/test_internal_api.py
  tests/pytest_tests/unit_tests/test_retry.py
Labels: cc-test

#6628 fix(nexus): create symlink to the server logs in the runs folder
  nexus/cmd/nexus/main.go
  nexus/go.mod
  nexus/go.sum
  nexus/pkg/observability/logging.go
  nexus/pkg/observability/util.go
  nexus/pkg/observability/util_test.go
  nexus/pkg/server/logging.go
  nexus/pkg/server/server.go
  nexus/pkg/server/stream.go
Labels: cc-fix

#6624 feat(nexus): add basic graphql versioning mechanism
  nexus/api/graphql/genqlient.yaml
  nexus/api/graphql/query_viewer.graphql
  nexus/docs/contributing.md
  nexus/internal/gql/gql_gen.go
  nexus/pkg/server/handler.go
  nexus/pkg/server/sender.go
  nexus/scripts/generate-graphql.sh
  noxfile.py
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
Labels: cc-feat

#6619 feat(nexus): add Apple M* GPU stats monitoring
  .github/workflows/release-core.yml
  .vscode/settings.json
  nexus/pkg/monitor/apple/AppleStats
  nexus/pkg/monitor/apple/LICENSE
  nexus/pkg/monitor/apple/Package.swift
  nexus/pkg/monitor/apple/Sources/Store.swift
  nexus/pkg/monitor/apple/Sources/SystemKit.swift
  nexus/pkg/monitor/apple/Sources/constants.swift
  nexus/pkg/monitor/apple/Sources/extensions.swift
  nexus/pkg/monitor/apple/Sources/helpers.swift
  nexus/pkg/monitor/apple/Sources/main.swift
  nexus/pkg/monitor/apple/Sources/protocol.swift
  nexus/pkg/monitor/apple/Sources/smc.swift
  nexus/pkg/monitor/apple/Sources/types.swift
  nexus/pkg/monitor/apple/readme.md
  nexus/pkg/monitor/gpu_apple.go
  nexus/pkg/monitor/monitor.go
  nexus/pkg/service/wandb_internal.pb.go
  nexus/setup.py
  noxfile.py
  src/apple_gpu_stats/README.md
  src/apple_gpu_stats/apple_gpu_stats.xcodeproj/project.pbxproj
  src/apple_gpu_stats/apple_gpu_stats.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  src/apple_gpu_stats/apple_gpu_stats.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  src/apple_gpu_stats/apple_gpu_stats.xcodeproj/xcshareddata/xcschemes/apple_gpu_stats.xcscheme
  src/apple_gpu_stats/apple_gpu_stats/APSL.txt
  src/apple_gpu_stats/apple_gpu_stats/DataSet.h
  src/apple_gpu_stats/apple_gpu_stats/DataSet.m
  src/apple_gpu_stats/apple_gpu_stats/GPUMiner.h
  src/apple_gpu_stats/apple_gpu_stats/GPUMiner.m
  src/apple_gpu_stats/apple_gpu_stats/SMCInterface.h
  src/apple_gpu_stats/apple_gpu_stats/SMCInterface.m
  src/apple_gpu_stats/apple_gpu_stats/SMCSensors.h
  src/apple_gpu_stats/apple_gpu_stats/SMCSensors.m
  src/apple_gpu_stats/apple_gpu_stats/TemperatureMiner.h
  src/apple_gpu_stats/apple_gpu_stats/TemperatureMiner.m
  src/apple_gpu_stats/apple_gpu_stats/definitions.h
  src/apple_gpu_stats/apple_gpu_stats/main.m
  tests/functional_tests/t0_main/mp/03-parent-child.yea
  tests/functional_tests/t0_main/mp/04-pool.yea
  tests/functional_tests/t0_main/mp/05-pool-nofinish.yea
  tests/functional_tests/t0_main/mp/06-1-share-child-base.yea
  tests/functional_tests/t0_main/mp/06-2-share-child-gt-step.yea
  tests/functional_tests/t0_main/mp/06-3-share-child-lt-step.yea
  tests/functional_tests/t0_main/mp/06-4-share-child-synchronize.yea
  tests/functional_tests/t0_main/mp/07-attach.yea
  tests/functional_tests/t0_main/mp/19-1-log-image-sequence.yea
  tests/functional_tests/t0_main/mp/19-2-log-image-sequence-attach.yea
  tests/pytest_tests/unit_tests/test_lib/test_redir.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
Labels: cc-feat

#6641 fix(integrations): tmin vs tmax in wandb/wandb_torch.py::log_tensor_stats
  wandb/wandb_torch.py
Labels: cc-fix

#6644 feat(launch): add helper to load wandb.Config from env vars
  tests/pytest_tests/unit_tests/test_launch/test_util.py
  wandb/sdk/launch/__init__.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#6498 feat(integrations): port OpenAI WandbLogger for openai-python v1.0
  nexus/pkg/service/wandb_telemetry.pb.go
  tests/functional_tests/t0_main/openai/t9_openai_finetuning.py
  tests/functional_tests/t0_main/openai/t9_openai_finetuning.yea
  wandb/integration/openai/__init__.py
  wandb/integration/openai/fine_tune.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
Labels: cc-feat

#6648 feat(integrations): fix version check for openAI WandbLogger
  tests/functional_tests/t0_main/openai/t1_openai_edit.yea
  tests/functional_tests/t0_main/openai/t2_openai_completion.yea
  tests/functional_tests/t0_main/openai/t3_openai_chat_completion.yea
  tests/functional_tests/t0_main/openai/t4_openai_edit_weird_autolog_api_usage.yea
  tests/functional_tests/t0_main/openai/t5_openai_edit_weird_autolog_api_usage_2.yea
  tests/functional_tests/t0_main/openai/t6_openai_edit_async.yea
  tests/functional_tests/t0_main/openai/t7_openai_completion_async.yea
  tests/functional_tests/t0_main/openai/t8_openai_chat_completion_async.yea
  tests/functional_tests/t0_main/openai/t9_openai_finetuning.py
  wandb/integration/openai/__init__.py
  wandb/integration/openai/fine_tuning.py
Labels: cc-feat
