Repository wandb/wandb, pull requests merged in 2023-04, with the labels that each got.

#5275 fix(sdk): Ensure empty string logs as empty string and not list
  tests/pytest_tests/system_tests/test_core/test_wandb.py
  wandb/sdk/data_types/utils.py
Labels: cc-fix

#4810 docs(sdk): add documentation to Object3D for individual methods
  wandb/sdk/data_types/object_3d.py
Labels: cc-docs

#5013 fix(sdk): make run's methods and attributes no-ops for a finished run
  tests/functional_tests/t0_main/console/t5_tqdm_post_finish.py
  tests/functional_tests/t0_main/console/t5_tqdm_post_finish.yea
  tests/pytest_tests/unit_tests/test_wandb_run.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_manager.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#5289 chore(sdk): removing duplicate docstring
  wandb/integration/keras/callbacks/model_checkpoint.py
Labels: cc-chore

#5179 refactor(artifacts): split up interface/artifacts.py
  wandb/sdk/interface/artifacts/__init__.py
  wandb/sdk/interface/artifacts/artifact.py
  wandb/sdk/interface/artifacts/artifact_cache.py
  wandb/sdk/interface/artifacts/artifact_manifest.py
  wandb/sdk/interface/artifacts/artifact_storage.py
Labels: cc-refactor

#5294 chore(artifacts): re-apply changes from #5050
  wandb/sdk/interface/artifacts/artifact_cache.py
Labels: cc-chore

#5276 docs(artifacts): convert docstrings to Google convention
  wandb/sdk/interface/artifacts/artifact_storage.py
Labels: cc-docs

#5144 fix(sdk): fix timeout in `offline` mode when trying to attach to an existing run
  tests/functional_tests/t0_main/offline/t2_multiprocess.py
  wandb/sdk/wandb_init.py
Labels: contrib, cc-fix

#5237 feat(sdk): allow setting of extra headers for the gql client
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#5282 feat(sdk): namespace filters applied by OpenMetrics endpoint consumer
  tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_open_metrics.py
  wandb/sdk/internal/system/assets/open_metrics.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#5193 test(sdk): add/improve tests that ensure StepUpload only calls async methods if settings say to
  tests/pytest_tests/unit_tests/test_step_upload.py
Labels: cc-test

#5171 test(integrations): Added telemetry for diffusers, trl, trlx, langchain, llama-index and stability-idk
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
Labels: cc-test

#5299 chore(sdk): bump to 0.14.2.dev1
  CHANGELOG.md
  pyproject.toml
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5305 revert(sdk): accidental checkin of two fixes without a PR
  wandb/analytics/sentry.py
  wandb/sdk/data_types/plotly.py
  wandb/sdk/data_types/utils.py
Labels: cc-revert

#5306 fix(sdk): fix `wandb sync` regression
  wandb/analytics/sentry.py
  wandb/sdk/data_types/plotly.py
  wandb/sdk/data_types/utils.py
Labels: cc-fix

#5307 chore(sdk): update changelog in main and bump version to 0.14.3.dev1
  CHANGELOG.md
  pyproject.toml
  setup.cfg
  setup.py
  wandb/__init__.py
Labels: cc-chore

#5183 fix(launch): don't assume keys in args and config refer to the same thing
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  wandb/sdk/launch/_project_spec.py
Labels: cc-fix

#5182 refactor(sweeps): sweeps on launch scheduler more intuitive
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_wandb_sweep.py
  wandb/apis/internal.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/scheduler_sweep.py
  wandb/sdk/launch/sweeps/utils.py
Labels: cc-refactor

#5206 refactor(sweeps): new command for launch sweeps
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_cli.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_sweep_cli.py
  tests/pytest_tests/unit_tests/test_util.py
  tests/pytest_tests/unit_tests_old/test_cli.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/agents/pyagent.py
  wandb/cli/cli.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/sweeps/utils.py
  wandb/sdk/wandb_sweep.py
  wandb/util.py
  wandb/wandb_agent.py
  wandb/wandb_controller.py
Labels: cc-refactor

#5159 fix(launch): make ElasticContainerRegistry environment handle "ImageNotFoundException" gracefully
  wandb/sdk/launch/registry/elastic_container_registry.py
Labels: cc-fix

#5320 chore(sdk): add copilot to the PR summary template
  .github/pull_request_template.md
Labels: cc-chore

#5325 chore(sdk): disable codecov from tox envs
  .github/pull_request_template.md
  tox.ini
Labels: cc-chore

#5318 fix(launch): Disable kaniko builder retry
  wandb/sdk/launch/builder/kaniko_builder.py
Labels: cc-fix

#5328 test(sdk): remove the mysql healthcheck in unmock server
  tests/pytest_tests/system_tests/conftest.py
Labels: cc-test

#5297 chore(sdk): pass usedforsecurity=False when possible for FIPS support
  wandb/sdk/data_types/image.py
  wandb/sdk/internal/system/assets/open_metrics.py
  wandb/sdk/lib/hashutil.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-chore

#5330 feat(launch): Allow platform override for docker builder
  tools/build_launch_agent.py
  wandb/docker/__init__.py
  wandb/sdk/launch/builder/docker_builder.py
Labels: cc-feat

#5341 fix(sdk): refine error message for auth error
  wandb/util.py
Labels: cc-fix

#5303 fix(launch): kubernetes runner does not respect override args
  tests/pytest_tests/system_tests/tests_launch/test_launch_cli.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_kubernetes.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_local_container.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_sweep.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py
  wandb/apis/public.py
  wandb/cli/cli.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/utils.py
  wandb/util.py
Labels: cc-fix

#5314 feat(artifacts): get full name of artifact for easier artifact retrieval
  wandb/sdk/interface/artifacts/artifact.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_run.py
Labels: cc-feat

#5268 fix(sweeps): allow attr-dicts as sweeps configs
  tests/pytest_tests/system_tests/test_sweep/test_wandb_sweep.py
  wandb/sdk/internal/internal_api.py
Labels: cc-fix

#5298 chore(launch): fix sentry context to capture launch associated contexts
  wandb/cli/cli.py
Labels: cc-chore

#5293 chore(launch): remove experimental warning when running launch cli commands
  wandb/cli/cli.py
Labels: cc-chore

#5354 chore(launch): Use _wandb_api_key to set env var
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  wandb/sdk/launch/builder/build.py
Labels: cc-chore

#5346 fix(artifacts): checksum the read-only staging copy instead of the original file
  wandb/sdk/internal/artifacts.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-fix

#5355 chore(launch): Fix local container test
  tests/pytest_tests/system_tests/tests_launch/test_launch_local_container.py
Labels: cc-chore

#5288 feat(media): Adds Media Types to Support LangChain
  .circleci/config.yml
  tests/functional_tests/t0_main/langchain/t1_v1.py
  tests/functional_tests/t0_main/langchain/t1_v1.yea
  tox.ini
  wandb/data_types.py
  wandb/integration/langchain/__init__.py
  wandb/integration/langchain/monkeypatch.py
  wandb/integration/langchain/util.py
  wandb/integration/langchain/wandb_tracer.py
  wandb/sdk/data_types/trace_tree.py
Labels: cc-feat

#5356 chore(sdk): fix codecov download as it was removed from pypi
  .circleci/config.yml
  tox.ini
Labels: cc-chore

#5360 chore(integrations): Update docs for LangChain integration
  wandb/integration/langchain/util.py
  wandb/integration/langchain/wandb_tracer.py
  wandb/sdk/data_types/trace_tree.py
Labels: cc-chore

#5363 chore(launch): Add secure mode for launch agent
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#5362 feat(integrations): add autolog for OpenAI's python library
  .circleci/config.yml
  tests/functional_tests/t0_main/langchain/t1_v1.yea
  tests/functional_tests/t0_main/openai/t1_openai_edit.py
  tests/functional_tests/t0_main/openai/t1_openai_edit.yea
  tests/functional_tests/t0_main/openai/t2_openai_completion.py
  tests/functional_tests/t0_main/openai/t2_openai_completion.yea
  tests/functional_tests/t0_main/openai/t3_openai_chat_completion.py
  tests/functional_tests/t0_main/openai/t3_openai_chat_completion.yea
  tox.ini
  wandb/integration/openai/__init__.py
  wandb/integration/openai/openai.py
  wandb/integration/openai/resolver.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/lib/retry.py
  wandb/sdk/lib/timer.py
  wandb/testing/relay.py
Labels: cc-feat

#5369 fix(integrations): add function signature wrapper to patched openai methods
  wandb/integration/openai/openai.py
Labels: cc-fix

#5365 test(sdk): enable codecov for LLM-related tests
  .circleci/config.yml
  .codecov.yml
  .coveragerc
  tox.ini
Labels: cc-test

#5379 fix(launch): Skip getting run info if run completes successfully or is from a different entity
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#5381 fix(integrations): adjust OpenAI autolog public API to improve user experience
  tests/functional_tests/t0_main/openai/t2_openai_completion.py
  tests/functional_tests/t0_main/openai/t4_openai_edit_weird_autolog_api_usage.py
  tests/functional_tests/t0_main/openai/t4_openai_edit_weird_autolog_api_usage.yea
  tests/functional_tests/t0_main/openai/t5_openai_edit_weird_autolog_api_usage_2.py
  tests/functional_tests/t0_main/openai/t5_openai_edit_weird_autolog_api_usage_2.yea
  tox.ini
  wandb/integration/langchain/wandb_tracer.py
  wandb/integration/openai/openai.py
Labels: cc-fix

#5382 chore(sdk): fix UP031 ruff linting error
  wandb/apis/public.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/update.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_config.py
Labels: cc-chore

#5366 feat(artifacts): make default root for artifacts download configurable
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  wandb/apis/public.py
  wandb/env.py
Labels: cc-feat

#5386 docs(sdk): Update README.md
  README.md
Labels: cc-docs

#5389 test(sdk): use pre release for sb3 that replaces gym with gymnasium
  tests/functional_tests/t0_main/sb3/t1_stable_baselines3.py
  tests/functional_tests/t0_main/sb3/t1_stable_baselines3.yea
Labels: cc-test

#5132 fix(sdk): extend dependency on tensorflow-macos to all Python versions
  requirements_dev.txt
Labels: cc-fix

#5281 chore(sdk): try to get ray112 to stop flaking
  tests/functional_tests/t0_main/raytune/t5_colab.py
Labels: cc-chore

#5317 feat(artifacts): add Azure storage handler in SDK
  setup.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/interface/artifacts/artifact.py
  wandb/sdk/interface/artifacts/artifact_storage.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-feat

#5375 fix(artifacts): default to project "uncategorized" instead of "None" when fetching artifacts
  wandb/apis/public.py
Labels: cc-fix

#4745 ci(sdk): run functional tests in CI with python 3.9
  .circleci/config.yml
  .coveragerc
  tests/functional_tests/t0_main/lightning/pl_base.py
  tests/functional_tests/t0_main/lightning/t0_strategy_ddp.py
  tests/functional_tests/t0_main/sklearn/t1_plot_calibration_curve_nonbinary.py
  tests/functional_tests/t0_main/xgboost/xgboost_clf_old.yea
  tests/functional_tests/t0_main/xgboost/xgboost_reg.yea
  tox.ini
Labels: cc-ci

#5301 feat(media): add method to convert wandb.Table to pandas.DataFrame
  wandb/data_types.py
Labels: contrib, cc-feat

#5394 chore(sdk): rename get_df to get_dataframe for converting wandb.Table to pandas.DataFrame
  wandb/data_types.py
Labels: cc-chore

#5230 fix(integrations): add enabled check to gym VideoRecorder
  wandb/integration/gym/__init__.py
Labels: contrib, cc-fix

#5198 feat(integrations): update docstrings of the Keras callbacks
  wandb/integration/keras/callbacks/metrics_logger.py
  wandb/integration/keras/callbacks/model_checkpoint.py
  wandb/integration/keras/callbacks/tables_builder.py
Labels: cc-feat

#5397 test(artifacts): fix flaky tests on windows (re-open file handle)
  tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
Labels: cc-test

#5399 docs(sdk): update the images in `README.md`
  README.md
  docs/README_images/Product_Icons_dark_background/artifacts-dark.svg
  docs/README_images/Product_Icons_dark_background/artifacts_icon.svg
  docs/README_images/Product_Icons_dark_background/evaluations_icon.svg
  docs/README_images/Product_Icons_dark_background/experiments-dark.svg
  docs/README_images/Product_Icons_dark_background/experiments_icon.svg
  docs/README_images/Product_Icons_dark_background/launch-dark.svg
  docs/README_images/Product_Icons_dark_background/launch_icon.svg
  docs/README_images/Product_Icons_dark_background/models-dark.svg
  docs/README_images/Product_Icons_dark_background/models_icon.svg
  docs/README_images/Product_Icons_dark_background/prompts-dark.svg
  docs/README_images/Product_Icons_dark_background/report-dark.svg
  docs/README_images/Product_Icons_dark_background/reports_icon.svg
  docs/README_images/Product_Icons_dark_background/sweeps-dark.svg
  docs/README_images/Product_Icons_dark_background/sweeps_icon.svg
  docs/README_images/Product_Icons_dark_background/tables-dark.svg
  docs/README_images/Product_Icons_dark_background/tables_icon.svg
  docs/README_images/Product_Icons_dark_background/weave-dark.svg
  docs/README_images/Product_Icons_light/artifacts-light.svg
  docs/README_images/Product_Icons_light/artifacts_icon.svg
  docs/README_images/Product_Icons_light/evaluations-light.svg
  docs/README_images/Product_Icons_light/evaluations_icon.svg
  docs/README_images/Product_Icons_light/experiments-light.svg
  docs/README_images/Product_Icons_light/experiments_icon.svg
  docs/README_images/Product_Icons_light/launch-light.svg
  docs/README_images/Product_Icons_light/launch_icon.svg
  docs/README_images/Product_Icons_light/models-light.svg
  docs/README_images/Product_Icons_light/models_icon.svg
  docs/README_images/Product_Icons_light/prompts-light.svg
  docs/README_images/Product_Icons_light/report-light.svg
  docs/README_images/Product_Icons_light/reports_icon.svg
  docs/README_images/Product_Icons_light/sweeps-light.svg
  docs/README_images/Product_Icons_light/sweeps_icon.svg
  docs/README_images/Product_Icons_light/tables-light.svg
  docs/README_images/Product_Icons_light/tables_icon.svg
  docs/README_images/Product_Icons_light/weave-light.svg
  docs/README_images/logo-dark.svg
  docs/README_images/logo-light.svg
Labels: cc-docs

#5321 fix(sdk): update import_hook.py with latest changes in the wrapt repository
  wandb/sdk/lib/import_hooks.py
Labels: cc-fix

#5411 refactor(artifacts): rename internal/artifacts.py to internal/artifact_saver.py
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_saver.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/system_tests/test_core/test_cli_full.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/filesync/step_checksum.py
  wandb/sdk/internal/artifact_saver.py
  wandb/sdk/internal/file_pusher.py
  wandb/sdk/internal/sender.py
  wandb/sdk/wandb_artifacts.py
Labels: cc-refactor

#5417 chore(integrations): add telemetry for LangChain W&B Tracer callback
  tests/functional_tests/t0_main/langchain/t1_v1.yea
  wandb/integration/langchain/wandb_tracer.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/data_types/base_types/media.py
Labels: cc-chore

#5199 chore(launch): manually add author to sweep scheduler
  tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py
  tests/pytest_tests/system_tests/tests_launch/test_launch_sweep.py
  wandb/cli/cli.py
  wandb/sdk/launch/launch.py
  wandb/sdk/launch/launch_add.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/utils.py
  wandb/sdk/launch/utils.py
Labels: cc-chore

#5361 chore(artifacts): disallow creating artifacts with reserved types
  tests/pytest_tests/system_tests/tests_launch/test_launch_run.py
  tests/pytest_tests/unit_tests/test_wandb_artifacts.py
  wandb/sdk/interface/artifacts/artifact.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_run.py
Labels: cc-chore

#5413 fix(launch): fix support for local urls in k8s launch agent
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  wandb/cli/cli.py
  wandb/sdk/launch/launch.py
Labels: cc-fix

#5380 refactor(artifacts): remove duplicate 'name' parameter in _DownloadedArtifactEntry
  tests/pytest_tests/unit_tests/test_saved_model.py
  wandb/apis/public.py
  wandb/sdk/interface/artifacts/artifact_manifest.py
Labels: cc-refactor

#5400 refactor(sdk): consolidate typedefs and use `StrPath` consistently
  tests/pytest_tests/conftest.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tools/generate-tool.py
  wandb/integration/keras/callbacks/model_checkpoint.py
  wandb/integration/langchain/wandb_tracer.py
  wandb/sdk/interface/artifacts/artifact.py
  wandb/sdk/interface/artifacts/artifact_cache.py
  wandb/sdk/interface/artifacts/artifact_manifest.py
  wandb/sdk/interface/artifacts/artifact_storage.py
  wandb/sdk/internal/artifact_saver.py
  wandb/sdk/lib/filesystem.py
  wandb/sdk/lib/hashutil.py
  wandb/sdk/lib/paths.py
  wandb/sdk/wandb_artifacts.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-refactor

#5403 test(artifacts): re-enable flaky test and try to fix the root cause
  tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
Labels: cc-test

#5315 feat(launch): sweeps on launch command args passed as params
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/system_tests/test_sweep/test_wandb_agent.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/utils.py
  wandb/wandb_agent.py
Labels: cc-feat

#5432 test(sdk): add testing enhancements
  .circleci/config.yml
  requirements_dev.txt
  tests/pytest_tests/system_tests/conftest.py
  tox.ini
Labels: cc-test

#4982 fix(sdk): improve notebook environment detection and testing
  .circleci/config.yml
  mypy.ini
  tests/pytest_tests/assets/notebooks/code_saving.ipynb
  tests/pytest_tests/assets/notebooks/ipython_exit.py
  tests/pytest_tests/assets/notebooks/login_timeout.ipynb
  tests/pytest_tests/assets/notebooks/magic.ipynb
  tests/pytest_tests/assets/notebooks/one_cell.ipynb
  tests/pytest_tests/system_tests/test_notebooks/conftest.py
  tests/pytest_tests/system_tests/test_notebooks/test_notebooks.py
  tests/pytest_tests/unit_tests_old/assets/notebooks/setup.ipynb
  tests/pytest_tests/unit_tests_old/conftest.py
  tests/pytest_tests/unit_tests_old/tests_launch/test_launch.py
  tox.ini
  wandb/__init__.py
  wandb/apis/internal.py
  wandb/jupyter.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/internal/internal_api.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/lib/apikey.py
  wandb/sdk/lib/ipython.py
  wandb/sdk/lib/printer.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_login.py
  wandb/sdk/wandb_manager.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
  wandb/util.py
Labels: cc-fix

#5436 fix(sdk): implement recursive isinstance check utility for the Settings object
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#5329 fix(sdk): correctly parse edge cases in OpenMetrics filter definitions in System Monitor
  CONTRIBUTING.md
  tests/pytest_tests/system_tests/test_system_metrics/test_open_metrics.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_gpu.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_gpu_apple.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_ipu.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_open_metrics.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_system_monitor.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_tpu.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_trainium.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/internal/system/assets/open_metrics.py
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#5344 fix(sdk): update debug logs to include SDK's version
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#4874 ci(sdk): upgrade tox to v4
  .circleci/config.yml
  .codecov.yml
  pyproject.toml
  requirements_dev.txt
  tests/pytest_tests/system_tests/test_notebooks/conftest.py
  tools/setup_dev_environment.py
  tox.ini
  wandb/proto/wandb_internal_codegen.py
Labels: cc-ci

#5142 fix(sdk): filter AWS Trainium metrics by local rank if executed with torchrun
  tests/pytest_tests/unit_tests/test_system_metrics/test_trainium.py
  wandb/sdk/internal/system/assets/trainium.py
Labels: cc-fix

#5452 test(sdk): fix broken regression
  tox.ini
Labels: cc-test
