Repository wandb/wandb, pull requests merged in 2024-03, with the labels that each got.

#7080 fix(launch): Fix entrypoint specification when using a Dockerfile.wandb
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/build.py
Labels: cc-fix

#7065 feat(sdk): Respect backpressure headers from backend
  core/internal/api/api.go
  core/internal/api/ratelimitheaders.go
  core/internal/api/ratelimitheaders_test.go
  core/internal/api/ratelimittracker.go
  core/internal/api/ratelimittracker_test.go
  core/internal/api/transport.go
Labels: cc-feat

#6930 chore(sdk): Update container registry in CI
  .circleci/config.yml
Labels: cc-chore

#7056 fix(sdk): fix stream releasing probe handle too early
  wandb/sdk/service/streams.py
Labels: cc-fix

#7087 chore(launch): Fix launch CI image
  .circleci/config.yml
Labels: cc-chore

#7074 chore(launch): Fix repo end to end test, support codePathLocal
  client/src/wandb_internal.rs
  core/pkg/server/handler.go
  core/pkg/service/wandb_settings.pb.go
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.py
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/internal/system/system_info.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_settings.py
Labels: cc-chore

#7079 fix(launch): Always attempt to pull latest image for local container
  wandb/sdk/launch/runner/local_container.py
Labels: cc-fix

#7089 feat(sdk): Rate-limit GraphQL and filestream separately
  core/internal/api/api.go
  core/internal/api/transport.go
Labels: cc-feat

#7083 ci(sdk): Fix up release-core-sdk action
  .github/workflows/release-core.yml
  core/.gitignore
  core/pkg/monitor/apple/winibuild.py
  core/scripts/build/install_go.py
  core/setup.py
  core/winibuild.py
  tools/wini/arch.py
  tools/wini/print.py
  tools/wini/subprocess.py
  tools/wini/wini.py
Labels: cc-ci

#7090 chore(sdk): Remove functions from clients.go
  core/internal/api/api.go
  core/internal/clients/clients.go
  core/internal/filetransfer/file_transfer_default_test.go
  core/pkg/server/sender.go
Labels: cc-chore

#6897 feat(sdk): W&B to W&B Importer
  .circleci/config.yml
  pyproject.toml
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_importers/test_mlflow/__init__.py
  tests/pytest_tests/system_tests/test_importers/test_mlflow/conftest.py
  tests/pytest_tests/system_tests/test_importers/test_mlflow/test_import_mlflow.py
  tests/pytest_tests/system_tests/test_importers/test_wandb/__init__.py
  tests/pytest_tests/system_tests/test_importers/test_wandb/conftest.py
  tests/pytest_tests/system_tests/test_importers/test_wandb/test_wandb.py
  tests/pytest_tests/unit_tests/test_importers/test_wandb_utils.py
  tox.ini
  wandb/apis/importers/__init__.py
  wandb/apis/importers/base.py
  wandb/apis/importers/internals/internal.py
  wandb/apis/importers/internals/protocols.py
  wandb/apis/importers/internals/util.py
  wandb/apis/importers/mlflow.py
  wandb/apis/importers/validation.py
  wandb/apis/importers/wandb.py
  wandb/apis/public/files.py
  wandb/util.py
Labels: cc-feat

#6920 chore(sdk): Update MLFlow Importer to match new importer pattern
  .circleci/config.yml
  tests/pytest_tests/system_tests/test_importers/test_mlflow/conftest.py
  tests/pytest_tests/system_tests/test_importers/test_mlflow/test_import_mlflow.py
  tests/pytest_tests/unit_tests/test_importers/test_mlflow_utils.py
  tox.ini
  wandb/apis/importers/mlflow.py
  wandb/cli/cli.py
Labels: cc-chore

#7099 chore(sdk): bump to dev version (0.16.5.dev1)
  .bumpversion.wandb.cfg
  .github/pull_request_template.md
  .github/release.yml
  .github/workflows/release-core.yml
  CHANGELOG.md
  wandb/__init__.py
Labels: cc-chore

#7100 chore(core): fix security issue in mio
  client/Cargo.lock
  client/Cargo.toml
Labels: cc-chore

#7092 test(core): enable tests that are skipped for wandb-core
  tests/pytest_tests/system_tests/test_core/test_cli_full.py
  tests/pytest_tests/system_tests/test_core/test_footer.py
  tests/pytest_tests/system_tests/test_core/test_sender.py
  tests/pytest_tests/system_tests/test_core/test_wandb_integration.py
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
  tests/pytest_tests/unit_tests_old/test_core/test_wandb.py
Labels: cc-test

#7105 fix(core): make upsert run more robust to nil data
  core/pkg/server/sender.go
  core/pkg/utils/utils.go
Labels: cc-fix

#7104 fix(core): add support for sweeps in upsert run
  .circleci/config.yml
  core/pkg/server/sender.go
  tests/pytest_tests/system_tests/test_core/test_wandb_integration.py
  tests/pytest_tests/system_tests/test_sweep/test_wandb_sweep.py
  wandb/testing/relay.py
Labels: cc-fix

#7106 test(sdk): re-org some system tests that were mis-classified
  tests/pytest_tests/system_tests/test_core/test_wandb.py
  tests/pytest_tests/system_tests/test_launch/test_launch_public_api.py
  tests/pytest_tests/system_tests/test_reports/test_report_api.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_public_api.py
Labels: cc-test

#7109 chore(core): Correctly delete existing file in setup.py
  core/setup.py
Labels: cc-chore

#7110 chore(sdk): Ignore ruff UP032
  pyproject.toml
Labels: cc-chore

#7111 chore(sdk): Disable pytest reruns, as they don't work with xdist
  requirements_test.txt
  tox.ini
Labels: cc-chore

#7103 refactor(core): Settings Go class and documentation
  client/src/wandb_internal.rs
  core/internal/settings/settings.go
  core/pkg/server/connection.go
  core/pkg/server/stream.go
  core/pkg/service/wandb_settings.pb.go
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
Labels: cc-refactor

#7112 refactor(core): Move server/config.go into its own package
  core/internal/runconfig/runconfig.go
  core/internal/runconfig/runconfig_test.go
  core/pkg/server/resume.go
  core/pkg/server/resume_test.go
  core/pkg/server/sender.go
Labels: cc-refactor

#7108 fix(launch): Retry when attempting to create API key Kubernetes secret
  CHANGELOG.md
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#7116 chore(sdk): Kill bad filesystem test
  tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
  wandb/sdk/lib/filesystem.py
Labels: cc-chore

#7117 refactor(sdk): Use parameters directly rather than via `locals()`
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  wandb/sdk/wandb_login.py
  wandb/sdk/wandb_settings.py
Labels: cc-refactor

#7119 chore(sdk): Fix Artifacts test that's broken on Windows
  tests/pytest_tests/unit_tests/test_artifacts/test_artifact_manifest_entry.py
Labels: cc-chore

#7120 chore(sdk): Fix bad test that reads from stdin
  tests/pytest_tests/unit_tests/test_public_api.py
Labels: cc-chore

#7121 chore(sdk): make output log more readable
  pyproject.toml
Labels: cc-chore

#7123 chore(sdk): Fix flaky report test
  tests/pytest_tests/unit_tests/test_reports/test_reports.py
  wandb/apis/reports/v2/interface.py
  wandb/apis/reports/v2/internal.py
Labels: cc-chore

#7125 refactor(sdk): Settings fields => methods
  core/internal/settings/settings.go
  core/pkg/server/connection.go
  core/pkg/server/stream.go
Labels: cc-refactor

#7053 fix(integrations): Fix device assignment in Ultralytics integration
  wandb/integration/ultralytics/callback.py
Labels: cc-fix

#7132 fix(sdk): remove job link and link run to workspace
  CHANGELOG.md
  tests/pytest_tests/system_tests/test_core/test_footer.py
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/sender.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#7051 chore(artifacts): fix functional tests for nexus
  core/README.md
  tests/functional_tests/t0_main/artifacts/link-artifact.py
  tests/functional_tests/t0_main/artifacts/link-artifact.yea
  tests/functional_tests/t0_main/artifacts/link-model-outside-run.py
  tests/functional_tests/t0_main/artifacts/link-model.py
  tests/functional_tests/t0_main/artifacts/link-model.yea
  tests/functional_tests/t0_main/artifacts/log-artifact.py
  tests/functional_tests/t0_main/artifacts/log-artifact.yea
  tests/functional_tests/t0_main/artifacts/public-link-model.py
  tests/functional_tests/t0_main/artifacts/public-link-model.yea
  tests/functional_tests/t0_main/artifacts/use-and-link-model.py
  tests/functional_tests/t0_main/artifacts/use-and-link-model.yea
  tests/functional_tests/t0_main/artifacts/use-model-error.py
  tests/functional_tests/t0_main/artifacts/use-model-outside-run-error.py
  tests/functional_tests/t0_main/artifacts/use-model.py
  tests/functional_tests/t0_main/artifacts/use-model.yea
Labels: cc-chore

#7091 chore(launch): add internal mechanism for filtering run config keys for job inputs
  client/src/wandb_internal.rs
  core/internal/runconfig/runconfig.go
  core/internal/runconfig/runconfig_test.go
  core/pkg/launch/job_builder.go
  core/pkg/launch/job_builder_test.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
Labels: cc-chore

#7140 fix(core): add a service that propagate messages back to the client
  core/pkg/observability/printer.go
  core/pkg/server/handler.go
  core/pkg/server/history.go
  core/pkg/server/sender.go
Labels: cc-fix

#7145 test(launch): test that FilterTree does not mutate original data
  core/internal/runconfig/runconfig_test.go
Labels: cc-test

#7144 docs(launch): correct docstrings related to #7901
  client/src/wandb_internal.rs
  core/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/interface/interface.py
Labels: cc-docs

#7153 chore(sdk): Try fixing watcher.go flakes
  core/internal/watcher/watcher.go
Labels: cc-chore

#7154 chore(sdk): minor clean up of skipped tests
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_run.py
  tests/pytest_tests/system_tests/test_core/test_data_types_full.py
  tests/pytest_tests/system_tests/test_core/test_kfp.py
  tests/pytest_tests/system_tests/test_core/test_offline_sync.py
  tests/pytest_tests/system_tests/test_core/test_wandb.py
  tests/pytest_tests/system_tests/test_importers/test_report_api.py
Labels: cc-chore

#7146 chore(sdk): Better docs for run.save() and improved code
  CHANGELOG.md
  client/.gitignore
  client/src/wandb_internal.rs
  core/pkg/service/wandb_internal.pb.go
  tests/pytest_tests/unit_tests/test_wandb_save.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
Labels: cc-chore

#7155 fix(sdk): add timeout to the `conda` system info command
  CHANGELOG.md
  wandb/sdk/internal/system/system_info.py
Labels: cc-fix

#7158 chore(sdk): remove from changelog internal change
  CHANGELOG.md
Labels: cc-chore

#7161 chore(sdk): disable flaky luanch test
  tests/pytest_tests/unit_tests_old/test_launch/test_launch.py
Labels: cc-chore

#7159 docs(launch): Fix rendering of create_run_queue arguments
  wandb/apis/public/api.py
Labels: cc-docs

#7160 chore(sdk): add telemetry to track usage of step in log and summary modification
  client/src/wandb_internal.rs
  core/pkg/service/wandb_telemetry.pb.go
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/wandb_run.py
Labels: cc-chore

#7163 fix(launch): Fix pushing to run queue when both resource args and template variables are provided
  wandb/sdk/launch/utils.py
Labels: cc-fix

#7142 feat(artifacts): Add storage policy while adding files to artifacts
  CHANGELOG.md
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-feat

#7098 feat(artifacts): Make caching optional while uploading artifact files
  CHANGELOG.md
  client/src/wandb_internal.rs
  core/pkg/service/wandb_internal.pb.go
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_cli.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/unit_tests/test_artifacts/test_artifact_manifest_entry.py
  wandb/cli/cli.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
  wandb/sdk/artifacts/artifact_manifests/artifact_manifest_v1.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
  wandb/sdk/interface/interface.py
  wandb/sdk/internal/sender.py
Labels: cc-feat

#7143 chore(artifacts): delete staging files while caching
  CHANGELOG.md
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
Labels: cc-chore

#7035 docs(artifacts): fix documentation for add_reference params checksum and max_objects, increase max_objects
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/storage_handler.py
Labels: cc-docs

#7171 chore(sdk): Create FakeFileTransferManager for tests
  core/internal/filetransfer/file_transfer_manager.go
  core/internal/filetransfertest/filetransfertest.go
  core/pkg/artifacts/downloader.go
  core/pkg/artifacts/saver.go
  core/pkg/server/sender.go
Labels: cc-chore

#7180 chore(sdk): Document Settings files_dir
  client/src/wandb_internal.rs
  core/internal/settings/settings.go
  core/pkg/service/wandb_settings.pb.go
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
Labels: cc-chore

#7181 chore(core): Create gqlmock
  core/internal/gqlmock/gqlmock.go
  core/internal/gqlmock/gqlmock_test.go
  core/internal/gqlmock/matchers.go
Labels: cc-chore

#7185 chore(sdk): Don't assert on time passed in test_wandb_login.py
  tests/pytest_tests/unit_tests/test_wandb_login.py
Labels: cc-chore

#7167 docs(sdk): fix a typo in an error message
  wandb/agents/pyagent.py
Labels: contrib, cc-docs

#7184 chore(sdk): Document Settings._offline
  client/src/wandb_internal.rs
  core/internal/settings/settings.go
  core/pkg/service/wandb_settings.pb.go
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
Labels: cc-chore

#7189 chore(sdk): disable flaky importer test
  tests/pytest_tests/system_tests/test_importers/test_wandb/test_wandb.py
Labels: cc-chore

#7192 chore(sdk): Ignore wandb_internal.rs
  client/.gitignore
  client/src/wandb_internal.rs
Labels: cc-chore

#7183 refactor(core): Create "runfiles" package stub with tests
  core/internal/filetransfertest/filetransfertest.go
  core/internal/runfiles/runfiles.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
  core/internal/runfilestest/runfilestest.go
Labels: cc-refactor

#7194 chore(core): Implement runfiles uploading
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
Labels: cc-chore

#7198 chore(sweeps): Move broken sweep tests off of mock live server
  tests/pytest_tests/system_tests/test_sweep/test_wandb_agent_full.py
  tests/pytest_tests/unit_tests_old/test_launch/test_wandb_agent.py
Labels: cc-chore

#7199 chore(sdk): minor clean up of flaky and failing tests
  .circleci/config.yml
  tests/pytest_tests/unit_tests/test_artifacts/__init__.py
  tests/pytest_tests/unit_tests/test_artifacts/saved_model_constructors.py
  tests/pytest_tests/unit_tests/test_artifacts/test_saved_model.py
  tests/pytest_tests/unit_tests/test_keras.py
  tests/pytest_tests/unit_tests/test_system_metrics/test_disk.py
Labels: cc-chore

#7193 chore(launch): Silence job builder unless use explicitly calls create job
  core/pkg/launch/job_builder.go
  core/pkg/launch/job_builder_test.go
  core/pkg/server/sender.go
  tests/pytest_tests/unit_tests/test_job_builder.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/launch/create_job.py
Labels: cc-chore

#7200 chore(core): Inject backend into sender
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-chore

#7141 chore(sdk): add temporary debugging logic for filestream size issues
  wandb/sdk/internal/file_stream.py
Labels: cc-chore

#7202 chore(sdk): fix typing issue in python3.7
  .pre-commit-config.yaml
  wandb/sdk/artifacts/artifact.py
Labels: cc-chore

#7078 feat(sdk): initial run forking sdk
  core/pkg/service/wandb_internal.pb.go
  core/pkg/service/wandb_settings.pb.go
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/unit_tests/test_library_public.py
  tests/pytest_tests/unit_tests/test_run_moment.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/proto/wandb_settings.proto
  wandb/sdk/internal/handler.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/settings_static.py
  wandb/sdk/lib/__init__.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/lib/run_moment.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#7205 refactor(core): Inject filestream into sender
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-refactor

#7206 refactor(core): Inject FileTransferManager into Sender
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-refactor

#7174 fix(core): add network status message
  core/internal/api/api.go
  core/internal/api/transportpeeker.go
  core/pkg/observability/printer.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-fix

#7211 refactor(core): Delete coretest
  core/internal/coretest/coretest.go
  core/internal/gqlmock/assert.go
  core/internal/gqlmock/gqlmock.go
  core/internal/gqlmock/gqlmock_test.go
  core/internal/gqlmock/matchers.go
  core/internal/gqlmock/remarshall.go
  core/internal/gqltest/generate.go
  core/internal/gqltest/gqltest_gen.go
  core/pkg/server/sender_test.go
Labels: cc-refactor

#7209 chore(sdk): skip broken model registry tests
  tests/pytest_tests/unit_tests/test_artifacts/test_saved_model.py
Labels: cc-chore

#7208 refactor(core): Replace FileTransferInfoRequest
  core/internal/filetransfer/file_transfer_default.go
  core/internal/filetransfer/file_transfer_default_test.go
  core/internal/filetransfer/file_transfer_manager.go
  core/internal/filetransfer/file_transfer_stats.go
  core/internal/filetransfer/run_file_kind.go
  core/internal/filetransfer/tasks.go
  core/internal/runfiles/uploader.go
  core/pkg/artifacts/downloader.go
  core/pkg/artifacts/saver.go
  core/pkg/server/files.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
  core/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
Labels: cc-refactor

#7218 chore(core): upgrade all pkg to use the latest
  core/go.mod
  core/go.sum
Labels: cc-chore

#7219 chore(core): minor clean up
  core/internal/runconfig/runconfig.go
  core/pkg/observability/printer.go
Labels: cc-chore

#7226 fix(core): symlink to resolved path rather than relative path
  core/setup.py
Labels: cc-fix

#7225 fix(core): Don't retry when trying to upload a directory
  core/internal/filetransfer/file_transfer_default.go
  core/internal/filetransfer/file_transfer_retry_policy.go
  core/pkg/server/stream_init.go
Labels: cc-fix

#7221 refactor(core): Inject GraphQL client into sender
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-refactor

#7220 chore(core): Support run.save(policy="live") in 'runfiles' package
  core/go.mod
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
Labels: cc-chore

#7172 chore(artifacts): make 'policy' choice option for artifact cli's put method
  CHANGELOG.md
  wandb/cli/cli.py
  wandb/sdk/artifacts/artifact_saver.py
Labels: cc-chore

#7224 chore(sdk): remove deleted files from manifest
  MANIFEST.in
Labels: cc-chore

#7232 feat(core): add support for stop status
  core/api/graphql/query_run_stop_status.graphql
  core/internal/gql/gql_gen.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
Labels: cc-feat

#7229 chore(sdk): Document Settings.ignore_globs
  core/internal/settings/settings.go
  core/pkg/service/wandb_settings.pb.go
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
Labels: cc-chore

#7230 chore(core): Don't upload ignored files in runfiles
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
Labels: cc-chore

#7222 refactor(core): Use new runfiles code
  core/internal/runfiles/uploader.go
  core/pkg/server/files.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-refactor

#7126 feat(launch): Add verbosity levels to the launch agent
  CHANGELOG.md
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch.py
  wandb/cli/cli.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/agent/config.py
Labels: cc-feat

#7139 fix(launch): `--entrypoint` expects an executable when creating a job from the CLI
  tests/pytest_tests/system_tests/test_launch/test_job.py
  tests/pytest_tests/unit_tests/test_launch/test_create_job.py
  wandb/cli/cli.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/create_job.py
  wandb/sdk/launch/utils.py
Labels: cc-fix

#7233 chore(core): Correctly track file categories in runfiles
  core/internal/runfiles/runfiles.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
Labels: cc-chore

#7240 chore(sdk): Document relay_server fixture a tiny bit more
  tests/pytest_tests/system_tests/conftest.py
Labels: cc-chore

#7246 chore(sdk): Skip orjson version 3.10.0
  pyproject.toml
Labels: cc-chore

#7247 chore(sdk): Revert orjson constraint
  pyproject.toml
Labels: cc-chore

#7239 chore(launch): make KubernetesMonitor error more verbose
  wandb/sdk/launch/runner/kubernetes_monitor.py
Labels: cc-chore

#7241 fix(core): Fix run.save() end behavior in Nexus
  core/internal/runfiles/uploader.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  tests/pytest_tests/system_tests/test_core/test_wandb_save.py
Labels: cc-fix

#7248 refactor(sdk): Move AppleStats to top-level directory
  .gitignore
  apple_stats/.gitignore
  apple_stats/LICENSE
  apple_stats/Package.swift
  apple_stats/Sources/Store.swift
  apple_stats/Sources/SystemKit.swift
  apple_stats/Sources/constants.swift
  apple_stats/Sources/extensions.swift
  apple_stats/Sources/helpers.swift
  apple_stats/Sources/main.swift
  apple_stats/Sources/protocol.swift
  apple_stats/Sources/smc.swift
  apple_stats/Sources/types.swift
  apple_stats/readme.md
  apple_stats/winibuild.py
  core/pkg/monitor/apple/AppleStats
  tools/wini/wini.py
Labels: cc-refactor

#7242 fix(core): Correctly track total bytes in run.save()
  core/internal/filetransfer/file_transfer_stats.go
Labels: cc-fix

#7235 refactor(sdk): Expand glob before passing to internal process
  tests/pytest_tests/unit_tests/test_wandb_save.py
  wandb/sdk/wandb_run.py
Labels: cc-refactor

#7249 test(sdk): update deprecated tensorflow syntax in functional test
  tests/functional_tests/t0_main/mp/13-synctb-gradienttape.py
Labels: cc-test

#7234 refactor(core): first pass to organize all messages
  .circleci/config.yml
  core/pkg/server/handler.go
  core/pkg/server/metric.go
  core/pkg/server/sender.go
  core/pkg/server/writer.go
Labels: cc-refactor

#7257 chore(sdk): fix py37 failures
  wandb/sdk/lib/run_moment.py
Labels: cc-chore

#7253 chore(sdk): Remove unused nox session for AppleStats
  noxfile.py
Labels: cc-chore

#7258 chore(launch): Fix polling sleep falsey check
  wandb/sdk/launch/sweeps/scheduler.py
Labels: cc-chore

#7243 fix(core): hack work around to deal with implicit shut down
  core/pkg/server/connection.go
Labels: cc-fix

#7259 chore(core): Move wandb-core metadata to pyproject.toml
  .bumpversion.core.cfg
  core/pyproject.toml
  core/setup.py
Labels: cc-chore

#7261 fix(sdk): Correctly handle run.save() for files in the run directory
  CHANGELOG.md
  tests/pytest_tests/unit_tests/test_wandb_save.py
  wandb/sdk/wandb_run.py
Labels: cc-fix
