Repository wandb/wandb, pull requests merged in 2024-05, with the labels that each got.

#7519 docs(public-api): make docstrings for public api exists functions clearer
  wandb/apis/public/api.py
Labels: cc-docs

#7521 fix(launch): remove trailing ')' from job version name
  wandb/sdk/internal/job_builder.py
Labels: cc-fix

#7496 chore(launch): make job input handlers callable before `wandb.init`
  tests/pytest_tests/unit_tests/test_launch/test_inputs/test_internal.py
  wandb/sdk/launch/inputs/internal.py
  wandb/sdk/wandb_run.py
Labels: cc-chore

#7525 docs(public-api): make `name` argument clearer in exists functions
  wandb/apis/public/api.py
Labels: cc-docs

#7530 fix(core): Log error in CaptureFatal
  core/pkg/observability/logging.go
Labels: cc-fix

#7532 docs(sdk): update comment on unresolved symbols when building with cgo
  core/hatch.py
Labels: cc-docs

#7537 ci(sdk): reduce parallelism in ci
  .circleci/config.yml
Labels: cc-ci

#7520 fix(core): handle keepalive messages during shutdown
  core/pkg/server/stream.go
Labels: cc-fix

#7533 fix(launch): correct malformed inputs section in wandb-job.json if saving inputs to metadata
  core/pkg/launch/job_builder.go
  core/pkg/launch/job_builder_test.go
Labels: cc-fix

#7526 refactor(core): clean up the server shutdown path
  core/cmd/wandb-core/main.go
  core/pkg/server/connection.go
  core/pkg/server/sender.go
  core/pkg/server/server.go
  core/pkg/server/stream.go
Labels: cc-refactor

#7540 fix(launch): look in the right place for `requirements.frozen.txt`
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  wandb/sdk/launch/builder/build.py
Labels: cc-fix

#7539 fix(sweeps): unbork launch specs with placeholder uris for sweep schedulers
  tests/pytest_tests/unit_tests/test_launch/test_project/test_project.py
  wandb/sdk/launch/_project_spec.py
Labels: cc-fix

#7543 refactor(sdk): Use open() in context manager in test_hashutil.py
  tests/pytest_tests/unit_tests/test_lib/test_hashutil.py
Labels: cc-refactor

#7531 refactor(core): Delete unused logging methods
  core/pkg/observability/logging.go
Labels: cc-refactor

#7527 refactor(core): Rewrite filestream_test.go
  core/internal/apitest/apitest.go
  core/pkg/filestream/filestream_test.go
Labels: cc-refactor

#7517 feat(core): Print error in terminal if filestream breaks
  core/pkg/filestream/filestream.go
  core/pkg/filestream/filestream_test.go
  core/pkg/filestreamtest/filestreamtest.go
  core/pkg/server/handler.go
  core/pkg/server/handler_test.go
  core/pkg/server/stream.go
Labels: cc-feat

#7541 refactor(public-api): Use less intrusive default entity query
  wandb/apis/public/api.py
Labels: cc-refactor

#7513 fix(core): remove duplicate summary lines in filestream
  core/pkg/filestream/collector.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
Labels: cc-fix

#7529 fix(launch): pass build context and dockerfile through partial job
  core/pkg/launch/job_builder.go
  core/pkg/launch/job_builder_test.go
  core/pkg/service/wandb_internal.pb.go
  tests/pytest_tests/system_tests/test_launch/test_job.py
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/interface/interface.py
Labels: cc-fix

#7466 ci(sdk): Toggle "wandb-core" in pytest; remove from tox/nox/CircleCI
  .circleci/config.yml
  .gitignore
  noxfile.py
  tests/pytest_tests/conftest.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  tests/pytest_tests/unit_tests/test_data_types.py
  tests/pytest_tests/unit_tests_old/test_core/test_cli.py
  tox.ini
Labels: cc-ci

#7497 feat(launch): job input management sdk
  tests/pytest_tests/system_tests/test_launch/test_launch_manage.py
  wandb/sdk/launch/__init__.py
  wandb/sdk/launch/inputs/manage.py
Labels: cc-feat

#7523 chore(sdk): add benchmark tool to demonstrate core wins
  tools/bench/_load_profiles.py
  tools/bench/_timing.py
  tools/bench/bench.md
  tools/bench/bench.py
Labels: cc-chore

#7535 fix(core): shutdown core process if parent process exits
  core/cmd/wandb-core/main.go
  core/internal/processlib/processlib_linux.go
  core/internal/processlib/processlib_notlinux.go
  core/pkg/server/server.go
Labels: cc-fix

#7528 feat(artifacts): add save() method on ArtifactCollection to allow persisting changes
  CHANGELOG.md
  core/pkg/service/wandb_telemetry.pb.go
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  wandb/apis/public/artifacts.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_deprecated.py
  wandb/proto/wandb_telemetry.proto
Labels: cc-feat
