Repository wandb/wandb, pull requests merged in 2024-04, with the labels that each got.

#7201 chore(artifacts): handle nullable project on artifact collection
  CHANGELOG.md
  wandb/sdk/artifacts/artifact.py
Labels: cc-chore

#7276 fix(sdk): add project link to the footer
  CHANGELOG.md
  tests/pytest_tests/system_tests/test_core/test_footer.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#7264 feat(core): Don't reupload files that have already been uploaded
  core/internal/runfiles/debounced_transfer.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
Labels: cc-feat

#7265 refactor(core): Only upload requested files at the end of the run
  core/internal/runfiles/runfiles.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
Labels: cc-refactor

#7150 fix(integrations): handling of Error type in OpenAI fine-tune integration
  CHANGELOG.md
  wandb/integration/openai/fine_tuning.py
Labels: cc-fix

#7282 fix(core): Fix a race condition caused by watcher in runfiles
  core/internal/runfiles/uploader.go
Labels: cc-fix

#7277 chore(sdk): update ruff config files
  pyproject.toml
  tests/ruff.toml
  tools/ruff.toml
Labels: cc-chore

#7238 chore(launch): Make clear to users where to find logs when kaniko job fails
  wandb/sdk/launch/builder/kaniko_builder.py
Labels: cc-chore

#7283 fix(core): Raise the default rate limit
  core/internal/api/api.go
  core/internal/api/transport.go
Labels: cc-fix

#7281 feat(launch): Allow overriding stopped run timeout
  CHANGELOG.md
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/agent/config.py
Labels: cc-feat

#7250 refactor(sdk): Build universal AppleStats binary
  .github/workflows/release-core.yml
  apple_stats/winibuild.py
  tools/wini/wini.py
Labels: cc-refactor

#7285 fix(launch): Make partial job download fail verbosely
  CHANGELOG.md
  wandb/sdk/interface/interface.py
Labels: cc-fix

#7280 fix(launch): wandb.login causes runs to not be associated in launch queue table
  CHANGELOG.md
  tests/pytest_tests/system_tests/test_launch/test_launch.py
  wandb/sdk/wandb_init.py
Labels: cc-fix

#7286 fix(core): Avoid concurrent map read and write
  core/internal/runfiles/uploader.go
Labels: cc-fix

#7293 chore(core): Fix incorrect changelog entries
  CHANGELOG.md
Labels: cc-chore

#7287 feat(sdk): allow to disable version check on startup time
  CHANGELOG.md
  core/pkg/service/wandb_settings.pb.go
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#7296 chore(sdk): bump version to 0.16.7.dev1
  .bumpversion.wandb.cfg
  CHANGELOG.md
  wandb/__init__.py
Labels: cc-chore

#7294 chore(sdk): update owners for manifest and changelog
  .github/CODEOWNERS
Labels: cc-chore

#7295 chore(launch): improve validation of registry uris in agent config
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_config.py
  wandb/sdk/launch/agent/config.py
  wandb/sdk/launch/utils.py
Labels: cc-chore

#7164 fix(core): use package that support nan/inf json serialization (only for history/summary)
  core/go.mod
  core/go.sum
  core/internal/corelib/summarylib.go
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
Labels: cc-fix

#7272 fix(sdk): check for nil http client responses
  CHANGELOG.md
  core/internal/api/api.go
  core/internal/api/logging.go
  core/internal/api/send.go
  core/internal/api/send_test.go
  core/internal/filetransfer/file_transfer_default.go
Labels: cc-fix

#7297 chore(launch): Add Job type, fix typing issues, and have k8s manager use queue driver
  wandb/sdk/launch/agent2/agent.py
  wandb/sdk/launch/agent2/controller.py
  wandb/sdk/launch/agent2/controllers/k8s.py
  wandb/sdk/launch/agent2/controllers/local_container.py
  wandb/sdk/launch/agent2/controllers/util.py
  wandb/sdk/launch/agent2/jobset.py
  wandb/sdk/launch/queue_driver/abstract.py
  wandb/sdk/launch/queue_driver/passthrough.py
  wandb/sdk/launch/queue_driver/standard_queue_driver.py
Labels: cc-chore

#7304 chore(core): Build universal no-op wandb-core wheel
  .github/workflows/release-core.yml
  core/setup.py
  core/wandb_core/__init__.py
  tools/wini/print.py
  tools/wini/subprocess.py
  tools/wini/wini.py
Labels: cc-chore

#7196 fix(sdk): report file upload failures as errors
  CHANGELOG.md
  core/internal/filetransfer/file_transfer_default.go
  core/internal/filetransfer/file_transfer_default_test.go
  core/internal/filetransfer/tasks.go
Labels: cc-fix

#7306 chore(launch): Exclude wandb and .git folders from code artifact when creating a job from the CLI
  tests/pytest_tests/system_tests/test_launch/test_job.py
  wandb/sdk/launch/create_job.py
Labels: cc-chore

#7307 refactor(core): Remove unused FileStreamCallback in FileTransferManager
  core/internal/filetransfer/file_transfer_manager.go
  core/internal/filetransfertest/filetransfertest.go
  core/pkg/filestream/filestream.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-refactor

#7308 refactor(core): Don't require filestream inputs to be protos
  core/pkg/filestream/filestream.go
  core/pkg/filestream/loop_process.go
Labels: cc-refactor

#7284 feat(core): Deduplicate CreateRunFiles invocations
  core/internal/runfiles/runfiles.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/upload_batcher.go
  core/internal/runfiles/uploader.go
  core/pkg/server/stream_init.go
Labels: cc-feat

#7314 chore(core): bump go to 1.22.2 and upgrade
  core/go.mod
  core/go.sum
Labels: cc-chore

#7102 chore(launch): internal process support for launch config file parameters
  core/pkg/launch/config.go
  core/pkg/launch/config_files.go
  core/pkg/launch/config_test.go
  core/pkg/launch/job_builder.go
  core/pkg/launch/job_builder_test.go
  core/pkg/launch/wandb_config.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
Labels: cc-chore

#7317 chore(launch): skip git job create test
  tests/pytest_tests/system_tests/test_launch/test_job.py
Labels: cc-chore

#7318 fix(core): fix a minor bug when accessing a nil object
  core/internal/filetransfer/file_transfer_default.go
Labels: cc-fix

#7223 chore(sdk): replace the gpu apple binary with the new one
  .circleci/config.yml
  apple_stats/Sources/main.swift
  core/pkg/monitor/gpu_apple.go
  wandb/bin/apple_gpu_stats
  wandb/sdk/internal/system/assets/gpu_apple.py
Labels: cc-chore

#7262 refactor(sdk): Build apple_gpu_stats in CI
  .github/workflows/release-sdk.yml
  tools/wini/wini.py
  wandb/.gitignore
  wandb/bin/apple_gpu_stats
Labels: cc-refactor

#7309 refactor(core): Extract FileStream interface for testability
  core/pkg/filestream/filestream.go
  core/pkg/filestream/filestream_test.go
  core/pkg/filestream/loop_feedback.go
  core/pkg/filestream/loop_process.go
  core/pkg/filestream/loop_transmit.go
  core/pkg/filestream/loop_transmit_test.go
  core/pkg/server/sender.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-refactor

#7310 fix(core): Notify backend of successfully uploaded run files
  core/internal/runfiles/runfiles.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
  core/pkg/filestream/filestream.go
  core/pkg/filestream/loop_process.go
  core/pkg/filestreamtest/filestreamtest.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-fix

#7320 chore(artifacts): fix link model test
  tests/functional_tests/t0_main/artifacts/public-link-model.py
  tests/functional_tests/t0_main/artifacts/public-link-model.yea
Labels: cc-chore

#7323 chore(sdk): minor go code clean up
  core/internal/execbin/execbin.go
  core/internal/shared/shared.go
  core/pkg/artifacts/linker.go
  core/pkg/artifacts/saver.go
  core/pkg/filestream/loop_process.go
  core/pkg/launch/config.go
  core/pkg/launch/config_files.go
  core/pkg/monitor/cpu.go
  core/pkg/monitor/memory.go
  core/pkg/monitor/monitor.go
  core/pkg/observability/printer.go
  core/pkg/observability/util.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
  core/pkg/server/sync.go
  core/pkg/server/writer.go
Labels: cc-chore

#7330 chore(sdk): skip tensorboard test that fails on core
  tests/functional_tests/t0_main/mp/13-synctb-gradienttape.yea
Labels: cc-chore

#7166 chore(launch): pass file overrides from launch spec to container
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/system_tests/test_launch/test_launch_local_container.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sagemaker.py
  tests/pytest_tests/system_tests/test_launch/test_launch_vertex.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/build.py
Labels: cc-chore

#7335 chore(sdk): Explain abs path folder structure in run.save() docs
  wandb/sdk/wandb_run.py
Labels: cc-chore

#7333 fix(core): harden resume logic to better handle nil responses
  core/internal/runresume/resume_test.go
  core/internal/runresume/runresume.go
  core/pkg/server/resume.go
  core/pkg/server/resume_test.go
  core/pkg/server/sender.go
Labels: cc-fix

#7228 chore(sdk): adding back the required flag for `wandb-core`
  .bumpversion.core.cfg
  .circleci/config.yml
  CHANGELOG.md
  core/README.md
  core/pkg/service/wandb_settings.pb.go
  tests/pytest_tests/system_tests/test_notebooks/test_notebooks.py
  tests/pytest_tests/unit_tests/test_util_wandb_core.py
  tox.ini
  wandb/__init__.py
  wandb/env.py
  wandb/errors/__init__.py
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/service/service.py
  wandb/sdk/wandb_require.py
  wandb/sdk/wandb_settings.py
  wandb/util.py
Labels: cc-chore

#7332 chore(artifacts): add assistive instructions to S3 error
  wandb/sdk/artifacts/storage_handlers/s3_handler.py
Labels: cc-chore

#7291 test(artifacts): add a large artifact benchmark
  tests/standalone_tests/large_artifact_benchmark.py
Labels: cc-test

#7336 chore(artifacts): check that the cache is writeable on initialization
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/artifacts/artifact_file_cache.py
Labels: cc-chore

#7325 refactor(core): minor clean up of the history sampling code
  core/internal/sampler/priority_queue.go
  core/internal/sampler/reservoir_samper.go
  core/pkg/server/handler.go
  core/pkg/server/history.go
Labels: cc-refactor

#7300 feat(core): split error reporting of `wandb_core` from `wandb`
  .bumpversion.core.cfg
  core/README.md
  core/internal/version/version.go
  core/pyproject.toml
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
  wandb/env.py
  wandb/sdk/service/service.py
  wandb/util.py
Labels: cc-feat

#7341 test(sdk): use the default timeout in file_transfer_default_test.go
  core/internal/filetransfer/file_transfer_default_test.go
Labels: cc-test

#7342 refactor(sdk): move copyFile helper function to pkg/utils/files.go
  core/pkg/server/handler.go
  core/pkg/server/util.go
  core/pkg/utils/files.go
Labels: cc-refactor

#7337 fix(artifacts): use etags instead of md5 hashes for gcs references
  CHANGELOG.md
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/artifacts/storage_handlers/gcs_handler.py
Labels: cc-fix

#7347 fix(core): propagate context cancellation if init_timeout is exceeded
  core/internal/mailbox/mailbox.go
  core/internal/runfiles/runfiles.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
  core/pkg/server/connection.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/stream_init.go
Labels: cc-fix

#7322 chore(sdk): implement a stricter check for amd gpu monitoring availability
  CHANGELOG.md
  core/pkg/monitor/gpu_amd.go
  wandb/sdk/internal/system/assets/gpu_amd.py
Labels: cc-chore

#7355 fix(core): fix file upload progress reportnig
  core/internal/filetransfer/file_transfer_stats.go
  core/pkg/server/handler.go
Labels: cc-fix

#7353 chore(artifacts): pass all artifact download options through to the wandb-core downloader
  core/pkg/artifacts/downloader.go
  core/pkg/server/sender.go
  core/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/interface/interface.py
Labels: cc-chore

#7361 chore(artifacts): fix error message when logging to a different project or entity
  tests/pytest_tests/system_tests/test_artifacts/test_public_api.py
  wandb/sdk/wandb_run.py
Labels: cc-chore

#7360 feat(core): send heartbeat to server
  core/pkg/filestream/filestream.go
  core/pkg/filestream/filestream_test.go
  core/pkg/filestream/loop_transmit.go
  core/pkg/filestream/loop_transmit_test.go
  core/pkg/filestreamtest/filestreamtest.go
  core/pkg/server/stream_init.go
Labels: cc-feat

#7369 chore(sdk): release wandb-core 0.17.0.b11
  .bumpversion.core.cfg
  core/README.md
  core/internal/version/version.go
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
Labels: cc-chore

#7370 chore(sdk): bump wandb-core version to 0.17.0.b12.dev1
  .bumpversion.core.cfg
  core/README.md
  core/internal/version/version.go
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
Labels: cc-chore

#7363 chore(artifacts): allow updates to WANDB_CACHE_DIR during execution
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_cli.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  wandb/sdk/artifacts/artifact_file_cache.py
  wandb/sdk/internal/datastore.py
Labels: cc-chore

#7344 refactor(core): Create a new watcher wrapper package
  core/internal/runfiles/uploader.go
  core/internal/watcher2/impl.go
  core/internal/watcher2/watcher2.go
  core/internal/watcher2/watcher2_test.go
Labels: cc-refactor

#7345 fix(core): Correctly watch live files
  core/internal/runfiles/runfiles.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/uploader.go
  core/internal/runfilestest/runfilestest.go
  core/internal/watcher2test/watcher2test.go
  core/pkg/server/stream_init.go
Labels: cc-fix

#7346 feat(core): Avoid race condition when uploading run files
  core/internal/runfiles/debounced_transfer.go
  core/internal/runfiles/runfiles.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/saved_file.go
  core/internal/runfiles/upload_batcher.go
  core/internal/runfiles/uploader.go
Labels: cc-feat

#7367 feat(artifacts): allow any os.PathLike as the download root
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-feat

#7352 chore(artifacts): add helper functions for verifying data/files
  core/pkg/artifacts/builder.go
  core/pkg/utils/files.go
  core/pkg/utils/hash.go
  core/pkg/utils/hash_test.go
Labels: cc-chore

#7182 chore(artifacts): use a retrying client to download manifests
  core/pkg/artifacts/manifest.go
Labels: cc-chore

#7203 docs(sdk): update contributing doc to include updated setup
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  noxfile.py
  requirements_dev.txt
  tox.ini
Labels: cc-docs

#7097 chore(artifacts): Remove latest artifact path copy summary
  wandb/sdk/internal/handler.py
Labels: cc-chore

#7381 refactor(sdk): Package wandb with wandb-core
  .bumpversion.core.cfg
  .bumpversion.wandb.cfg
  .circleci/config.yml
  .github/workflows/release-core.yml
  .github/workflows/release-sdk.yml
  .gitignore
  CHANGELOG.md
  MANIFEST.in
  apple_stats/.gitignore
  apple_stats/hatch.py
  core/.gitignore
  core/MANIFEST.in
  core/Makefile
  core/README.md
  core/docs/contributing.md
  core/hatch.py
  core/internal/version/version.go
  core/pkg/monitor/gpu_apple.go
  core/pyproject.toml
  core/setup.py
  core/wandb_core/__init__.py
  hatch.toml
  hatch_build.py
  noxfile.py
  pyproject.toml
  requirements_build.txt
  requirements_test.txt
  requirements_tools.txt
  setup.py
  tests/pytest_tests/unit_tests/test_util_wandb_core.py
  tools/wini/__init__.py
  tools/wini/arch.py
  tools/wini/print.py
  tools/wini/subprocess.py
  tools/wini/wini.py
  tools/wini/workspace.py
  tox.ini
  wandb/__init__.py
  wandb/env.py
  wandb/proto/wandb_internal_codegen.py
  wandb/sdk/service/service.py
  wandb/util.py
  wini
Labels: cc-refactor

#7386 chore(sdk): add space before ';' in requirements_dev.txt
  requirements_dev.txt
Labels: cc-chore

#7388 chore(sdk): put mypy back
  .circleci/config.yml
  wandb/analytics/sentry.py
  wandb/env.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/interface/interface.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
  wandb/sdk/lib/gitlib.py
  wandb/sdk/wandb_manager.py
  wandb/util.py
Labels: cc-chore

#7397 build(sdk): fix minor issue with build on windows
  core/hatch.py
Labels: cc-build

#7391 chore(sdk): Cache .tox in CircleCI
  .circleci/config.yml
Labels: cc-chore

#7395 chore(sdk): Replace install_command in tox envs
  tox.ini
Labels: cc-chore

#7396 chore(sdk): Move WANDB_ERROR_REPORTING in tox to base env
  tox.ini
Labels: cc-chore

#7392 chore(sdk): fix typos
  CHANGELOG.md
  core/pkg/launch/job_builder.go
  core/pkg/launch/job_builder_test.go
  core/pkg/leveldb/record_internal_test.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  tests/functional_tests/t0_main/cohere/t5_cohere_summarization.py
  tests/functional_tests/t0_main/keras/keras_subclassed_test_tf_2_6.yea
  tests/functional_tests/t0_main/sklearn/plot_classifier-basic.py
  tests/pytest_tests/system_tests/test_core/test_system_info.py
  tests/pytest_tests/system_tests/test_core/test_wandb.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/unit_tests/test_artifacts/saved_model_constructors.py
  tests/pytest_tests/unit_tests/test_import_wandb.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_ecr.py
  tests/pytest_tests/unit_tests/test_launch/test_registry/test_gcp_artifact_registry.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_vertex.py
  tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
  tests/pytest_tests/unit_tests/test_sagemaker_config_parse.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_aws.py
  tests/standalone_tests/point_cloud.py
  tools/build_launch_agent.py
  wandb/apis/reports/v1/_blocks.py
  wandb/data_types.py
  wandb/docker/__init__.py
  wandb/integration/huggingface/resolver.py
  wandb/integration/keras/callbacks/metrics_logger.py
  wandb/integration/keras/keras.py
  wandb/old/summary.py
  wandb/plot/confusion_matrix.py
  wandb/plots/precision_recall.py
  wandb/plots/roc.py
  wandb/sdk/data_types/_dtypes.py
  wandb/sdk/data_types/image.py
  wandb/sdk/data_types/video.py
  wandb/sdk/integration_utils/data_logging.py
  wandb/sdk/interface/interface.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/abstract.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/sweeps/scheduler_sweep.py
  wandb/sdk/launch/sweeps/utils.py
  wandb/sdk/lib/import_hooks.py
  wandb/sdk/lib/redirect.py
  wandb/sdk/lib/tracelog.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_setup.py
  wandb/sklearn/plot/classifier.py
  wandb/sklearn/plot/clusterer.py
  wandb/wandb_controller.py
Labels: cc-chore

#7405 chore(sdk): fix go on windows and go version
  .circleci/config.yml
Labels: cc-chore

#7390 chore(sdk): move all code checks to use noxfile
  .circleci/config.yml
  CONTRIBUTING.md
  noxfile.py
  pyproject.toml
  tox.ini
  wandb/sdk/launch/registry/google_artifact_registry.py
Labels: cc-chore

#7403 chore(sdk): Don't discriminate between unit_tests subdirectories
  .circleci/config.yml
  tox.ini
Labels: cc-chore

#7412 fix(sdk): Don't resolve() globs on Windows
  CHANGELOG.md
  wandb/sdk/wandb_run.py
Labels: cc-fix

#7414 ci(sdk): fetch and store latest local-testcontainer on GCP
  .circleci/config.yml
Labels: cc-ci

#7411 ci(sdk): add more automations to the wandb release process
  .github/workflows/pre-commit.yml
  .github/workflows/release-sdk.yml
  CHANGELOG.md
  CONTRIBUTING.md
  core/scripts/update-dev-env.txt
Labels: cc-ci

#7408 fix(sdk): fix writing port file on windows
  core/pkg/server/server.go
  core/pkg/server/util.go
Labels: cc-fix

#7415 chore(sdk): add proper windows tests
  .circleci/config.yml
Labels: cc-chore

#7407 chore(sdk): bump version to 0.17.1.dev1
  .bumpversion.wandb.cfg
  core/internal/version/version.go
  wandb/__init__.py
Labels: cc-chore

#7420 chore(sdk): migrate from appdirs (deprecated) to platformdirs
  pyproject.toml
  tests/standalone_tests/executor_tests/requirements.txt
  wandb/env.py
Labels: cc-chore

#7430 fix(core): Fix a nil pointer dereference in util.go
  core/pkg/observability/util.go
  wandb/sdk/service/service.py
Labels: cc-fix

#7418 chore(sdk): Use nox instead of tox for unit tests
  .circleci/config.yml
  .gitignore
  noxfile.py
  tox.ini
Labels: cc-chore

#7433 chore(sdk): Fix CircleCI config, forgot to update Windows unit-tests
  .circleci/config.yml
Labels: cc-chore

#7432 chore(sdk): Use uv for unit tests in CI
  .circleci/config.yml
  noxfile.py
  requirements_dev.txt
Labels: cc-chore

#7437 ci(sdk): increase sleep time before installing from TestPyPI
  .github/workflows/release-sdk.yml
Labels: cc-ci

#7438 fix(sdk): stop status nil pointer dereference check
  core/pkg/server/sender.go
Labels: cc-fix

#7439 ci(sdk): pass missing env variables in nox for unit_tests sessions
  noxfile.py
Labels: cc-ci

#7440 fix(sdk): return empty summary for finished runs
  CHANGELOG.md
  wandb/sdk/wandb_run.py
Labels: cc-fix

#7443 ci(sdk): enable nexus unit-tests on windows
  .circleci/config.yml
Labels: cc-ci

#7442 ci(sdk): skip tests launch tests that fail on windows
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
Labels: cc-ci

#7446 chore(sdk): Remove "notebooks" factor from tox.ini
  tox.ini
Labels: cc-chore

#7449 refactor(core): move timer to separate package
  core/internal/timer/timer.go
  core/pkg/server/handler.go
Labels: cc-refactor

#7448 refactor(core): use params instead of opts in stream
  core/pkg/server/handler.go
  core/pkg/server/handler_test.go
  core/pkg/server/history_test.go
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
  core/pkg/server/writer.go
Labels: cc-refactor

#7453 chore(sdk): Delete old unit test that takes 5 minutes
  tests/pytest_tests/unit_tests_old/test_core/test_offline_sync.py
Labels: cc-chore

#7454 chore(sdk): Make some test_agent.py tests run faster
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
Labels: cc-chore

#7451 chore(sdk): Give a better error message if Swift build fails
  apple_stats/hatch.py
  hatch_build.py
Labels: cc-chore

#7455 chore(launch): Make get_run_state_info back off test fast
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-chore

#7424 refactor(artifacts): reorder checks in Run.log_artifact to read more easily
  wandb/apis/public/runs.py
Labels: cc-refactor

#7456 refactor(core): minor clean up of the forward and response functions
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/server/stream.go
Labels: cc-refactor

#7429 chore(artifacts): formally deprecate already deprecated features
  core/pkg/service/wandb_telemetry.pb.go
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_deprecated.py
  wandb/proto/wandb_internal_codegen.py
  wandb/proto/wandb_telemetry.proto
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
Labels: cc-chore

#7460 refactor(core): Go nuclear in file_transfer_stats.go
  core/internal/filetransfer/file_transfer_stats.go
Labels: cc-refactor

#7458 ci(sdk): Re-enable codecov validation, use workaround
  .circleci/config.yml
Labels: cc-ci

#7462 chore(sdk): add a comment about GHA bot credentials in sdk release action
  .github/workflows/release-sdk.yml
Labels: cc-chore

#7463 fix(sdk): correctly handle nested keys in summary
  noxfile.py
  wandb/sdk/lib/proto_util.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#7464 chore(sdk): fix accidentally broken test
  wandb/sdk/wandb_run.py
Labels: cc-chore

#7465 refactor(core): create common PathTree struct and use in RunConfig
  core/internal/pathtree/pathtree.go
  core/internal/runconfig/runconfig.go
  core/internal/runconfig/runconfig_test.go
  core/pkg/server/sender.go
Labels: cc-refactor

#7471 chore(sdk): Skip recent mypy version that has a bug
  noxfile.py
Labels: cc-chore

#7385 refactor(launch): build + _project_spec cleanup
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.py
  tests/pytest_tests/system_tests/test_launch/test_agent.py
  tests/pytest_tests/system_tests/test_launch/test_launch.py
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/system_tests/test_launch/test_launch_local_container.py
  tests/pytest_tests/system_tests/test_launch/test_launch_run.py
  tests/pytest_tests/system_tests/test_launch/test_launch_sagemaker.py
  tests/pytest_tests/system_tests/test_launch/test_launch_vertex.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_public_api.py
  tests/pytest_tests/system_tests/test_sweep/test_wandb_sweep.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_config.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_context_manager.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_docker.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_kaniko.py
  tests/pytest_tests/unit_tests/test_launch/test_create_job.py
  tests/pytest_tests/unit_tests/test_launch/test_job.py
  tests/pytest_tests/unit_tests/test_launch/test_launch_docker.py
  tests/pytest_tests/unit_tests/test_launch/test_project/test_project.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_local_container.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_local_process.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_sagemaker.py
  tests/pytest_tests/unit_tests/test_launch/test_util.py
  tests/pytest_tests/unit_tests_old/test_launch/test_cli.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_aws.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_docker.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_jobs.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_local_process.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_utils.py
  tests/pytest_tests/unit_tests_old/test_launch/test_wandb_run.py
  wandb/apis/public/jobs.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/abstract.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/context_manager.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
  wandb/sdk/launch/builder/templates/dockerfile.py
  wandb/sdk/launch/create_job.py
  wandb/sdk/launch/runner/kubernetes_runner.py
  wandb/sdk/launch/runner/local_container.py
  wandb/sdk/launch/runner/local_process.py
  wandb/sdk/launch/runner/sagemaker_runner.py
  wandb/sdk/launch/runner/vertex_runner.py
  wandb/sdk/launch/utils.py
Labels: cc-refactor

#7472 ci(sdk): skip broken version instead of pinning
  noxfile.py
Labels: cc-ci

#7469 fix(core): make beta work again adding
  wandb/cli/cli.py
Labels: cc-fix

#7478 refactor(core): remove generic from treepath
  core/internal/pathtree/pathtree.go
  core/internal/pathtree/pathtree_test.go
  core/internal/runconfig/runconfig.go
  core/internal/runsummary/runsummary.go
  core/pkg/filestream/loop_process.go
Labels: cc-refactor

#7431 refactor(core): use pathtree data structure for run summary
  core/internal/corelib/summarylib.go
  core/internal/pathtree/pathtree.go
  core/internal/pathtree/pathtree_test.go
  core/internal/runconfig/runconfig.go
  core/internal/runconfig/runconfig_test.go
  core/internal/runsummary/runsummary.go
  core/pkg/filestream/loop_process.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/stream.go
  core/pkg/server/summary.go
  core/pkg/service/wandb_base.pb.go
  core/pkg/service/wandb_internal.pb.go
  core/pkg/service/wandb_server.pb.go
  core/pkg/service/wandb_settings.pb.go
  core/pkg/service/wandb_telemetry.pb.go
  core/scripts/update-dev-env.txt
  tests/pytest_tests/system_tests/test_core/test_wandb_run.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
  wandb/sdk/lib/proto_util.py
  wandb/sdk/wandb_run.py
Labels: cc-refactor

#7475 chore(artifacts): deprecate Api.artifact_versions
  core/pkg/service/wandb_telemetry.pb.go
  wandb/apis/public/api.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_deprecated.py
  wandb/proto/wandb_telemetry.proto
Labels: cc-chore

#7476 fix(artifacts): report why an artifact can't be found
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#7394 chore(launch): set build context and dockerfile in `wandb job create`
  tests/pytest_tests/unit_tests/test_job_builder.py
  tests/pytest_tests/unit_tests/test_launch/test_create_job.py
  wandb/cli/cli.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/launch/create_job.py
Labels: cc-chore

#7481 chore(launch): build uses build context and dockerfile setting from job
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_context_manager.py
  wandb/apis/public/jobs.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/context_manager.py
  wandb/sdk/launch/create_job.py
Labels: cc-chore

#7486 refactor(sdk): Migrate test_mailbox.py to pytest from unittest
  tests/pytest_tests/unit_tests/test_lib/test_mailbox.py
Labels: cc-refactor

#7487 fix(sdk): Fix wandb/util.py json_friendly() mutating its argument
  tests/pytest_tests/unit_tests/test_util.py
  wandb/util.py
Labels: cc-fix

#7484 chore(sdk): explicitly configure nox to use uv by default
  .circleci/config.yml
  CONTRIBUTING.md
  noxfile.py
Labels: cc-chore

#7364 feat(artifacts): use the cache when downloading through wandb-core
  CHANGELOG.md
  core/pkg/artifacts/downloader.go
  core/pkg/artifacts/file_cache.go
  core/pkg/artifacts/file_cache_test.go
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
Labels: cc-feat

#7492 ci(sdk): install uv for the store-local-testcontainer job in circle
  .circleci/config.yml
Labels: cc-ci

#7461 fix(launch): Warn instead of error when kaniko builder doesn't support registry type
  CHANGELOG.md
  wandb/sdk/launch/builder/kaniko_builder.py
Labels: cc-fix

#7498 refactor(core): Move FileStream.SetPath/SetOffsets into Start()
  core/pkg/filestream/filestream.go
  core/pkg/filestream/filestream_test.go
  core/pkg/filestreamtest/filestreamtest.go
  core/pkg/server/sender.go
Labels: cc-refactor

#7366 feat(artifacts): cache files when uploading with wandb-core
  CHANGELOG.md
  core/pkg/artifacts/downloader.go
  core/pkg/artifacts/file_cache.go
  core/pkg/artifacts/manifest.go
  core/pkg/artifacts/saver.go
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_cli.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
Labels: cc-feat

#7499 refactor(core): Introduce 'waiting' package for testable code with Sleep()
  core/internal/runfiles/runfiles.go
  core/internal/runfiles/runfiles_test.go
  core/internal/runfiles/upload_batcher.go
  core/internal/runfiles/uploader.go
  core/internal/waiting/waiting.go
  core/internal/waitingtest/waitingtest.go
  core/pkg/server/stream_init.go
Labels: cc-refactor

#7500 refactor(core): Use waiting.Delay in filestream
  core/pkg/filestream/collector.go
  core/pkg/filestream/collector_test.go
  core/pkg/filestream/filestream.go
  core/pkg/filestream/loop_transmit.go
Labels: cc-refactor

#7416 chore(artifacts): remove httpx-based async upload path
  CHANGELOG.md
  CONTRIBUTING.md
  core/pkg/service/wandb_settings.pb.go
  noxfile.py
  pyproject.toml
  requirements_dev.txt
  tests/pytest_tests/assets/ssl_certs/README.md
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/system_tests/test_core/test_telemetry_full.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_internal_api.py
  tests/pytest_tests/unit_tests/test_retry.py
  tests/pytest_tests/unit_tests/test_step_prepare.py
  tests/pytest_tests/unit_tests/test_step_upload.py
  tests/pytest_tests/unit_tests/test_wandb_settings.py
  wandb/apis/importers/internals/internal.py
  wandb/apis/internal.py
  wandb/filesync/step_checksum.py
  wandb/filesync/step_prepare.py
  wandb/filesync/step_upload.py
  wandb/filesync/upload_job.py
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
  wandb/sdk/artifacts/storage_policy.py
  wandb/sdk/internal/file_pusher.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/internal/progress.py
  wandb/sdk/internal/sender.py
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_init.py
  wandb/sdk/wandb_settings.py
Labels: cc-chore

#7505 refactor(core): `waiting.Stopwatch` for filestream heartbeat testability
  core/internal/waiting/waiting.go
  core/internal/waitingtest/fakedelay.go
  core/internal/waitingtest/fakestopwatch.go
  core/internal/waitingtest/waitingtest.go
  core/pkg/filestream/filestream.go
  core/pkg/filestream/filestream_test.go
  core/pkg/filestream/loop_transmit.go
Labels: cc-refactor

#7506 refactor(core): Add comments in `collector.go`
  core/pkg/filestream/collector.go
  core/pkg/filestream/loop_transmit.go
Labels: cc-refactor

#7493 chore(launch): add helpers for config file job inputs
  tests/pytest_tests/unit_tests/test_launch/test_inputs/test_files_helpers.py
  wandb/sdk/launch/inputs/files.py
Labels: cc-chore

#7509 fix(core): avoid setting the debouncer if there were no changes made
  core/pkg/server/sender.go
Labels: cc-fix

#7494 fix(launch): add source message to job input in publish method
  wandb/sdk/interface/interface.py
Labels: cc-fix

#7507 refactor(core): Remove overflow wait-skipping logic in collector.go
  core/pkg/filestream/collector.go
Labels: cc-refactor

#7508 refactor(core): Simplify `read` / `readMore` code in `collector.go`
  core/pkg/filestream/collector.go
  core/pkg/filestream/collector_test.go
  core/pkg/filestream/filestream.go
  core/pkg/filestream/filestream_test.go
  core/pkg/filestream/loop_transmit.go
Labels: cc-refactor

#7474 chore(launch): Remove project from agent config
  tests/pytest_tests/system_tests/test_launch/test_launch_sweep.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_config.py
  wandb/cli/cli.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/agent/config.py
Labels: cc-chore

#7511 chore(artifacts): update the artifact benchmark to use `wandb.require('core')`
  tests/standalone_tests/large_artifact_benchmark.py
Labels: cc-chore

#7515 refactor(core): Don't assume file upload URL doesn't change
  core/internal/runfiles/saved_file.go
Labels: cc-refactor

#7512 refactor(core): Move (nil, nil) retryablehttp output handling
  core/internal/api/api.go
  core/internal/api/send.go
  core/internal/filetransfer/file_transfer_default.go
Labels: cc-refactor

#7514 refactor(core): Create fake of `api.Client` for easier testing
  core/internal/api/api_test.go
  core/internal/apitest/apitest.go
  core/internal/clienttest/clienttest.go
  core/internal/clienttest/clienttest_gen.go
  core/internal/clienttest/generate.go
  core/pkg/filestream/filestream_test.go
  core/pkg/filestream/loop_transmit_test.go
Labels: cc-refactor

#7518 fix(core): Fix file stats tracking
  core/internal/filetransfer/file_transfer_stats.go
Labels: cc-fix

#7516 fix(sdk): cancel polling on broken pipe
  wandb/sdk/wandb_run.py
Labels: cc-fix

#7485 feat(launch): `wandb launch` a git or local uri
  CHANGELOG.md
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests/test_launch/test_util.py
  wandb/cli/cli.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/_launch_add.py
  wandb/sdk/launch/builder/context_manager.py
  wandb/sdk/launch/utils.py
Labels: cc-feat

#7495 chore(launch): add internal library for handling inputs and applying overrides
  tests/pytest_tests/unit_tests/test_launch/test_inputs/test_internal.py
  wandb/sdk/launch/inputs/internal.py
Labels: cc-chore
