Repository wandb/wandb, pull requests merged in 2024-02, with the labels that each got.

#6937 chore(core): print a message when using wandb-core
  core/README.md
  wandb/sdk/lib/_wburls_generated.py
  wandb/sdk/lib/wburls.py
  wandb/sdk/service/service.py
Labels: cc-chore

#6939 fix(artifacts): artifact file upload progress in nexus
  core/pkg/artifacts/saver.go
Labels: cc-fix

#6938 fix(sdk): exercise caution in system monitor when rocm-smi is installed on a system with no amd gpus
  core/pkg/monitor/gpu_amd.go
  tests/pytest_tests/unit_tests/test_system_metrics/test_gpu_amd.py
  wandb/sdk/internal/system/assets/gpu_amd.py
Labels: cc-fix

#6892 fix(cli): typo in cli.py
  wandb/cli/cli.py
Labels: contrib, cc-fix

#6761 build(core): package python rust bindings with go binary and use maturin
  .bumpversion.cargo.cfg
  .bumpversion.core.cfg
  client/Cargo.lock
  client/Cargo.toml
  client/pyproject.toml
  client/src/lib.rs
  client/src/printer.rs
  client/src/run.rs
  client/src/session.rs
  client/src/settings.rs
  client/wandb/__init__.py
  client/wandb_core/__init__.py
  core/setup.py
  noxfile.py
Labels: cc-build

#6908 feat(core): update go packages
  core/go.mod
  core/go.sum
  core/pkg/filestream/collector_test.go
  core/pkg/filestream/loop_transmit_test.go
Labels: cc-feat

#6933 fix(launch): remove deadsnakes from accelerator build step
  wandb/sdk/launch/builder/build.py
Labels: cc-fix

#6948 chore(sdk): Add .venv to gitignore
  .gitignore
Labels: cc-chore

#6954 chore(sdk): Bump version to 0.16.4.dev1
  .bumpversion.wandb.cfg
  CHANGELOG.md
  wandb/__init__.py
Labels: cc-chore

#6956 chore(sdk): Don't exit in 'wandb beta' if wandb-core not found
  wandb/cli/cli.py
Labels: cc-chore

#6961 chore(sdk): Write 'wandb beta' error to stderr
  wandb/cli/cli.py
Labels: cc-chore

#6955 chore(launch): scrub launch_metadata.json from codebase
  tests/pytest_tests/unit_tests_old/test_launch/test_launch.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_aws.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
Labels: cc-chore

#6959 fix(launch): Fix passing of template variables in the sweeps-on-launch scheduler
  wandb/sdk/launch/sweeps/scheduler.py
  wandb/sdk/launch/utils.py
Labels: cc-fix

#6940 fix(launch): link job artifact to a run
  core/pkg/artifacts/saver.go
  core/pkg/launch/job_builder.go
  core/pkg/server/handler.go
Labels: cc-fix

#6958 refactor(launch): refactor use of asyncio in launch agent1
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_cli.py
  wandb/cli/cli.py
  wandb/sdk/launch/_launch_add.py
Labels: cc-refactor

#6960 refactor(launch): clean up launch project
  tests/pytest_tests/system_tests/test_launch/test_launch.py
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
  tests/pytest_tests/unit_tests/test_launch/test_project/test_project.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_docker.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/_launch_add.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/agent/agent.py
  wandb/sdk/launch/builder/build.py
Labels: cc-refactor

#6970 chore(sdk): fix a nox function missing a session argument
  noxfile.py
Labels: cc-chore

#6969 fix(launch): Fix sagemaker entrypoint to use given entrypoint
  tests/pytest_tests/system_tests/test_launch/test_launch_sagemaker.py
  wandb/sdk/launch/runner/sagemaker_runner.py
Labels: cc-fix

#6947 refactor(sdk): Add `wini package {release,testing,install}` replacing nox sessions
  .circleci/config.yml
  .github/workflows/release-core.yml
  .gitignore
  core/docs/contributing.md
  core/pkg/monitor/apple/winibuild.py
  core/setup.py
  core/winibuild.py
  noxfile.py
  requirements_tools.txt
  tools/wini/__init__.py
  tools/wini/wini.py
  tools/wini/workspace.py
  tox.ini
  wini
Labels: cc-refactor

#6962 chore(sdk): Improve printed output in wini
  core/pkg/monitor/apple/winibuild.py
  core/winibuild.py
  requirements_tools.txt
  tools/wini/print.py
  tools/wini/subprocess.py
  tools/wini/wini.py
  tox.ini
Labels: cc-chore

#6980 chore(sdk): Delete ./core/dist/ directory when rebuilding in wini
  .gitignore
  tools/wini/subprocess.py
  tools/wini/wini.py
Labels: cc-chore

#6979 chore(sdk): Use a single unit test job in CircleCI
  .circleci/config.yml
  tox.ini
Labels: cc-chore

#6983 fix(core): parse upload headers correctly
  core/internal/filetransfer/file_transfer_default.go
  core/internal/filetransfer/file_transfer_default_test.go
  core/internal/filetransfer/file_transfer_manager.go
  core/internal/filetransfer/tasks.go
  core/pkg/artifacts/downloader.go
  core/pkg/artifacts/saver.go
  core/pkg/server/sender.go
Labels: cc-fix

#6944 fix(core): properly propagate server errors
  core/internal/clients/retry_policy.go
  core/internal/clients/retry_policy_test.go
  core/pkg/server/sender.go
Labels: cc-fix

#6975 fix(core): make file upload faster by using parallelism
  core/pkg/server/sender.go
Labels: cc-fix

#6984 fix(core): don't send git data if it's not populated
  core/pkg/server/handler.go
Labels: cc-fix

#6991 chore(sdk): Bump core version to 0.17.0b9
  .bumpversion.cargo.cfg
  .bumpversion.core.cfg
  .github/workflows/release-core.yml
  client/Cargo.toml
  core/README.md
  core/internal/version/version.go
  core/setup.py
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
Labels: cc-chore

#6990 chore(sdk): Don't use "rm" in wini
  tools/wini/wini.py
Labels: cc-chore

#6992 chore(core): fix pre-commit clippy
  client/Cargo.lock
Labels: cc-chore

#6963 fix(sdk): fix console logging resumption, avoid overwrite
  wandb/sdk/internal/file_stream.py
Labels: cc-fix

#6971 feat(artifacts): Add ability to change artifact collection types
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  wandb/apis/public/artifacts.py
Labels: cc-feat

#6994 chore(sdk): Use codecov's CircleCI orb instead of custom nox session
  .circleci/config.yml
  noxfile.py
  tox.ini
Labels: cc-chore

#6996 docs(artifacts): remove from doc string that we can use artifact with digest
  wandb/sdk/wandb_run.py
Labels: cc-docs

#7001 chore(core): bump go version and update dependencies
  .circleci/config.yml
  core/go.mod
  core/go.sum
Labels: cc-chore

#6999 fix(cli): remove hostname validation when using --host on wandb login
  tests/pytest_tests/unit_tests/test_lib/test_apikey.py
  wandb/sdk/lib/apikey.py
Labels: contrib, cc-fix

#7000 refactor(sdk): Factor out config manipulation logic in sender.py
  tests/pytest_tests/unit_tests/test_lib/test_apikey.py
  tests/pytest_tests/unit_tests/test_sender_config.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/sender_config.py
  wandb/sdk/lib/config_util.py
Labels: cc-refactor

#7005 fix(sdk): Don't discard past visualizations when resuming a run
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/sender_config.py
Labels: cc-fix

#7002 chore(sdk): remove the use of `pkg_resources`
  tests/pytest_tests/unit_tests/test_plots.py
  tests/standalone_tests/all_media_types.py
  tools/check-protobuf-version-compatibility.py
  tools/setup_dev_environment.py
  wandb/apis/public/api.py
  wandb/integration/gym/__init__.py
  wandb/integration/keras/callbacks/model_checkpoint.py
  wandb/integration/keras/keras.py
  wandb/integration/kfp/kfp_patch.py
  wandb/integration/openai/fine_tuning.py
  wandb/sdk/data_types/base_types/wb_value.py
  wandb/sdk/data_types/image.py
  wandb/sdk/internal/profiler.py
  wandb/sdk/internal/sender.py
  wandb/sdk/internal/update.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/verify/verify.py
  wandb/sdk/wandb_run.py
  wandb/util.py
Labels: cc-chore

#7011 fix(core): avoid retrying on conflict status code
  core/internal/clients/retry_policy.go
Labels: cc-fix

#7014 chore(sdk): add SDK as codeowners of the CI configs
  .github/CODEOWNERS
Labels: cc-chore

#7015 chore(sdk): Fix variable name in sender_config.py
  wandb/sdk/internal/sender_config.py
Labels: cc-chore

#7017 ci(sdk): Remove legacy unit test macOS jobs
  .circleci/config.yml
Labels: cc-ci

#7016 chore(sdk): Delete unused system_tests/test_sdk_core/ dir
  tests/pytest_tests/system_tests/test_sdk_core/test_core.py
Labels: cc-chore

#7009 refactor(sdk): Factor out RunConfig in Go code
  core/pkg/server/config.go
  core/pkg/server/config_test.go
  core/pkg/server/sender.go
Labels: cc-refactor

#7012 fix(sdk): Fix visualization config merging for resumed runs in wandb-core
  core/pkg/server/config.go
  core/pkg/server/resume.go
  core/pkg/server/resume_test.go
  core/pkg/server/sender.go
Labels: cc-fix

#7027 fix(core): replace usage of standard library's json with `segmentio`'s
  core/pkg/server/handler.go
Labels: cc-fix

#7022 fix(core): remove stderr as writer for the logs
  core/cmd/wandb-core/main.go
  core/pkg/server/logging.go
  core/pkg/server/server.go
  core/pkg/server/stream.go
  wandb/sdk/service/service.py
Labels: cc-fix

#7030 fix(core): disable negative steps from initialization
  core/pkg/server/history.go
Labels: cc-fix

#7029 chore(sdk): Remove unused empty file
  tools/build_install_nexus
Labels: cc-chore

#7038 chore(sdk): Use better Go style in config.go
  core/pkg/server/config.go
  core/pkg/server/config_test.go
  core/pkg/server/sender.go
Labels: cc-chore

#7034 chore(sdk): remove regression tests that are not used anymore
  .circleci/config.yml
  tools/check-protobuf-version-compatibility.py
Labels: cc-chore

#7041 chore(launch): Fix log artifact record for nexus job builder
  core/pkg/launch/job_builder.go
  core/pkg/launch/job_builder_test.go
  core/pkg/server/sender.go
Labels: cc-chore

#7018 chore(artifacts): Add API override for Artifacts to fix multipart upload issue with Importer
  wandb/sdk/artifacts/artifact_manifest.py
  wandb/sdk/artifacts/artifact_manifests/artifact_manifest_v1.py
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
  wandb/sdk/artifacts/storage_policy.py
  wandb/sdk/internal/internal_api.py
Labels: cc-chore

#6987 chore(sdk): Report API: Remove v2 welcome message
  wandb/apis/reports/v2/__init__.py
Labels: cc-chore

#7049 fix(artifacts): Revert "make upload request async to support progress reporting (#6497)"
  tests/pytest_tests/system_tests/test_artifacts/test_artifact_saver.py
  tests/pytest_tests/system_tests/test_artifacts/test_misc2.py
  tests/pytest_tests/system_tests/test_artifacts/test_model_workflows.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
  tests/pytest_tests/system_tests/test_core/test_cli_full.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_saver.py
  wandb/sdk/interface/interface.py
  wandb/sdk/interface/interface_shared.py
  wandb/sdk/internal/job_builder.py
  wandb/sdk/internal/sender.py
  wandb/sdk/service/streams.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#7031 refactor(sdk): Create 'api' package in core
  core/internal/api/api.go
  core/internal/api/send.go
  core/internal/apitest/apitest.go
  core/pkg/filestream/filestream.go
  core/pkg/filestream/filestream_test.go
  core/pkg/filestream/loop_transmit.go
  core/pkg/filestream/loop_transmit_test.go
  core/pkg/server/sender.go
Labels: cc-refactor

#7045 feat(sdk): Respect rate-limiting headers
  core/internal/api/api.go
  core/internal/api/ratelimit.go
  core/internal/api/send.go
  core/internal/api/transport.go
Labels: cc-feat

#7050 chore(launch): remove legacy agent deployment manifests
  wandb/sdk/launch/deploys/Dockerfile
  wandb/sdk/launch/deploys/aws-ec2/launch-config.yaml
  wandb/sdk/launch/deploys/aws-eks/launch-agent.yaml
  wandb/sdk/launch/deploys/aws-eks/launch-config.yaml
  wandb/sdk/launch/deploys/gcp-gke/launch-agent.yaml
  wandb/sdk/launch/deploys/gcp-gke/launch-config.yaml
  wandb/sdk/launch/deploys/gcp-vertex/launch-config.yaml
  wandb/sdk/launch/deploys/kubernetes/launch-agent.yaml
  wandb/sdk/launch/deploys/kubernetes/launch-config.yaml
Labels: cc-chore

#6978 chore(launch): add deprecation warning if registry block is used
  wandb/sdk/launch/loader.py
Labels: cc-chore

#7044 refactor(sdk): Use new 'api' package for GraphQL requests as well
  core/internal/api/api.go
  core/internal/api/send.go
  core/internal/apitest/apitest.go
  core/internal/clients/clients.go
  core/internal/clients/clients_test.go
  core/pkg/server/sender.go
Labels: cc-refactor

#6964 feat(launch): add support for installing deps from pyproject.toml
  pyproject.toml
  tests/pytest_tests/system_tests/test_launch/test_launch_cli.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  tests/pytest_tests/unit_tests/test_launch/test_create_job.py
  wandb/sdk/launch/_project_spec.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/create_job.py
Labels: cc-feat

#7058 feat(sdk): Use a hard-coded limit for requests to the backend
  core/internal/api/api.go
  core/internal/api/api_test.go
  core/internal/api/transport.go
Labels: cc-feat

#7055 chore(sdk): Increase timeout for non-unit Linux tests
  .circleci/config.yml
Labels: cc-chore

#7052 chore(artifacts): add implementation for sendArtifact in nexus
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
Labels: cc-chore

#7028 chore(core): enable wandb-core for all the functional tests
  .circleci/config.yml
  tests/functional_tests/t0_main/artifacts/link-artifact.yea
  tests/functional_tests/t0_main/artifacts/link-model.yea
  tests/functional_tests/t0_main/artifacts/log-artifact.yea
  tests/functional_tests/t0_main/artifacts/public-link-model.yea
  tests/functional_tests/t0_main/artifacts/use-and-link-model.yea
  tests/functional_tests/t0_main/artifacts/use-model.yea
  tests/functional_tests/t0_main/catboost/t1_regression.yea
  tests/functional_tests/t0_main/debug/t2_tracelog_logger.py
  tests/functional_tests/t0_main/fastai/t1_v1.yea
  tests/functional_tests/t0_main/jax/01-log-bfloat16.yea
  tests/functional_tests/t0_main/jobs/job_artifact_creation.yea
  tests/functional_tests/t0_main/jobs/job_artifact_creation_disabled.yea
  tests/functional_tests/t0_main/jobs/job_container_creation.yea
  tests/functional_tests/t0_main/jobs/job_repo_creation.yea
  tests/functional_tests/t0_main/jobs/job_repo_end_to_end.yea
  tests/functional_tests/t0_main/lightgbm/t1_regression.yea
  tests/functional_tests/t0_main/lightgbm/t2_regression.yea
  tests/functional_tests/t0_main/lightning/t0_strategy_ddp.yea
  tests/functional_tests/t0_main/lightning/t1_strategy_ddp_spawn.yea
  tests/functional_tests/t0_main/lightning/train_tpu_ddp.yea
  tests/functional_tests/t0_main/lightning_fabric/test_fabric_logging.yea
  tests/functional_tests/t0_main/lightning_fabric/test_lightning_trainer_logging.yea
  tests/functional_tests/t0_main/lightning_fabric/test_logger_logging.yea
  tests/functional_tests/t0_main/mp/05-pool-nofinish.yea
  tests/functional_tests/t0_main/prefect_ray/t1_prefect_ray_workflow.yea
  tests/functional_tests/t0_main/prodigy/prodigy_integration.py
  tests/functional_tests/t0_main/profiler/profiler.yea
  tests/functional_tests/t0_main/sacred/t1_regression.yea
  tests/functional_tests/t0_main/save/save-dir.py
  tests/functional_tests/t0_main/sb3/t1_stable_baselines3.yea
  tests/functional_tests/t0_main/tensorflow/t1_tensorflow_log.yea
  tests/functional_tests/t0_main/tensorflow/t2_tensorflow_hook.yea
  tests/functional_tests/t0_main/torch/t1_sparse_tensors.yea
  tests/functional_tests/t0_main/torch/t2_mp_simple.yea
  tests/functional_tests/t0_main/torch/t3_ddp_basic.yea
  tests/standalone_tests/mitm_tests/t2_fs_inject.yea
  tox.ini
Labels: cc-chore

#7072 ci(sdk): clean up system tests to use a single job spec
  .circleci/config.yml
  tests/pytest_tests/system_tests/test_functional/test_mode_shared.py
  tests/pytest_tests/system_tests/test_sweep/test_wandb_sweep.py
  tests/pytest_tests/system_tests/test_system_metrics/test_open_metrics.py
Labels: cc-ci

#7075 chore(sdk): remove deprecated coverage check tool
  tools/coverage-tool.py
  tox.ini
Labels: cc-chore
