Repository wandb/wandb, pull requests merged in 2024-01, with the labels that each got.

#6767 fix(core): put back the upload file count
  client/src/wandb_internal.rs
  core/internal/filetransfer/file_transfer_default_test.go
  core/internal/filetransfer/tasks.go
  core/pkg/artifacts/downloader.go
  core/pkg/artifacts/saver.go
  core/pkg/server/git.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
Labels: cc-fix

#6769 feat(core): add TensorBoard log dir watcher
  core/internal/watcher/event.go
  core/internal/watcher/registry.go
  core/internal/watcher/watcher.go
  core/pkg/monitor/monitor.go
  core/pkg/server/files.go
  core/pkg/server/handler.go
  core/pkg/server/stream.go
  core/pkg/server/tb.go
Labels: cc-feat

#6763 test(core): add tests for watcher
  .vscode/settings.json
  core/internal/debounce/debounce_test.go
  core/internal/watcher/event.go
  core/internal/watcher/registry.go
  core/internal/watcher/watcher.go
  core/internal/watcher/watcher_test.go
  core/scripts/pre-commit-hooks/run-go-unit-tests.sh
  tests/pytest_tests/system_tests/test_core/test_sync_tb.py
Labels: cc-test

#6787 fix(core): add send cancel request to sender
  core/pkg/server/sender.go
Labels: cc-fix

#6790 fix(core): check errors in memory monitoring
  core/pkg/monitor/memory.go
Labels: cc-fix

#6786 chore(core): release wandb-core 0.17.0b6
  .bumpversion.core.cfg
  core/README.md
  core/internal/version/version.go
  core/setup.py
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
Labels: cc-chore

#6523 fix(sdk): add job_type flag in CLI to allow override of job_type
  wandb/cli/cli.py
  wandb/sync/sync.py
Labels: cc-fix

#6741 fix(integrations): Handle ultralytics utils import refactor
  wandb/integration/ultralytics/bbox_utils.py
  wandb/integration/ultralytics/callback.py
  wandb/integration/yolov8/yolov8.py
Labels: contrib, cc-fix

#6795 chore(integrations): fix linting in ultralytics integration
  tests/pytest_tests/system_tests/test_core/test_sync_tb.py
  wandb/integration/ultralytics/bbox_utils.py
  wandb/integration/ultralytics/callback.py
Labels: cc-chore

#6798 fix(core): download artifacts with wandb-core without an active run
  core/internal/filetransfer/file_transfer_manager.go
  core/pkg/artifacts/manifest.go
  core/pkg/server/sender.go
  tests/pytest_tests/system_tests/test_artifacts/test_model_workflows.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-fix

#6724 fix(sdk): fix error logging matplotlib scatter plot if the minimum version of plotly library is not met
  pyproject.toml
Labels: contrib, cc-fix

#6781 feat(core): upload wandb-summary.json and config.yaml files
  core/go.mod
  core/internal/watcher/watcher.go
  core/pkg/server/files.go
  core/pkg/server/handler.go
  core/pkg/server/sender.go
  core/pkg/server/stream.go
Labels: cc-feat

#6806 test(sdk): fix code-check and a test in watcher_test.go
  core/internal/watcher/watcher_test.go
  tox.ini
Labels: cc-test

#6708 fix(sdk): allow overriding the default .netrc location with NETRC env var
  tests/pytest_tests/conftest.py
  tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
  tests/pytest_tests/unit_tests/test_cli.py
  tests/pytest_tests/unit_tests/test_lib/test_apikey.py
  wandb/sdk/lib/apikey.py
Labels: cc-fix

#6814 chore(sdk): merge dev branch into main
  .bumpversion.wandb.cfg
  CHANGELOG.md
  wandb/__init__.py
Labels: cc-chore

#6815 ci(sdk): increase wait time to make sure we get the latest version
  .github/workflows/release-sdk.yml
Labels: cc-ci

#6818 fix(launch): Remove project and runner fields from agent config
  wandb/cli/cli.py
  wandb/sdk/launch/_launch.py
  wandb/sdk/launch/agent/agent.py
Labels: cc-fix

#6824 fix(launch): recognize deleted k8s jobs as failed
  tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py
  tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py
  wandb/sdk/launch/runner/kubernetes_monitor.py
  wandb/sdk/launch/runner/kubernetes_runner.py
Labels: cc-fix

#6827 feat(core): generate data type info in core
  core/internal/data_types/data_types.go
  core/internal/data_types/data_types_test.go
  core/internal/watcher/watcher_test.go
  wandb/sdk/data_types/_dtypes.py
Labels: cc-feat

#6833 fix(launch): warn of extra fields in environment block instead of erroring
  wandb/sdk/launch/agent/config.py
Labels: cc-fix

#6822 feat(core): add support for Launch 🚀
  .circleci/config.yml
  core/internal/data_types/data_types.go
  core/internal/data_types/data_types_test.go
  core/pkg/artifacts/builder.go
  core/pkg/artifacts/builder_test.go
  core/pkg/artifacts/manifest.go
  core/pkg/artifacts/saver.go
  core/pkg/launch/job_builder.go
  core/pkg/launch/job_builder_test.go
  core/pkg/server/sender.go
  core/pkg/server/sender_test.go
  core/pkg/utils/files.go
  core/pkg/utils/files_test.go
  core/pkg/utils/utils.go
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_core/test_data_types_full.py
  tests/pytest_tests/system_tests/test_launch/test_job.py
  tests/pytest_tests/system_tests/test_launch/test_launch_add.py
  tests/pytest_tests/unit_tests/test_data_types.py
  tests/pytest_tests/unit_tests/test_model_workflows.py
  tests/pytest_tests/unit_tests/test_tables.py
Labels: cc-feat

#6844 fix(launch): Local container runner doesn't ignore override args
  wandb/sdk/launch/runner/local_container.py
Labels: cc-fix

#6841 fix(sdk): merge-update config with sweep/launch config
  tests/pytest_tests/system_tests/test_core/test_sync_tb.py
  tests/pytest_tests/unit_tests/test_library_public.py
  tests/pytest_tests/unit_tests/test_wandb_config.py
  wandb/sdk/lib/config_util.py
  wandb/sdk/wandb_config.py
  wandb/sdk/wandb_run.py
Labels: cc-fix

#6845 ci(sdk): store local-testcontainer's of local server releases
  .circleci/config.yml
  core/internal/data_types/data_types_test.go
  noxfile.py
Labels: cc-ci

#6847 fix(sdk): fix retry logic in wandb-core and system_tests conftest
  .circleci/config.yml
  client/src/wandb_internal.rs
  core/internal/clients/backoff.go
  core/internal/clients/clients.go
  core/internal/data_types/data_types_test.go
  core/internal/filetransfer/file_transfer_default_test.go
  core/pkg/gowandb/settings/settings.go
  core/pkg/server/sender.go
  core/pkg/service/wandb_settings.pb.go
  core/scripts/build/Dockerfile
  pyproject.toml
  tests/pytest_tests/system_tests/conftest.py
  tests/pytest_tests/system_tests/test_core/test_wandb_init.py
  tests/standalone_tests/executor_tests/executor-pex.sh
  tests/standalone_tests/executor_tests/requirements.txt
  tox.ini
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/wandb_settings.py
Labels: cc-fix

#6853 chore(core): store version info in header message
  client/src/wandb_internal.rs
  core/cmd/wandb-core/main.go
  core/internal/version/version.go
  core/pkg/observability/util.go
  core/pkg/server/handler.go
  core/pkg/service/wandb_internal.pb.go
  wandb/proto/v3/wandb_internal_pb2.py
  wandb/proto/v3/wandb_internal_pb2.pyi
  wandb/proto/v4/wandb_internal_pb2.py
  wandb/proto/v4/wandb_internal_pb2.pyi
  wandb/proto/wandb_internal.proto
Labels: cc-chore

#6854 chore(core): release wandb-core 0.17.0b7
  .bumpversion.core.cfg
  core/README.md
  core/internal/version/version.go
  core/setup.py
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
Labels: cc-chore

#6855 fix(launch): set build context to entrypoint dir if it contains Dockerfile.wandb
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
  tests/pytest_tests/unit_tests/test_launch/test_builder/test_kaniko.py
  tests/pytest_tests/unit_tests_old/test_launch/test_launch_docker.py
  wandb/sdk/launch/builder/build.py
  wandb/sdk/launch/builder/docker_builder.py
  wandb/sdk/launch/builder/kaniko_builder.py
Labels: cc-fix

#6861 fix(launch): wandb job create should not look for requirements.txt if Dockerfile.wandb is next to entrypoint
  tests/pytest_tests/unit_tests/test_launch/test_create_job.py
  wandb/sdk/launch/create_job.py
Labels: cc-fix

#6862 refactor(core): redo header to be more idiomatic
  core/pkg/server/store.go
  core/pkg/server/store_test.go
Labels: cc-refactor

#6858 fix(sdk): fix _parse_path when only id is passed to wandb.Api().run()
  tests/pytest_tests/unit_tests/test_public_api.py
  wandb/apis/public/api.py
Labels: cc-fix

#6840 feat(public-api): Added option to control number of grouped sampled runs in reports
  wandb/apis/reports/_panels.py
Labels: cc-feat

#6830 docs(sdk): Update sweep docstrings
  tests/functional_tests/t0_main/doctest/one-parameter-sweep-agent.yea
  tests/functional_tests/t0_main/doctest/one-parameter-sweep.yea
  wandb/cli/cli.py
  wandb/sdk/wandb_sweep.py
  wandb/wandb_agent.py
Labels: cc-docs

#6887 fix(media): Update video.py: Fix fps bug
  wandb/sdk/data_types/video.py
Labels: cc-fix

#6888 chore(media): lint main
  wandb/sdk/data_types/video.py
Labels: cc-chore

#6889 feat(launch): passthrough queue driver
  wandb/sdk/launch/queue_driver/abstract.py
  wandb/sdk/launch/queue_driver/passthrough.py
  wandb/sdk/launch/queue_driver/standard_queue_driver.py
Labels: cc-feat

#6882 feat(sdk): add shared mode to enable multiple independent writers to the same run
  .circleci/config.yml
  client/src/wandb_internal.rs
  core/pkg/filestream/filestream.go
  core/pkg/filestream/loop_process.go
  core/pkg/server/history.go
  core/pkg/server/sender.go
  core/pkg/service/wandb_settings.pb.go
  core/scripts/generate-proto.sh
  tests/pytest_tests/assets/scripts/eval.py
  tests/pytest_tests/assets/scripts/train.py
  tests/pytest_tests/system_tests/test_functional/test_mode_shared.py
  wandb/proto/v3/wandb_settings_pb2.py
  wandb/proto/v3/wandb_settings_pb2.pyi
  wandb/proto/v4/wandb_settings_pb2.py
  wandb/proto/v4/wandb_settings_pb2.pyi
  wandb/proto/wandb_settings.proto
  wandb/sdk/lib/_settings_toposort_generated.py
  wandb/sdk/wandb_run.py
  wandb/sdk/wandb_settings.py
Labels: cc-feat

#6890 chore(core): release wandb-core 0.17.0b8
  .bumpversion.core.cfg
  core/README.md
  core/internal/version/version.go
  core/setup.py
  core/wandb_core/__init__.py
  noxfile.py
  wandb/__init__.py
Labels: cc-chore

#6878 perf(artifacts): Reduce artifact download latency via optional cache copy + threads
  tests/pytest_tests/unit_tests/test_artifacts/test_artifact_manifest_entry.py
  tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/artifacts/artifact_file_cache.py
  wandb/sdk/artifacts/artifact_manifest_entry.py
  wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
  wandb/sdk/artifacts/storage_policy.py
Labels: cc-perf

#6891 fix(sdk): clean up temp folders
  wandb/__init__.py
  wandb/cli/cli.py
  wandb/data_types.py
  wandb/sdk/artifacts/artifact.py
  wandb/sdk/data_types/_private.py
  wandb/sdk/internal/file_pusher.py
  wandb/sync/__init__.py
  wandb/sync/sync.py
Labels: cc-fix

#6899 chore(artifacts): add docstrings for artifact collection method on public api
  wandb/apis/public/api.py
Labels: cc-chore

#6904 feat(launch): jobset dif
  wandb/apis/internal.py
  wandb/sdk/internal/internal_api.py
  wandb/sdk/launch/agent2/agent.py
  wandb/sdk/launch/agent2/controllers/local_process.py
  wandb/sdk/launch/agent2/job_set.py
Labels: cc-feat

#6900 feat(launch): Implement LocalProcessManager using QueueDriver
  wandb/sdk/launch/agent2/controllers/local_process.py
  wandb/sdk/launch/queue_driver/passthrough.py
Labels: cc-feat

#6911 feat(artifacts): Add partial file downloads, via directory prefix
  tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
  wandb/sdk/artifacts/artifact.py
Labels: cc-feat

#6916 refactor(sdk): Add "proto-go" to noxfile.py
  noxfile.py
Labels: cc-refactor

#6846 fix(artifacts): fix long artifact paths on Windows
  wandb/sdk/artifacts/artifact_manifest_entry.py
Labels: cc-fix

#6880 docs(sdk): Updates the Tables reference docs.
  tests/functional_tests/t0_main/doctest/table-construct-dataframe.yea
  tests/functional_tests/t0_main/doctest/table-construct-rowwise.yea
  tests/functional_tests/t0_main/doctest/table-logging-direct.yea
  wandb/data_types.py
Labels: cc-docs

#6921 refactor(sdk): Add proto-python nox session
  noxfile.py
Labels: cc-refactor

#6825 docs(sdk): Artifact docstrings PR draft
  wandb/sdk/artifacts/artifact.py
Labels: cc-docs

#6804 feat(integrations): Update the Diffusers Integration
  tests/functional_tests/t0_main/diffusers/t1_sdxl_generation.py
  tests/functional_tests/t0_main/diffusers/t1_sdxl_generation.yea
  tests/functional_tests/t0_main/diffusers/t2_pixart_alpha_generation.py
  tests/functional_tests/t0_main/diffusers/t2_pixart_alpha_generation.yea
  tests/functional_tests/t0_main/diffusers/t3_sd_batched_generation.py
  tests/functional_tests/t0_main/diffusers/t3_sd_batched_generation.yea
  tests/functional_tests/t0_main/diffusers/t4_audioldm2_generation.py
  tests/functional_tests/t0_main/diffusers/t4_audioldm2_generation.yea
  tests/functional_tests/t0_main/diffusers/t5_animatediff_generation.py
  tests/functional_tests/t0_main/diffusers/t5_animatediff_generation.yea
  wandb/integration/diffusers/autologger.py
  wandb/integration/diffusers/pipeline_resolver.py
  wandb/integration/diffusers/resolvers/__init__.py
  wandb/integration/diffusers/resolvers/multimodal.py
  wandb/integration/diffusers/resolvers/sdxl.py
  wandb/integration/diffusers/resolvers/utils.py
Labels: cc-feat

#6638 refactor(sdk): Refactor Report API and include limited json validation
  .circleci/config.yml
  pyproject.toml
  requirements_dev.txt
  tests/pytest_tests/system_tests/test_core/test_report_api.py
  tests/pytest_tests/unit_tests/test_reports/test_reports.py
  tox.ini
  wandb/apis/reports/__init__.py
  wandb/apis/reports/v1/__init__.py
  wandb/apis/reports/v1/_blocks.py
  wandb/apis/reports/v1/_helpers.py
  wandb/apis/reports/v1/_panels.py
  wandb/apis/reports/v1/_templates.py
  wandb/apis/reports/v1/blocks.py
  wandb/apis/reports/v1/helpers.py
  wandb/apis/reports/v1/mutations.py
  wandb/apis/reports/v1/panels.py
  wandb/apis/reports/v1/report.py
  wandb/apis/reports/v1/runset.py
  wandb/apis/reports/v1/templates.py
  wandb/apis/reports/v1/util.py
  wandb/apis/reports/v1/validators.py
  wandb/apis/reports/v2/__init__.py
  wandb/apis/reports/v2/blocks.py
  wandb/apis/reports/v2/expr_parsing.py
  wandb/apis/reports/v2/gql.py
  wandb/apis/reports/v2/interface.py
  wandb/apis/reports/v2/internal.py
  wandb/apis/reports/v2/metrics.py
  wandb/apis/reports/v2/panels.py
Labels: cc-refactor

#6796 feat(integrations): Update Ultralytics Integration
  tests/functional_tests/t0_main/ultralytics/test_ultralytics_classification.py
  tests/functional_tests/t0_main/ultralytics/test_ultralytics_classification.yea
  tests/functional_tests/t0_main/ultralytics/test_ultralytics_detection.py
  tests/functional_tests/t0_main/ultralytics/test_ultralytics_detection.yea
  tests/functional_tests/t0_main/ultralytics/test_ultralytics_pose.py
  tests/functional_tests/t0_main/ultralytics/test_ultralytics_pose.yea
  tests/functional_tests/t0_main/ultralytics/test_ultralytics_segmentation.py
  tests/functional_tests/t0_main/ultralytics/test_ultralytics_segmentation.yea
  wandb/integration/ultralytics/__init__.py
  wandb/integration/ultralytics/bbox_utils.py
  wandb/integration/ultralytics/callback.py
  wandb/integration/ultralytics/classification_utils.py
  wandb/integration/ultralytics/mask_utils.py
  wandb/integration/ultralytics/pose_utils.py
Labels: cc-feat

#6919 feat(integrations): Add Pytorch Lightning Fabric Logger
  client/src/wandb_internal.rs
  core/pkg/service/wandb_telemetry.pb.go
  tests/functional_tests/t0_main/lightning_fabric/pl_base.py
  tests/functional_tests/t0_main/lightning_fabric/test_fabric_logging.py
  tests/functional_tests/t0_main/lightning_fabric/test_fabric_logging.yea
  tests/functional_tests/t0_main/lightning_fabric/test_lightning_trainer_logging.py
  tests/functional_tests/t0_main/lightning_fabric/test_lightning_trainer_logging.yea
  tests/functional_tests/t0_main/lightning_fabric/test_logger_logging.py
  tests/functional_tests/t0_main/lightning_fabric/test_logger_logging.yea
  wandb/integration/lightning/__init__.py
  wandb/integration/lightning/fabric/__init__.py
  wandb/integration/lightning/fabric/logger.py
  wandb/proto/v3/wandb_telemetry_pb2.py
  wandb/proto/v3/wandb_telemetry_pb2.pyi
  wandb/proto/v4/wandb_telemetry_pb2.py
  wandb/proto/v4/wandb_telemetry_pb2.pyi
  wandb/proto/wandb_telemetry.proto
Labels: cc-feat

#6925 fix(sdk): Update Report API to work with pydantic2.6
  tox.ini
  wandb/apis/reports/v2/interface.py
Labels: cc-fix

#6922 refactor(sdk): Remove proto envs from tox.ini and make Make use nox
  .circleci/config.yml
  Makefile
  noxfile.py
  tox.ini
Labels: cc-refactor

#6926 fix(launch): fetch all commits to enable checking out by sha
  wandb/sdk/launch/git_reference.py
Labels: cc-fix

#6927 fix(sweeps): dont swallow exceptions in pyagent
  wandb/agents/pyagent.py
Labels: cc-fix
